%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
    function SP2_MARSS_MARSSMain
%% 
%%  Main window for MRS Simulation
%%
%%  12-2019, Christoph Juchem
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global fm fmfig pars flag marss 


if ~SP2_ClearWindow
    fprintf('\n--- WARNING ---\nClearing of window figure handles failed.\n\n')
    return
end
flag.fmWin = 10;
pars.figPos = get(fmfig,'Position');
set(fmfig,'Name',' INSPECTOR: MR Spectral Simulation Tool','Position',...
    [pars.figPos(1) pars.figPos(2) pars.mainDims(3) pars.mainDims(4)])


%**************************************************************************************************
%    D A T A     F O R M A T  
%**************************************************************************************************
% MRS sequence
fm.marss.sequNameLab   = text('Position',[-0.145, 1.030],'String','Sequence','FontSize',pars.fontSize);
fm.marss.sequName      = uicontrol('Style','Popup','String',SP2_CellArrayToStrList(marss.sequNameCell,'|'),'Value',flag.marssSequName,...
                                   'Position',[120 669 160 8],'Callback','SP2_MARSS_SequenceUpdate','FontSize',pars.fontSize,...
                                   'TooltipString',sprintf('MRS sequence selection'));

% vendor selection
fm.marss.sequOriginLab = text('Position',[0.540, 1.030],'String','Origin / Vendor','FontSize',pars.fontSize);
fm.marss.sequOrigin    = uicontrol('Style','Popup','String',SP2_CellArrayToStrList(marss.sequOriginCell,'|'),'Value',flag.marssSequOrigin,...
                                   'Position',[415 669 160 8],'Callback','SP2_MARSS_SequOriginUpdate','FontSize',pars.fontSize,...
                                   'TooltipString',sprintf('MR vendor selection'));

% simulation parameter source/definition
fm.marss.simParsDefLab   = text('Position',[-0.145, 0.978],'String','Parameter definition','FontSize',pars.fontSize);
fm.marss.simParsDef      = uicontrol('Style','Popup','String',SP2_CellArrayToStrList(marss.simParsDefCell,'|'),'Value',flag.marssSimParsDef,...
                                     'Position',[120 639 110 8],'Callback','SP2_MARSS_SimParsDefUpdate','FontSize',pars.fontSize,...
                                     'TooltipString',sprintf('Source of simulation parameter definition'));
fm.marss.simParsDefAdopt = uicontrol('Style','Pushbutton','String','Adopt',...
                                     'Position',[230 626 50 20],'Callback','SP2_MARSS_SimParsDefAdopt;',...
                                     'TooltipString',sprintf('Adopt spectral properties from selected parameter source'),'FontSize',pars.fontSize);

% result/output format
fm.marss.resultFormatLab = text('Position',[0.540, 0.978],'String','Result format','FontSize',pars.fontSize);
fm.marss.resultFormat = uicontrol('Style','Popup','String',SP2_CellArrayToStrList(marss.resultFormatCell,'|'),'Value',flag.marssResultFormat,...
                                  'Position',[415 639 160 8],'Callback','SP2_MARSS_ResultFormatUpdate','FontSize',pars.fontSize,...
                                  'TooltipString',sprintf('Output data format'),'Enable','off');
        
                           
%--- spin system library ---
fm.marss.spinSysLibLab   = text('Position',[-0.145, 0.926],'String','Spin system library','FontSize',pars.fontSize);
fm.marss.spinSysLibPath  = uicontrol('Style','Edit','Position', [120 600 365 18],'String',marss.spinSys.libPath,...
                                      'HorizontalAlignment','Left','Callback','SP2_MARSS_SpinSysLibPathUpdate;','FontSize',pars.fontSize);
fm.marss.spinSysLibSelect = uicontrol('Style','Pushbutton','String','Select',...
                                      'Position',[485 600 45 18],'Callback','SP2_MARSS_SpinSysLibSelect;',...
                                      'TooltipString',sprintf('Select spin system library'),'FontSize',pars.fontSize);
% fm.marss.spinSysLibManage = uicontrol('Style','Pushbutton','String','Manage','Enable','off',...
%                                       'Position',[485 600 45 18],'Callback','SP2_MARSS_SpinSysLibMain',...
%                                       'TooltipString',sprintf('Open window for spin system library handling'),'FontSize',pars.fontSize);
fm.marss.spinSysLibLoad   = uicontrol('Style','Pushbutton','String','Load',...
                                      'Position',[530 600 45 18],'Callback','SP2_MARSS_SpinSysLibLoad;',...
                                      'TooltipString',sprintf('Load spin system library from file'),'FontSize',pars.fontSize);

%--- spin system selection ---
fm.marss.spinSysBoxLab  = text('Position',[-0.065 0.84],'String','Spin Systems','FontSize',pars.fontSize,'FontWeight','bold');
fm.marss.spinSysBox     = uicontrol('Style','Listbox','Position',[10 320 150 220],'FontSize',pars.fontSize,...
                                    'Min',0,'Max',100,'String',marss.spinSys.nameCell,'Value',[],...
                                    'TooltipString',sprintf('Library of spin systems'));
fm.marss.spinSysAddSel  = uicontrol('Style','Pushbutton','String','Add Selected','FontSize',pars.fontSize,...
                                    'Position',[10 295 90 25],'Callback','SP2_MARSS_SpinSysAddSelected;',...
                                    'TooltipString',sprintf('Add selected spin system(s) from the library\nto the basis selection for simulation'));
fm.marss.spinSysAddAll  = uicontrol('Style','Pushbutton','String','Add All','FontSize',pars.fontSize,...
                                    'Position',[100 295 60 25],'Callback','SP2_MARSS_SpinSysAddAll;',...
                                    'TooltipString',sprintf('Add all spin systems from the library\nto the basis selection for simulation'));

%--- metabolite basis selection ---
fm.marss.basisBoxLab  = text('Position',[0.270 0.84],'String','Basis Selection','FontSize',pars.fontSize,'FontWeight','bold');
fm.marss.basisBox     = uicontrol('Style','Listbox','Position',[175 320 150 220],'FontSize',pars.fontSize,...
                                  'Min',0,'Max',100,'String',marss.basis.selectNames,'Value',[],...
                                  'TooltipString',sprintf('Selection of spin systems considered in basis set simulation'));
fm.marss.basisRmSel   = uicontrol('Style','Pushbutton','String','Remove Selected','FontSize',pars.fontSize,...
                                  'Position',[175 295 100 25],'Callback','SP2_MARSS_BasisRmSelected;',...
                                  'TooltipString',sprintf('Remove selected metabolite(s) from basis selection'));
fm.marss.basisRmAll   = uicontrol('Style','Pushbutton','String','Rm All','FontSize',pars.fontSize,...
                                  'Position',[275 295 50 25],'Callback','SP2_MARSS_BasisRmAll;',...
                                  'TooltipString',sprintf('Remova all metabolites from basis selection'));
                              
%--- basis set file handling ---
fm.marss.basisDirLab    = text('Position',[-0.145, 0.332],'String','Basis Dir','FontSize',pars.fontSize);
fm.marss.basisDirPath   = uicontrol('Style','Edit','Position', [70 260 280 18],'String',marss.basis.fileDir,...
                                    'HorizontalAlignment','Left','Callback','SP2_MARSS_BasisDirPathUpdate;','FontSize',pars.fontSize);
fm.marss.basisDirSelect = uicontrol('Style','Pushbutton','String','Select',...
                                    'Position',[350 260 45 18],'Callback','SP2_MARSS_BasisDirSelect;',...
                                    'TooltipString',sprintf('Select basis set directory'),'FontSize',pars.fontSize);
fm.marss.basisFileLab    = text('Position',[-0.145, 0.298],'String','Basis File','FontSize',pars.fontSize);
fm.marss.basisFileName   = uicontrol('Style','Edit','Position', [70 240 235 18],'String',marss.basis.fileName,...
                                     'HorizontalAlignment','Left','Callback','SP2_MARSS_BasisFileNameUpdate;','FontSize',pars.fontSize);
fm.marss.basisFileSelect = uicontrol('Style','Pushbutton','String','Select',...
                                     'Position',[305 240 45 18],'Callback','SP2_MARSS_BasisFileSelect;',...
                                     'TooltipString',sprintf('Select basis file'),'FontSize',pars.fontSize);
fm.marss.basisFileLoad   = uicontrol('Style','Pushbutton','String','Load',...
                                     'Position',[350 240 45 18],'Callback','SP2_MARSS_BasisFileLoad;',...
                                     'TooltipString',sprintf('Load basis from file'),'FontSize',pars.fontSize);

                                 
%--- simulation parameters ---
fm.marss.simParsLab   = text('Position',[0.750 0.84],'String','Simulation Details','FontSize',pars.fontSize,'FontWeight','bold');
fm.marss.b0Lab        = text('Position',[0.590, 0.7961],'String',sprintf('B_{0} Field'),'FontSize',pars.fontSize);
fm.marss.b0           = uicontrol('Style','Edit','Position', [400 524 50 18],'String',sprintf('%.3f',marss.b0),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_LarmorInTeslaUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Scanner B0 field strength [T]'),'FontSize',pars.fontSize);
fm.marss.sfLab        = text('Position',[0.845, 0.7961],'String','Larmor','FontSize',pars.fontSize);
fm.marss.sf           = uicontrol('Style','Edit','Position', [525 524 50 18],'String',sprintf('%.2f',marss.sf),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_LarmorInHertzUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Larmor frequency [MHz]'),'FontSize',pars.fontSize);
fm.marss.sw_hLab      = text('Position',[0.590, 0.7522],'String','BW [Hz]','FontSize',pars.fontSize);
fm.marss.sw_h         = uicontrol('Style','Edit','Position', [400 499 50 18],'String',sprintf('%.1f',marss.sw_h),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_BandwidthInHertzUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Spectral bandwidth [Hz]'),'FontSize',pars.fontSize);
fm.marss.swLab        = text('Position',[0.845, 0.7522],'String','BW [ppm]','FontSize',pars.fontSize);
fm.marss.sw           = uicontrol('Style','Edit','Position', [525 499 50 18],'String',sprintf('%.3f',marss.sw),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_BandwidthInPpmUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Spectral bandwidth [Hz]'),'FontSize',pars.fontSize);
fm.marss.nspecCLab    = text('Position',[0.590, 0.7083],'String','# Pts','FontSize',pars.fontSize);
fm.marss.nspecCBasic  = uicontrol('Style','Edit','Position', [400 474 50 18],'String',num2str(marss.nspecCBasic),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_SimParsUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Number of complex points of original simulation before processing'),'FontSize',pars.fontSize);                
fm.marss.ppmCalibLab  = text('Position',[0.845, 0.7083],'String','Calib','FontSize',pars.fontSize);
fm.marss.ppmCalib     = uicontrol('Style','Edit','Position', [525 474 50 18],'String',num2str(marss.ppmCalib),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_SimParsUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Synthesizer frequency calibration [ppm]\n(typically corresponding to water resonance, i.e. ~4.65 ppm)'),'FontSize',pars.fontSize); 
fm.marss.voxDimLab    = text('Position',[0.590, 0.6644],'String','Vox Dim','FontSize',pars.fontSize);
fm.marss.voxDim       = uicontrol('Style','Edit','Position', [400 449 50 18],'String',num2str(marss.voxDim),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_SimParsUpdate','Enable','off',...
                                  'TooltipString',sprintf('Simulation detail: Voxel dimension [mm] per spatial dimension\n(Note that the simulation extends over twice the voxel dimension)'),'FontSize',pars.fontSize);                
fm.marss.simDimLab    = text('Position',[0.845, 0.6644],'String','Sim Dim','FontSize',pars.fontSize);
fm.marss.simDim       = uicontrol('Style','Edit','Position', [525 449 50 18],'String',num2str(marss.simDim),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_SimParsUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Simulatiton dimension [pts] per spatial dimension'),'FontSize',pars.fontSize); 
fm.marss.lbLab        = text('Position',[0.590, 0.6205],'String','LB','FontSize',pars.fontSize);
fm.marss.lb           = uicontrol('Style','Edit','Position', [400 424 50 18],'String',num2str(marss.lb),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_SimParsUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Lorentzian line broadening [Hz]'),'FontSize',pars.fontSize);                
fm.marss.teLab        = text('Position',[0.845, 0.6205],'String','TE','FontSize',pars.fontSize);
fm.marss.te           = uicontrol('Style','Edit','Position', [525 424 50 18],'String',num2str(marss.te),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_SimParsUpdate',...
                                  'TooltipString',sprintf('Simulation detail: Echo time [ms]'),'FontSize',pars.fontSize); 
% fm.marss.te2Lab       = text('Position',[0.590, 0.5766],'String','TE','FontSize',pars.fontSize);                           
% fm.marss.te2          = uicontrol('Style','Edit','Position', [400 399 50 18],'String',num2str(marss.te2),...
%                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ParsUpdate',...
%                                   'TooltipString',sprintf('Simulation detail: Echo time 2 [ms]'),'FontSize',pars.fontSize);
% if flag.marssSequName==1            % STEAM
%     fm.marss.tmLab        = text('Position',[0.845, 0.5766],'String','TM','FontSize',pars.fontSize);                           
%     fm.marss.tm           = uicontrol('Style','Edit','Position', [525 399 50 18],'String',num2str(marss.tm),...
%                                       'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ParsUpdate',...
%                                       'TooltipString',sprintf('Simulation detail: Mixing time [ms]'),'FontSize',pars.fontSize); 
% end
fm.marss.saveIndiv    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.marssSaveIndiv,...
                                  'String','Save individual','Position',[0.585 0.50 .16 .03],'Callback','SP2_MARSS_SaveIndivMetabsFlagUpdate',...
                                  'TooltipString',sprintf('Save individual metabolite spectra as\nindividual files in addition to basis set'),'FontSize',pars.fontSize);
fm.marss.saveLog      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Log', ...
                                  'Position',[.78 .50 .08 .03],'Callback','SP2_MARSS_SaveLogFlagUpdate',...
                                  'TooltipString',sprintf('Save processing trace information in log text file'),'FontSize',pars.fontSize,'Enable','off');
fm.marss.saveJpeg     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Jpeg', ...
                                  'Position',[.885 .50 .08 .03],'Callback','SP2_MARSS_SaveJpegFlagUpdate',...
                                  'TooltipString',sprintf('Save figures also as image (jpeg) files'),'FontSize',pars.fontSize,'Enable','off');
                              
                              
%--- simulate basis set ---
fm.marss.doSimulation = uicontrol('Style','Pushbutton','String','Simulate',...
                                  'Position',[350 315 70 20],'Callback','SP2_MARSS_DoSimulation;',...
                                  'TooltipString',sprintf('Performs MRS simulation'),'FontSize',pars.fontSize);

%--- spectral processing and display ---
% apodization
fm.marss.procCutLab    = text('Position',[-0.13, 0.2184],'String','Cut','FontSize',pars.fontSize);
fm.marss.procCutFlag   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcCut,...
                                   'Position',[.09 .2726 .03 .03],'Callback','SP2_MARSS_ProcCutFlagUpdate',...
                                   'TooltipString',sprintf('Apodization of FID data vector [pts]'));
fm.marss.procCutDec3   = uicontrol('Style','Pushbutton','String','<<<','Position',[75 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcCutDec3','FontSize',pars.fontSize);
fm.marss.procCutDec2   = uicontrol('Style','Pushbutton','String','<<','Position',[97 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcCutDec2','FontSize',pars.fontSize);
fm.marss.procCutDec1   = uicontrol('Style','Pushbutton','String','<','Position',[119 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcCutDec1','FontSize',pars.fontSize);
fm.marss.procCutVal    = uicontrol('Style','Edit','Position', [141 195 55 18],'String',sprintf('%.0f',marss.procCut),...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcCutUpdate','FontSize',pars.fontSize);
fm.marss.procCutInc1   = uicontrol('Style','Pushbutton','String','>','Position',[196 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcCutInc1','FontSize',pars.fontSize);
fm.marss.procCutInc2   = uicontrol('Style','Pushbutton','String','>>','Position',[218 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcCutInc2','FontSize',pars.fontSize);
fm.marss.procCutInc3   = uicontrol('Style','Pushbutton','String','>>>','Position',[240 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcCutInc3','FontSize',pars.fontSize);
fm.marss.procCutReset  = uicontrol('Style','Pushbutton','String','R','Position',[265 195 22 18],'Callback','SP2_MARSS_ProcCutReset','FontSize',pars.fontSize);
            
% zero-filling
fm.marss.procZfLab     = text('Position',[-0.13, 0.1745],'String','ZF','FontSize',pars.fontSize);
fm.marss.procZfFlag    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcZf,...
                                   'Position',[.09 .2370 .03 .03],'Callback','SP2_MARSS_ProcZfFlagUpdate',...
                                   'TooltipString',sprintf('Time domain zero-filling [pts]'));
fm.marss.procZfDec3    = uicontrol('Style','Pushbutton','String','<<<','Position',[75 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcZfDec3','FontSize',pars.fontSize);
fm.marss.procZfDec2    = uicontrol('Style','Pushbutton','String','<<','Position',[97 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcZfDec2','FontSize',pars.fontSize);
fm.marss.procZfDec1    = uicontrol('Style','Pushbutton','String','<','Position',[119 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcZfDec1','FontSize',pars.fontSize);
fm.marss.procZfVal     = uicontrol('Style','Edit','Position', [141 170 55 18],'String',sprintf('%.0f',marss.procZf),...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcZfUpdate','FontSize',pars.fontSize);
fm.marss.procZfInc1    = uicontrol('Style','Pushbutton','String','>','Position',[196 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcZfInc1','FontSize',pars.fontSize);
fm.marss.procZfInc2    = uicontrol('Style','Pushbutton','String','>>','Position',[218 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcZfInc2','FontSize',pars.fontSize);
fm.marss.procZfInc3    = uicontrol('Style','Pushbutton','String','>>>','Position',[240 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcZfInc3','FontSize',pars.fontSize);
fm.marss.procZfReset   = uicontrol('Style','Pushbutton','String','R','Position',[265 170 22 18],'Callback','SP2_MARSS_ProcZfReset','FontSize',pars.fontSize);
                            
% exponential line broadening
fm.marss.procLbLab     = text('Position',[-0.13, 0.1306],'String','LB','FontSize',pars.fontSize);
fm.marss.procLbFlag    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcLb,...
                                   'Position',[.09 .2014 .03 .03],'Callback','SP2_MARSS_ProcLbFlagUpdate',...
                                   'TooltipString',sprintf('Exponential line broadening [Hz]\n(compare Gaussian broadening, GB)'));
fm.marss.procLbDec3    = uicontrol('Style','Pushbutton','String','<<<','Position',[75 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcLbDec3','FontSize',pars.fontSize);
fm.marss.procLbDec2    = uicontrol('Style','Pushbutton','String','<<','Position',[97 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcLbDec2','FontSize',pars.fontSize);
fm.marss.procLbDec1    = uicontrol('Style','Pushbutton','String','<','Position',[119 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcLbDec1','FontSize',pars.fontSize);
fm.marss.procLbVal     = uicontrol('Style','Edit','Position', [141 145 55 18],'String',sprintf('%.2f',marss.procLb),...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcLbUpdate','FontSize',pars.fontSize);
fm.marss.procLbInc1    = uicontrol('Style','Pushbutton','String','>','Position',[196 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcLbInc1','FontSize',pars.fontSize);
fm.marss.procLbInc2    = uicontrol('Style','Pushbutton','String','>>','Position',[218 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcLbInc2','FontSize',pars.fontSize);
fm.marss.procLbInc3    = uicontrol('Style','Pushbutton','String','>>>','Position',[240 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcLbInc3','FontSize',pars.fontSize);
fm.marss.procLbReset   = uicontrol('Style','Pushbutton','String','R','Position',[265 145 22 18],'Callback','SP2_MARSS_ProcLbReset','FontSize',pars.fontSize);

% Gaussian line broadening
fm.marss.procGbLab     = text('Position',[-0.13, 0.0867],'String','GB','FontSize',pars.fontSize);
fm.marss.procGbFlag    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcGb,...
                                   'Position',[.09 .1658 .03 .03],'Callback','SP2_MARSS_ProcGbFlagUpdate',...
                                   'TooltipString',sprintf('Gaussian line broadening [Hz^2]\n(compare exponential broadening, LB)'));
fm.marss.procGbDec3    = uicontrol('Style','Pushbutton','String','<<<','Position',[75 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcGbDec3','FontSize',pars.fontSize);
fm.marss.procGbDec2    = uicontrol('Style','Pushbutton','String','<<','Position',[97 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcGbDec2','FontSize',pars.fontSize);
fm.marss.procGbDec1    = uicontrol('Style','Pushbutton','String','<','Position',[119 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcGbDec1','FontSize',pars.fontSize);
fm.marss.procGbVal     = uicontrol('Style','Edit','Position', [141 120 55 18],'String',sprintf('%.2f',marss.procGb),...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcGbUpdate','FontSize',pars.fontSize);
fm.marss.procGbInc1    = uicontrol('Style','Pushbutton','String','>','Position',[196 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcGbInc1','FontSize',pars.fontSize);
fm.marss.procGbInc2    = uicontrol('Style','Pushbutton','String','>>','Position',[218 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcGbInc2','FontSize',pars.fontSize);
fm.marss.procGbInc3    = uicontrol('Style','Pushbutton','String','>>>','Position',[240 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcGbInc3','FontSize',pars.fontSize);
fm.marss.procGbReset   = uicontrol('Style','Pushbutton','String','R','Position',[265 120 22 18],'Callback','SP2_MARSS_ProcGbReset','FontSize',pars.fontSize);

% phase correction: zero order          
fm.marss.procPhc0Lab   = text('Position',[0.50, 0.2184],'String','PHC0','FontSize',pars.fontSize);
fm.marss.procPhc0Flag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcPhc0,...
                                   'Position',[.59 .2726 .03 .03],'Callback','SP2_MARSS_ProcPhc0FlagUpdate',...
                                   'TooltipString',sprintf('Zero order phase correction [deg]'));
fm.marss.procPhc0Dec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[376 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc0Dec3','FontSize',pars.fontSize);
fm.marss.procPhc0Dec2  = uicontrol('Style','Pushbutton','String','<<','Position',[398 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc0Dec2','FontSize',pars.fontSize);
fm.marss.procPhc0Dec1  = uicontrol('Style','Pushbutton','String','<','Position',[420 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc0Dec1','FontSize',pars.fontSize);
fm.marss.procPhc0Val   = uicontrol('Style','Edit','Position', [442 195 55 18],'String',sprintf('%.1f',marss.procPhc0),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcPhc0Update','FontSize',pars.fontSize);
fm.marss.procPhc0Inc1  = uicontrol('Style','Pushbutton','String','>','Position',[497 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc0Inc1','FontSize',pars.fontSize);
fm.marss.procPhc0Inc2  = uicontrol('Style','Pushbutton','String','>>','Position',[519 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc0Inc2','FontSize',pars.fontSize);
fm.marss.procPhc0Inc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[543 195 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc0Inc3','FontSize',pars.fontSize);
fm.marss.procPhc0Reset = uicontrol('Style','Pushbutton','String','R','Position',[568 195 22 18],'Callback','SP2_MARSS_ProcPhc0Reset','FontSize',pars.fontSize);

% phase correction: first order          
fm.marss.procPhc1Lab   = text('Position',[0.50, 0.1745],'String','PHC1','FontSize',pars.fontSize);
fm.marss.procPhc1Flag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcPhc1,...
                                   'Position',[.59 .2370 .03 .03],'Callback','SP2_MARSS_ProcPhc1FlagUpdate',...
                                   'TooltipString',sprintf('First order phase correction [deg]'));
fm.marss.procPhc1Dec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[376 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc1Dec3','FontSize',pars.fontSize);
fm.marss.procPhc1Dec2  = uicontrol('Style','Pushbutton','String','<<','Position',[398 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc1Dec2','FontSize',pars.fontSize);
fm.marss.procPhc1Dec1  = uicontrol('Style','Pushbutton','String','<','Position',[420 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc1Dec1','FontSize',pars.fontSize);
fm.marss.procPhc1Val   = uicontrol('Style','Edit','Position', [442 170 55 18],'String',sprintf('%.1f',marss.procPhc1),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcPhc1Update','FontSize',pars.fontSize);
fm.marss.procPhc1Inc1  = uicontrol('Style','Pushbutton','String','>','Position',[497 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc1Inc1','FontSize',pars.fontSize);
fm.marss.procPhc1Inc2  = uicontrol('Style','Pushbutton','String','>>','Position',[519 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc1Inc2','FontSize',pars.fontSize);
fm.marss.procPhc1Inc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[543 170 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcPhc1Inc3','FontSize',pars.fontSize);
fm.marss.procPhc1Reset = uicontrol('Style','Pushbutton','String','R','Position',[568 170 22 18],'Callback','SP2_MARSS_ProcPhc1Reset','FontSize',pars.fontSize);

% amplitude scaling
fm.marss.procScaleLab   = text('Position',[0.50, 0.1306],'String','Scale','FontSize',pars.fontSize);
fm.marss.procScaleFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                    'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcScale,...
                                    'Position',[.59 .2014 .03 .03],'Callback','SP2_MARSS_ProcScaleFlagUpdate',...
                                    'TooltipString',sprintf('Amplitude scaling [1]'));
fm.marss.procScaleDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[376 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcScaleDec3','FontSize',pars.fontSize);
fm.marss.procScaleDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[398 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcScaleDec2','FontSize',pars.fontSize);
fm.marss.procScaleDec1  = uicontrol('Style','Pushbutton','String','<','Position',[420 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcScaleDec1','FontSize',pars.fontSize);
fm.marss.procScaleVal   = uicontrol('Style','Edit','Position', [442 145 55 18],'String',sprintf('%.3f',marss.procScale),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcScaleUpdate','FontSize',pars.fontSize);
fm.marss.procScaleInc1  = uicontrol('Style','Pushbutton','String','>','Position',[497 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcScaleInc1','FontSize',pars.fontSize);
fm.marss.procScaleInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[519 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcScaleInc2','FontSize',pars.fontSize);
fm.marss.procScaleInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[543 145 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcScaleInc3','FontSize',pars.fontSize);
fm.marss.procScaleReset = uicontrol('Style','Pushbutton','String','R','Position',[568 145 22 18],'Callback','SP2_MARSS_ProcScaleReset','FontSize',pars.fontSize);

% frequency shift          
fm.marss.procShiftLab   = text('Position',[0.50, 0.0867],'String','Shift','FontSize',pars.fontSize);
fm.marss.procShiftFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                    'FontSize',pars.fontSize,'Units','Normalized','Value',flag.marssProcShift,...
                                    'Position',[.59 .1658 .03 .03],'Callback','SP2_MARSS_ProcShiftFlagUpdate',...
                                    'TooltipString',sprintf('Spectral shift [Hz]'));
fm.marss.procShiftDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[376 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcShiftDec3','FontSize',pars.fontSize);
fm.marss.procShiftDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[398 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcShiftDec2','FontSize',pars.fontSize);
fm.marss.procShiftDec1  = uicontrol('Style','Pushbutton','String','<','Position',[420 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcShiftDec1','FontSize',pars.fontSize);
fm.marss.procShiftVal   = uicontrol('Style','Edit','Position', [442 120 55 18],'String',sprintf('%.3f',marss.procShift),'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ProcShiftUpdate','FontSize',pars.fontSize);
fm.marss.procShiftInc1  = uicontrol('Style','Pushbutton','String','>','Position',[497 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcShiftInc1','FontSize',pars.fontSize);
fm.marss.procShiftInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[519 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcShiftInc2','FontSize',pars.fontSize);
fm.marss.procShiftInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[543 120 22 18],'FontWeight','bold','Callback','SP2_MARSS_ProcShiftInc3','FontSize',pars.fontSize);
fm.marss.procShiftReset = uicontrol('Style','Pushbutton','String','R','Position',[568 120 22 18],'Callback','SP2_MARSS_ProcShiftReset','FontSize',pars.fontSize);

                             
%--- result display ---
fm.marss.amplShowLab    = text('Position',[-0.13, 0.030],'String','Amplitude','FontSize',pars.fontSize);
fm.marss.amplShowAuto   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',~flag.marssAmplShow,...
                                  'String','Auto','Position',[.14 .12 .2 .03],'Callback','SP2_MARSS_AmplShowAutoUpdate',...
                                  'TooltipString',sprintf('Automatic determination of amplitude range'),'FontSize',pars.fontSize);
fm.marss.amplShowDirect = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.marssAmplShow,...
                                  'String','Direct','Position',[.24 .12 .03 .03],'Callback','SP2_MARSS_AmplShowDirectUpdate',...
                                  'TooltipString',sprintf('Direct assignment of amplitude range'),'FontSize',pars.fontSize);
fm.marss.amplShowMin    = uicontrol('Style','Edit','Position', [165 88 50 18],'String',num2str(marss.amplShowMin),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_AmplShowMinUpdate',...
                                  'TooltipString','Lower amplitude limit','FontSize',pars.fontSize);
fm.marss.amplShowMax    = uicontrol('Style','Edit','Position', [215 88 50 18],'String',num2str(marss.amplShowMax),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_AmplShowMaxUpdate',...
                                  'TooltipString','Upper amplitude limit','FontSize',pars.fontSize);
fm.marss.ppmShowLab     = text('Position',[0.50, 0.030],'String','Frequ.','FontSize',pars.fontSize);
fm.marss.ppmShowFull    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Full', ...
                                  'Value',flag.marssPpmShow,'Position',[.590 .12 .12 .03],'Callback','SP2_MARSS_PpmShowFullUpdate','FontSize',pars.fontSize);
fm.marss.ppmShowDirect  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized', ...
                                  'Value',~flag.marssPpmShow,'Position',[.669 .12 .03 .03],'Callback','SP2_MARSS_PpmShowDirectUpdate','FontSize',pars.fontSize);
fm.marss.ppmShowMinDecr = uicontrol('Style','Pushbutton','String','-','Position',[422 88 18 18],'FontWeight','bold','Callback','SP2_MARSS_PpmShowMinDecr','FontSize',pars.fontSize);
fm.marss.ppmShowMin     = uicontrol('Style','Edit','Position', [440 88 40 18],'String',sprintf('%.2f',marss.ppmShowMin),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_PpmShowMinUpdate',...
                                  'TooltipString','Lower amplitude limit','FontSize',pars.fontSize);
fm.marss.ppmShowMinIncr = uicontrol('Style','Pushbutton','String','+','Position',[480 88 18 18],'FontWeight','bold','Callback','SP2_MARSS_PpmShowMinIncr','FontSize',pars.fontSize);
fm.marss.ppmShowMaxDecr = uicontrol('Style','Pushbutton','String','-','Position',[503 88 18 18],'FontWeight','bold','Callback','SP2_MARSS_PpmShowMaxDecr','FontSize',pars.fontSize);
fm.marss.ppmShowMax     = uicontrol('Style','Edit','Position', [521 88 40 18],'String',sprintf('%.2f',marss.ppmShowMax),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_PpmShowMaxUpdate',...
                                  'TooltipString','Upper amplitude limit','FontSize',pars.fontSize);
fm.marss.ppmShowMaxIncr = uicontrol('Style','Pushbutton','String','+','Position',[561 88 18 18],'FontWeight','bold','Callback','SP2_MARSS_PpmShowMaxIncr','FontSize',pars.fontSize);

                             
%--- simulation result result ---                             
fm.marss.showSuperpos = uicontrol('Style','Pushbutton','String','Superpos','Position',[15 45 80 20],...
                                'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_MARSS_ProcAndPlotSpecSuperpos(1);',...
                                'TooltipString',sprintf('Show superposition of MARSS traces'));
fm.marss.showSum      = uicontrol('Style','Pushbutton','String','Sum','Position',[95 45 50 20],...
                                'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_MARSS_ProcAndPlotSpecSum(1);',...
                                'TooltipString',sprintf('Shows sum of MARSS metabolite results'));
fm.marss.showSel      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized', ...
                                'Value',flag.marssShowSelAll,'Position',[.27 .06 .03 .03],'Callback','SP2_MARSS_ShowSelUpdate',...
                                'TooltipString',sprintf('1: Superimpose / sum assigned metabolite selection only\n0: Superimpose / sum all available metabolites'),'FontSize',pars.fontSize);
fm.marss.showSelStr   = uicontrol('Style','Edit','Position', [183 45 150 18],'String',marss.showSelStr,'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_ShowSelStrUpdate',...
                                'TooltipString',sprintf('Metabolite selection for superposition/summation display\n(e.g. 1:3 7 9)'),'FontSize',pars.fontSize);            
fm.marss.showSingle   = uicontrol('Style','Pushbutton','String','Single','Position',[15 15 80 20],...
                                'FontName','Helvetica','FontSize',pars.fontSize,'Callback','SP2_MARSS_ProcAndPlotSpecSingle(1);',...
                                'TooltipString',sprintf('Shows single metabolite of simulation result'));
fm.marss.singleDecr   = uicontrol('Style','Pushbutton','String','-','Position',[95 15 22 20],...
                                'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_MARSS_SpecSingleCurrDecr',...
                                'TooltipString',sprintf('Lower number of metabolite to be displayed'));
fm.marss.singleCurr   = uicontrol('Style','Edit','Position', [117 15 36 20],'BackGroundColor',pars.bgColor,'Callback','SP2_MARSS_SpecSingleCurrUpdate','FontSize',pars.fontSize);
fm.marss.singleIncr   = uicontrol('Style','Pushbutton','String','+','Position',[153 15 22 20],...
                                'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_MARSS_SpecSingleCurrIncr',...
                                'TooltipString',sprintf('Raise number of metabolite to be displayed'));


%--- clear all MARSS figures ---                              
fm.marss.closeMarssFigs = uicontrol('Style','Pushbutton','String','X Figs','Position',[275 15 56 18],'Callback','SP2_MARSS_CloseMarssFigures;',...
                                    'TooltipString',sprintf('Close all MARSS spectral figures'),'FontSize',pars.fontSize);
                                                         
%--- color mode ---         
fm.marss.cmapUni     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Blue', ...
                               'Value',flag.marssColorMap==0,'Position',[.63 .06 .2 .03],'Callback','SP2_MARSS_ColormapUniUpdate','FontSize',pars.fontSize);
fm.marss.cmapJet     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Jet', ...
                               'Value',flag.marssColorMap==1,'Position',[.72 .06 .2 .03],'Callback','SP2_MARSS_ColormapJetUpdate','FontSize',pars.fontSize);
fm.marss.cmapHsv     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Hsv', ...
                               'Value',flag.marssColorMap==2,'Position',[.805 .06 .2 .03],'Callback','SP2_MARSS_ColormapHsvUpdate','FontSize',pars.fontSize);
fm.marss.cmapHot     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Hot', ...
                               'Value',flag.marssColorMap==3,'Position',[.89 .06 .2 .03],'Callback','SP2_MARSS_ColormapHotUpdate','FontSize',pars.fontSize);
                            
%--- freeze/keep figure ---
fm.marss.legend       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Legend', ...
                                'Value',flag.marssLegend,'Position',[.63 .02 .2 .03],'Callback','SP2_MARSS_LegendUpdate',...
                                'TooltipString',sprintf('Show overview data legend in superposition display'),'FontSize',pars.fontSize);
fm.marss.keepFigure   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Keep', ...
                                'Value',flag.marssKeepFig,'Position',[.75 .02 .10 .03],'Callback','SP2_MARSS_KeepFigureUpdate',...
                                'TooltipString',sprintf('1: figures are kept, ie. parameter changes are plotted to new figures\n0: Parameter changes are updated in the same figure'),'FontSize',pars.fontSize);
fm.marss.verbose   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.verbose,...
                               'String','Verbose','Position',[0.85 0.02 .17 .03],'Callback','SP2_MARSS_VerboseFlagUpdate',...
                               'TooltipString',sprintf('Detailed display of simulation and result information'),'FontSize',pars.fontSize);
                             
                             
%--- window update ---
SP2_MARSS_MARSSWinUpdate
