%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
    function SP2_Data_DataMain
%% 
%%  Main window for the selection of data path(s)/file(s)
%%
%%  02-2008, Christoph Juchem
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global fm fmfig pars data flag


if ~SP2_ClearWindow
    fprintf('\n--- WARNING ---\nClearing of window figure handles failed.\n\n')
    return
end
flag.fmWin = 1;
pars.figPos = get(fmfig,'Position');
set(fmfig,'Name',' INSPECTOR: Data Handling','Position',...
    [pars.figPos(1) pars.figPos(2) pars.mainDims(3) pars.mainDims(4)])


%**********************************************************************************
%***    F M A P     S E T U P    /    P R O T O C O L     S E L E C T I O N     ***
%**********************************************************************************
fm.data.protLab    = text('Position',[-0.14, 1.05],'String','Protocol','FontSize',pars.fontSize);
fm.data.protPath   = uicontrol('Style','Edit','Position', [70 670 500 18],'String',data.protPath, ...
                               'HorizontalAlignment','Left','Callback','SP2_Data_ProtocolPathUpdate;','FontSize',pars.fontSize);
fm.data.protSelect = uicontrol('Style','Pushbutton','String','Select','Position',[70 650 50 18],'Callback','SP2_Data_ProtocolSelect',...
                               'TooltipString',sprintf('Select INSPECTOR protocol file'),'FontSize',pars.fontSize);
fm.data.protLoad   = uicontrol('Style','Pushbutton','String','Load','Position',[120 650 50 18],'Callback','SP2_Data_ProtocolLoad;',...
                               'TooltipString',sprintf('Load INSPECTOR protocol from file'),'FontSize',pars.fontSize);
fm.data.protWrite  = uicontrol('Style','Pushbutton','String','Save','Position',[170 650 50 18],'Callback','SP2_Data_ProtocolSave;',...
                               'TooltipString',sprintf('Save INSPECTOR protocol to file'),'FontSize',pars.fontSize);
% fm.data.protExport = uicontrol('Style','Pushbutton','String','Export','Position',[220 650 50 18],'Callback','SP2_Data_ProtocolExport',...
%                                'TooltipString',sprintf('Export INSPECTOR protocol to text file'),'FontSize',pars.fontSize);
fm.data.resetDef   = uicontrol('Style','Pushbutton','String','Reset Default','Position',[295 650 80 18],'Callback','SP2_Data_ResetDefProtocol',...
                               'TooltipString',sprintf('Reset INSPECTOR to software defaults\n(unlikely to be used)'),'FontSize',pars.fontSize);
fm.data.resetSpec  = uicontrol('Style','Pushbutton','String','Reset INSPECTOR','Position',[400 650 105 18],'Callback','SP2_Data_ResetSpec',...
                               'TooltipString',sprintf('Reset INSPECTOR software:\n1) All settings are kept\n2) All data is removed from memory'),'FontSize',pars.fontSize);
fm.data.verbose    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.verbose,...
                               'String','Verbose','Position',[0.87 0.92 .11 .03],'Callback','SP2_Data_VerboseFlagUpdate',...
                               'TooltipString',sprintf('(Overall) detailed display of data and processing details'),'FontSize',pars.fontSize);

%********************************************************************
%   D A T A     S E L E C T I O N
%********************************************************************
fm.data.selectLab  = text('Position',[-0.15, 0.955],'String','Data Selection','FontWeight','bold','FontSize',pars.fontSize);

% metabolite data set selection
SP2_Data_ExpTypePars2Display
fm.data.expType = uicontrol('Style','Popup','String',SP2_CellArrayToStrList(data.expTypeDisplCell,'|'),'Value',data.expTypeDisplay,...
                            'Position',[180 623 170 12],'Callback','SP2_Data_ExpTypeUpdate','TooltipString',sprintf('Experiment type selection'),'FontSize',pars.fontSize);

% fm.data.single      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataExpType==1,...
%                                 'String','Regular','Position',[0.2 0.87 .10 .03],'Callback','SP2_Data_ExpTypeSingleUpdate');
% fm.data.stability   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataExpType==4,...
%                                 'String','Stability','Position',[0.31 0.87 .10 .03],'Callback','SP2_Data_ExpTypeStabilityUpdate');
% fm.data.double      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataExpType==2,...
%                                 'String','Sat-Rec','Position',[0.425 0.87 .10 .03],'Callback','SP2_Data_ExpTypeDoubleUpdate');
% fm.data.t1t2        = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataExpType==5,...
%                                 'String','T1/T2','Position',[0.54 0.87 .10 .03],'Callback','SP2_Data_ExpTypeT1T2Update');
% fm.data.mrsi        = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataExpType==6,...
%                                 'String','MRSI','Position',[0.640 0.87 .10 .03],'Callback','SP2_Data_ExpTypeMrsiUpdate');
% fm.data.editing     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataExpType==3,...
%                                 'String','Editing','Position',[0.740 0.87 .10 .03],'Callback','SP2_Data_ExpTypeEditingUpdate');
% fm.data.editOne     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataEditNo==1,...
%                                 'String','1','Position',[0.835 0.87 .05 .03],'Callback','SP2_Data_EditDataOneUpdate',...
%                                 'TooltipString',sprintf('JDE data selection:\nFirst and last condition'));
% fm.data.editTwo     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataEditNo==2,...
%                                 'String','2','Position',[0.885 0.87 .05 .03],'Callback','SP2_Data_EditDataTwoUpdate',...
%                                 'TooltipString',sprintf('JDE data selection:\nSecond and last condition'));
% fm.data.convdta     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataConvdta,...
%                                 'String','Convdta','Position',[0.87 0.87 .10 .03],'Callback','SP2_Data_ConvdtaFlagUpdate');
fm.data.spec1Lab          = text('Position',[-0.14, 0.915],'String','Data 1','FontSize',pars.fontSize);
fm.data.spec1FidDecr      = uicontrol('Style','Pushbutton','String','-','Position',[450 612 25 18],'FontWeight','bold','Callback','SP2_Data_Dat1FidFileDecr',...
                                      'TooltipString',sprintf('Decrease scan number of data set (FID) 1'),'FontSize',pars.fontSize);
fm.data.spec1FidIncr      = uicontrol('Style','Pushbutton','String','+','Position',[475 612 25 18],'FontWeight','bold','Callback','SP2_Data_Dat1FidFileIncr',...
                                      'TooltipString',sprintf('Increase scan number of data set (FID) 1'),'FontSize',pars.fontSize);
fm.data.spec1FidSelect    = uicontrol('Style','Pushbutton','String','Select','Position',[500 612 50 18],'Callback','SP2_Data_Dat1FidFileSelect',...
                                      'TooltipString',sprintf('Select data set (FID) 1'),'FontSize',pars.fontSize);
fm.data.spec1FidLoad      = uicontrol('Style','Pushbutton','String','Load','Position',[550 612 45 18],'Callback','SP2_Data_Dat1FidFileLoadButton;',...
                                      'TooltipString',sprintf('Load data set (FID) 1'),'FontSize',pars.fontSize);
fm.data.spec1FidFile      = uicontrol('Style','Edit','Position', [65 592 530 18],'String',data.spec1.fidFile, ...
                                      'HorizontalAlignment','Left','Callback','SP2_Data_Dat1FidFileUpdate;',...
                                      'TooltipString',sprintf('Path of data set (FID) 1'),'FontSize',pars.fontSize);
fm.data.spec1SeriesLab    = text('Position',[-0.14, 0.880],'String','Series','FontSize',pars.fontSize);
fm.data.spec1SeriesStr    = uicontrol('Style','Edit','Position', [65 572 385  18],'String',data.spec1.seriesStr, ...
                                      'HorizontalAlignment','Left','Callback','SP2_Data_Dat1SeriesUpdate;',...
                                      'TooltipString',sprintf('String (in Matlab format) defining the a series of data set 1 FIDs'),'FontSize',pars.fontSize);
% fm.data.spec1SeriesSelect = uicontrol('Style','Pushbutton','String','Select','Position',[450 572 50 18],'Callback','SP2_Data_Dat1SeriesSelect','Enable','off');
fm.data.spec1SeriesLoad    = uicontrol('Style','Pushbutton','String','Load','Position',[450 572 50 18],'Callback','SP2_Data_Dat1SeriesLoad;',...
                                       'TooltipString',sprintf('Load (FID) data series 1'),'FontSize',pars.fontSize);
fm.data.spec1QualityAssess = uicontrol('Style','Pushbutton','String','QA','Position',[500 572 50 18],'Callback','SP2_Data_QualityDetailsMain;',...
                                       'TooltipString',sprintf('Start quality assessment (QA) tool for FID series 1'),'FontSize',pars.fontSize);
fm.data.spec1SeriesSum     = uicontrol('Style','Pushbutton','String','Mean','Position',[550 572 45 18],'Callback','SP2_Data_Dat1SeriesSum;',...
                                       'TooltipString',sprintf('Average data series 1'),'FontSize',pars.fontSize);

%--- reference data set selection ---
fm.data.spec2Lab       = text('Position',[-0.14, 0.810],'String','Data 2','FontSize',pars.fontSize);
fm.data.spec2FidDecr   = uicontrol('Style','Pushbutton','String','-','Position',[450 552 25 18],'FontWeight','bold','Callback','SP2_Data_Dat2FidFileDecr',...
                                   'TooltipString',sprintf('Decrease scan number of data set (FID) 2'),'FontSize',pars.fontSize);
fm.data.spec2FidIncr   = uicontrol('Style','Pushbutton','String','+','Position',[475 552 25 18],'FontWeight','bold','Callback','SP2_Data_Dat2FidFileIncr',...
                                   'TooltipString',sprintf('Increase scan number of data set (FID) 2'),'FontSize',pars.fontSize);         
fm.data.spec2FidSelect = uicontrol('Style','Pushbutton','String','Select','Position',[500 552 50 18],'Callback','SP2_Data_Dat2FidFileSelect','FontSize',pars.fontSize);
fm.data.spec2FidLoad   = uicontrol('Style','Pushbutton','String','Load','Position',[550 552 45 18],'Callback','SP2_Data_Dat2FidFileLoadButton;','FontSize',pars.fontSize);
fm.data.spec2FidFile   = uicontrol('Style','Edit','Position', [65 532 530 18],'String',data.spec2.fidFile, ...
                                   'HorizontalAlignment','Left','Callback','SP2_Data_Dat2FidFileUpdate;',...
                                   'TooltipString',sprintf('Path of data set (FID) 2'),'FontSize',pars.fontSize);

%--- phase / frequency correction ---
fm.data.alignFrequency    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataAlignFrequ,...
                                      'String','Frequ.','Position',[0.11 0.782 .11 .03],'Callback','SP2_Data_AlignFrequencyUpdate','FontSize',pars.fontSize);
fm.data.alignPhase        = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataAlignPhase,...
                                      'String','Phase','Position',[0.205 0.782 .11 .03],'Callback','SP2_Data_AlignPhaseUpdate','FontSize',pars.fontSize);
fm.data.alignAmplitude    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataAlignAmpl,...
                                      'String','Ampl.','Position',[0.30 0.782 .11 .03],'Callback','SP2_Data_AlignAmplitudeUpdate','FontSize',pars.fontSize);
fm.data.alignDetails      = uicontrol('Style','Pushbutton','String','Details','Position',[240 552 50 18],'Callback','SP2_Data_AlignDetailsMain',...
                                      'TooltipString',sprintf('Start setup page to define criteria for\n phase and frequency alignment.\n'),'FontSize',pars.fontSize);
fm.data.spec1SeriesAlign  = uicontrol('Style','Pushbutton','String','Align','Position',[290 552 50 18],'Callback','SP2_Data_Dat1SeriesAlign;','FontSize',pars.fontSize);
fm.data.alignVerbose      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataAlignVerbose,...
                                      'String','Align QA','Position',[0.58 0.782 .11 .03],'Callback','SP2_Data_AlignVerboseUpdate',...
                                      'TooltipString',sprintf('Detailed display of intermediate results of the alignment routines.\n'),'FontSize',pars.fontSize);

%--- reassign data paths to protocol directory ---                                  
fm.data.assignProtDir     = uicontrol('Style','Pushbutton','String','Same','Position',[540 512 55 18],'Callback','SP2_Data_AssignProtDir2Data;',...
                                      'TooltipString',sprintf('Reassign data paths assuming data are located in the ''Same'' directory with the protocol'),'FontSize',pars.fontSize);  
fm.data.assignProtRel     = uicontrol('Style','Pushbutton','String','Relative','Position',[540 492 55 18],'Callback','SP2_Data_AssignProtRel2Data;',...
                                      'TooltipString',sprintf('Reassign paths of both data sets to maintain directory structure ''Relative'' to protocol file'),'FontSize',pars.fontSize);
fm.data.convAnaPC         = uicontrol('Style','Pushbutton','String','Ana Prot','Position',[540 472 55 18],'Callback','SP2_Data_CreateAnalysisProtocol;',...
                                      'TooltipString',sprintf('Automated conversion of SPX protocol and data structure to current data location\ne.g. Linux (scanner) to PC or Mac (for analysis)\nNote that the selected protocol is expected to be located in the overall data/study directory'),'FontSize',pars.fontSize);
fm.data.closeAlignFigs    = uicontrol('Style','Pushbutton','String','X Align','Position',[540 452 55 18],'Callback','SP2_Data_CloseAlignFigures;',...
                                      'TooltipString',sprintf('Close all ''Align QA'' figures'),'FontSize',pars.fontSize);
% fm.data.dat2ExtractWater  = uicontrol('Style','Pushbutton','String','Water','Position',[540 432 55 18],'Callback','SP2_Data_Dat2ExtractWater;',...
%                                       'TooltipString',sprintf('Extract water reference\n(Last water scan, ECC by first water scan)'),'FontSize',pars.fontSize);

%--- T2 water formating ---
% fm.data.t2Special         = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.t2Special,...
%                                       'String','T2 Special','Position',[0.5 0.35 .20 .03],'Callback','SP2_Data_T2SpecialUpdate','FontSize',pars.fontSize);

                                                                    
%**************************************************************************
% data manipulation
%**************************************************************************
fm.data.maniLab     = text('Position',[-0.15, 0.32],'String','Data Handling and Visualization','FontWeight','bold','FontSize',pars.fontSize);


%--- acquisition modes ---
fm.data.dsLab       = text('Position',[-0.13, 0.270],'String','DS','FontSize',pars.fontSize);
fm.data.ds          = uicontrol('Style','Edit','Position', [70 223 45 18],'String',sprintf('%.0f',data.ds),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_DummyScansUpdate',...
                                'TooltipString',sprintf('Number of dummy scans (as part of the data)'),'FontSize',pars.fontSize);
fm.data.nPhCycleLab = text('Position',[0.145, 0.270],'String','nPC','FontSize',pars.fontSize);
fm.data.nPhCycle    = uicontrol('Style','Edit','Position', [190 223 45 18],'String',sprintf('%.0f',data.nPhCycle),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_NPhaseCycleUpdate',...
                                'TooltipString',sprintf('Number of steps of the employed phase cycling scheme'),'FontSize',pars.fontSize);
                            

% spectrum visualization: ppm calibration
fm.data.ppmCalibLab = text('Position',[-0.13, 0.225],'String','Calib.','FontSize',pars.fontSize);
fm.data.ppmCalib    = uicontrol('Style','Edit','Position', [70 197 45 18],'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmCalibUpdate',...
                                'TooltipString',sprintf('Calibration synthesizer (water) frequency [ppm]'),'FontSize',pars.fontSize);
fm.data.ppmAssignToPeak = uicontrol('Style','Pushbutton','String','Assign','Position',[140 197 50 18],...
                                    'Callback','SP2_Data_PpmAssignToPeak','TooltipString',sprintf('Assigns ppm value (to the right) to the peak\nthat is selected in spectrum 1'),'FontSize',pars.fontSize);
fm.data.ppmAssign   = uicontrol('Style','Edit','Position', [190 197 45 18],'String',num2str(data.ppmAssign),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmAssignUpdate',...
                                'TooltipString',sprintf('Calibration frequency [ppm] to be\nassigned to selected (peak) position'),'FontSize',pars.fontSize);

%--- FID apodization (for display purposes only) ---
fm.data.fidCutLab = text('Position',[0.40, 0.225],'String','FID pts','FontSize',pars.fontSize);
fm.data.fidCut    = uicontrol('Style','Edit','Position', [315 197 45 18],'BackGroundColor',pars.bgColor,'Callback','SP2_Data_FidCutUpdate',...
                              'TooltipString',sprintf('FID apodization (for display purposes only)'),'FontSize',pars.fontSize);
                            
%--- spectral zero filling (for display purposes only) ---
fm.data.fidZfLab  = text('Position',[0.67, 0.225],'String','ZF','FontSize',pars.fontSize);
fm.data.fidZf     = uicontrol('Style','Edit','Position', [415 197 45 18],'String',sprintf('%.0f',data.fidZf),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_FidZfUpdate',...
                              'TooltipString',sprintf('Spectral zero-filling (for display purposes only)'),'FontSize',pars.fontSize);
                            
%--- minimum TI for saturation-recovery experiments ---
fm.data.satRecMinTILab = text('Position',[0.873, 0.225],'String','min TI','FontSize',pars.fontSize);
fm.data.satRecMinTI    = uicontrol('Style','Edit','Position', [530 197 45 18],'String',sprintf('%.3f',data.satRec.minTI),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_SatRecMinTiUpdate',...
                                   'TooltipString',sprintf('Minimum saturation recovery time [sec] spectrum\nto be applied for frequency/phase alignment'),'FontSize',pars.fontSize);

                               
%--- phase correction ---
fm.data.phaseLab    = text('Position',[-0.13, 0.180],'String','Phase Corr.','FontSize',pars.fontSize);
fm.data.phCorrKlose = uicontrol('Style','RadioButton','String','Klose','BackGroundColor',pars.bgColor, ...
                                'Units','Normalized','Value',flag.dataPhaseCorr==1,'Position',[0.16 .240 .10 .03],'Callback','SP2_Data_PhaseCorrKloseUpdate',...
                                'TooltipString',sprintf('Klose-type phase correction of individual MRS experiment'),'FontSize',pars.fontSize);
fm.data.phCorrFirst = uicontrol('Style','RadioButton','String','1st Point','BackGroundColor',pars.bgColor, ...
                                'Units','Normalized','Value',flag.dataPhaseCorr==2,'Position',[0.27 .240 .14 .03],'Callback','SP2_Data_PhaseCorrFirstUpdate',...
                                'TooltipString',sprintf('Phase correction of individual MRS experiment\nbased on 1st point of reference signal'),'FontSize',pars.fontSize);
% fm.data.kloseComb   = uicontrol('Style','RadioButton','String','Combined','BackGroundColor',pars.bgColor, ...
%                                 'Units','Normalized','Value',flag.dataKloseMode==1,'Position',[0.40 .240 .20 .03],'Callback','SP2_Data_PhaseCorrKloseCombinedUpdate',...
%                                 'TooltipString',sprintf('Phase information from all phase-cycling steps combined\nis applied for Klose phase correction'),'FontSize',pars.fontSize);
fm.data.kloseSep    = uicontrol('Style','RadioButton','String','Individual','BackGroundColor',pars.bgColor, ...
                                'Units','Normalized','Value',flag.dataKloseMode==2,'Position',[0.50 .240 .14 .03],'Callback','SP2_Data_PhaseCorrKloseSeparateUpdate',...
                                'TooltipString',sprintf('Phase information of individual phase-cycling-specific\nsteps is applied for Klose phase correction'),'FontSize',pars.fontSize);
fm.data.kloseSelect = uicontrol('Style','RadioButton','String','Selected','BackGroundColor',pars.bgColor, ...
                                'Units','Normalized','Value',flag.dataKloseMode==3,'Position',[0.62 .240 .14 .03],'Callback','SP2_Data_PhaseCorrKloseSelectedUpdate',...
                                'TooltipString',sprintf('Phase information of selected phase-cycling step\nis applied for Klose correction'),'FontSize',pars.fontSize);
fm.data.phaseCorrNr = uicontrol('Style','Edit','Position', [443 171 35 18],'String',sprintf('%.0f',data.phaseCorrNr),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PhaseCorrNrUpdate',...
                                'TooltipString',sprintf('Number of water reference\n(in an arrayed experiment)\napplied for Klose correction'),'FontSize',pars.fontSize);
fm.data.doPhaseCorr = uicontrol('Style','Pushbutton','String','Apply','Position',[530 171 50 18],'Callback','SP2_Data_DoPhaseCorr;',...
                                'TooltipString',sprintf('Apply phase correction to individual MRS experiment'),'FontSize',pars.fontSize);

%--- receiver handling ---
fm.data.rcvrLab = text('Position',[-0.13, 0.135],'String','Receivers','FontSize',pars.fontSize);
% fm.data.rcvr1   = uicontrol('Style','RadioButton','String','1','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(1),'Position',[0.16 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 1 in data summation'),'FontSize',pars.fontSize);
% fm.data.rcvr2   = uicontrol('Style','RadioButton','String','2','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(2),'Position',[0.21 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 2 in data summation'),'FontSize',pars.fontSize);
% fm.data.rcvr3   = uicontrol('Style','RadioButton','String','3','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(3),'Position',[0.26 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 3 in data summation'),'FontSize',pars.fontSize);
% fm.data.rcvr4   = uicontrol('Style','RadioButton','String','4','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(4),'Position',[0.31 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 4 in data summation'),'FontSize',pars.fontSize);
% fm.data.rcvr5   = uicontrol('Style','RadioButton','String','5','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(5),'Position',[0.36 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 5 in data summation'),'FontSize',pars.fontSize);
% fm.data.rcvr6   = uicontrol('Style','RadioButton','String','6','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(6),'Position',[0.41 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 6 in data summation'),'FontSize',pars.fontSize);
% fm.data.rcvr7   = uicontrol('Style','RadioButton','String','7','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(7),'Position',[0.46 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 7 in data summation'),'FontSize',pars.fontSize);
% fm.data.rcvr8   = uicontrol('Style','RadioButton','String','8','BackGroundColor',pars.bgColor, ...
%                             'Units','Normalized','Value',data.rcvr(8),'Position',[0.51 .203 .08 .03],'Callback','SP2_Data_RcvrVecUpdate',...
%                             'TooltipString',sprintf('In-/exclusion of Rx channel 8 in data summation'),'FontSize',pars.fontSize);

fm.data.rcvrAll        = uicontrol('Style','RadioButton','String','All','BackGroundColor',pars.bgColor, ...
                                   'Units','Normalized','Value',flag.dataRcvrAllSelect,'Position',[0.16 .2025 .07 .03],'Callback','SP2_Data_RcvrAllUpdate',...
                                   'TooltipString',sprintf('Display of / summation over all available receivers'),'FontSize',pars.fontSize);
fm.data.rcvrSelect     = uicontrol('Style','RadioButton','String','Select','BackGroundColor',pars.bgColor, ...
                                   'Units','Normalized','Value',~flag.dataRcvrAllSelect,'Position',[0.24 .2025 .11 .03],'Callback','SP2_Data_RcvrSelectUpdate','FontSize',pars.fontSize);
fm.data.rcvrSelStr     = uicontrol('Style','Edit','Position', [200 143 215 18],'String',data.rcvrSelectStr,'BackGroundColor',pars.bgColor,'Callback','SP2_Data_RcvrSelectStrUpdate',...
                                   'TooltipString',sprintf('Repetitions (per individual scan) to be summed together'),'FontSize',pars.fontSize);
fm.data.rcvrWeight     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.dataRcvrWeight,...
                                   'String','Weighted','Position',[0.70 0.2025 .13 .03],'Callback','SP2_Data_RcvrWeightUpdate',...
                                   'TooltipString',sprintf('Sensitivity-weighting in summation/combination of receive channels'),'FontSize',pars.fontSize);
                        
%--- data selection and summation ---
fm.data.sumLab    = text('Position',[-0.13, 0.090],'String','FIDs (NR)','FontSize',pars.fontSize);
fm.data.sumAll    = uicontrol('Style','RadioButton','String','All','BackGroundColor',pars.bgColor, ...
                              'Units','Normalized','Value',flag.dataAllSelect,'Position',[0.16 .167 .07 .03],'Callback','SP2_Data_FIDsAllUpdate',...
                               'TooltipString',sprintf('Summation of all available repetitions'),'FontSize',pars.fontSize);
fm.data.sumSelect = uicontrol('Style','RadioButton','String','Select','BackGroundColor',pars.bgColor, ...
                              'Units','Normalized','Value',~flag.dataAllSelect,'Position',[0.24 .167 .11 .03],'Callback','SP2_Data_FIDsSelectUpdate','FontSize',pars.fontSize);
fm.data.sumSelStr = uicontrol('Style','Edit','Position', [200 118 285 18],'String',data.selectStr,'BackGroundColor',pars.bgColor,'Callback','SP2_Data_FIDsSelectStrUpdate',...
                               'TooltipString',sprintf('Repetitions (per individual scan) to be summed together'),'FontSize',pars.fontSize);

%--- spectrum summation ---
fm.data.doSum     = uicontrol('Style','Pushbutton','String','Mean','Position',[530 118 50 18],'Callback','SP2_Data_DoSumRcvrs;',...
                              'TooltipString',sprintf('Summation/combination of Rx channels\nfor selected (single) MRS experiment'),'FontSize',pars.fontSize);
                          
%--- batch processing (tmp) ---
% fm.data.doBatchProc = uicontrol('Style','Pushbutton','String','Proc','Position',[530 98 50 18],'Callback','SP2_Data_DoProcTmp;',...
%                                 'TooltipString',sprintf('Temporary processing option'));
%                         
%**************************************************************************
% data visualization
%**************************************************************************
%--- FID 1 visualization ---
fm.data.plotAnaSingle   = uicontrol('Style','Pushbutton','String','Single','Position',[15 75 55 18],'Callback','SP2_Data_PlotAnaSingle;','FontSize',pars.fontSize);
fm.data.plotAnaSuper    = uicontrol('Style','Pushbutton','String','Super','Position',[15 55 55 18],'Callback','SP2_Data_PlotAnaSuperposition;','FontSize',pars.fontSize);
fm.data.plotAnaArray    = uicontrol('Style','Pushbutton','String','Array','Position',[15 35 55 18],'Callback','SP2_Data_PlotAnaArray;','FontSize',pars.fontSize);
% fm.data.plotAnaSum      = uicontrol('Style','Pushbutton','String','Average','Position',[143 80 47 18],'Callback','SP2_Data_PlotAnaAverage;');
% fm.data.plotAnaSNR      = uicontrol('Style','Pushbutton','String','SNR','Position',[10 60 45 18],'Callback','SP2_Data_PlotAnaSNR;');
% fm.data.plotAnaFwhm     = uicontrol('Style','Pushbutton','String','FWHM','Position',[55 60 45 18],'Callback','SP2_Data_PlotAnaFWHM;');
% fm.data.plotAnaIntegral = uicontrol('Style','Pushbutton','String','Integr','Position',[100 60 43 18],'Callback','SP2_Data_PlotAnaIntegral;');
fm.data.keepFigure      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Keep', ...
                                    'Value',flag.dataKeepFig,'Position',[.03 .01 .10 .03],'Callback','SP2_Data_KeepFigureUpdate',...
                                    'TooltipString',sprintf('Keep existing figures (i.e. do not update)\nand create new ones with additional data display'),'FontSize',pars.fontSize);

%--- FWHM / integral area definition ---
% fm.data.ppmTargetLab = text('Position',[-0.13, -0.068],'String','Target');
% fm.data.ppmTargetMin = uicontrol('Style','Edit','Position', [62 30 40 18],'String',sprintf('%.2f',data.ppmTargetMin),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmTargetWinUpdate');
% fm.data.ppmTargetMax = uicontrol('Style','Edit','Position', [102 30 40 18],'String',sprintf('%.2f',data.ppmTargetMax),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmTargetWinUpdate');
% fm.data.ppmNoiseLab  = text('Position',[-0.13, -0.102],'String','Noise');
% fm.data.ppmNoiseMin  = uicontrol('Style','Edit','Position', [62 10 40 18],'String',sprintf('%.2f',data.ppmNoiseMin),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmNoiseWinUpdate');
% fm.data.ppmNoiseMax  = uicontrol('Style','Edit','Position', [102 10 40 18],'String',sprintf('%.2f',data.ppmNoiseMax),'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmNoiseWinUpdate');

%--- scrolling functionality ---
fm.data.plotAnaFid1  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','FID 1',...
                                 'Value',flag.dataAna==1,'Position',[.165 .11 .13 .03],'Callback','SP2_Data_PlotAnaFid1Update',...
                                 'TooltipString',sprintf('Visualization of FID of data set 1 (metabolites)'),'FontSize',pars.fontSize);
fm.data.plotAnaSpec1 = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Spec 1',...
                                 'Value',flag.dataAna==2,'Position',[.255 .11 .13 .03],'Callback','SP2_Data_PlotAnaSpec1Update',...
                                 'TooltipString',sprintf('Visualization of spectrum of data set 1 (metabolites)'),'FontSize',pars.fontSize);
fm.data.plotAnaFid2  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','FID 2',...
                                 'Value',flag.dataAna==3,'Position',[.165 .08 .13 .03],'Callback','SP2_Data_PlotAnaFid2Update',...
                                 'TooltipString',sprintf('Visualization of FID of data set 2 (water)'),'FontSize',pars.fontSize);
fm.data.plotAnaSpec2 = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Spec 2',...
                                 'Value',flag.dataAna==4,'Position',[.255 .08 .13 .03],'Callback','SP2_Data_PlotAnaSpec2Update',...
                                 'TooltipString',sprintf('Visualization of spectrum of data set 2 (water)'),'FontSize',pars.fontSize);
fm.data.scrRcvrLab  = text('Position',[0.043, -0.071],'String','Rcvr','FontSize',pars.fontSize);
fm.data.scrRcvrDecr = uicontrol('Style','Pushbutton','String','-','Position',[135 30 22 18],'FontWeight','bold',...
                                'Callback','SP2_Data_ScrollReceiverDecr',...
                                'TooltipString',sprintf('Decrease selected receiver for single Rx/NR display'),'FontSize',pars.fontSize);
fm.data.scrRcvrNum  = uicontrol('Style','Edit','Position', [157 30 35 18],'String',num2str(data.scrollRcvr), ...
                                'HorizontalAlignment','Center','Callback','SP2_Data_ScrollReceiverUpdate',...
                                'TooltipString',sprintf('Selected receiver for single Rx/NR display'),'FontSize',pars.fontSize);          
fm.data.scrRcvrIncr = uicontrol('Style','Pushbutton','String','+','Position',[192 30 22 18],'FontWeight','bold',...
                                'Callback','SP2_Data_ScrollReceiverIncr',...
                                'TooltipString',sprintf('Increase selected receiver for single Rx/NR display'),'FontSize',pars.fontSize);
fm.data.scrRepLab   = text('Position',[0.050, -0.104],'String','NR','FontSize',pars.fontSize);
fm.data.scrRepDecr  = uicontrol('Style','Pushbutton','String','-','Position',[135 10 22 18],'FontWeight','bold',...
                                'Callback','SP2_Data_ScrollRepetitionDecr',...
                                'TooltipString',sprintf('Decrease selected repetition for single Rx/NR display'),'FontSize',pars.fontSize);
fm.data.scrRepNum   = uicontrol('Style','Edit','Position', [157 10 35 18],'String',num2str(data.scrollRep), ...
                                'HorizontalAlignment','Center','Callback','SP2_Data_ScrollRepetitionUpdate',...
                                'TooltipString',sprintf('Selected repetition for single Rx/NR display'),'FontSize',pars.fontSize);          
fm.data.scrRepIncr  = uicontrol('Style','Pushbutton','String','+','Position',[192 10 22 18],'FontWeight','bold',...
                                'Callback','SP2_Data_ScrollRepetitionIncr',...
                                'TooltipString',sprintf('Increase selected repetition for single Rx/NR display'),'FontSize',pars.fontSize);

%--- amplitude range ---
fm.data.amplAuto   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Auto', ...
                               'Value',flag.dataAmpl==0,'Position',[.405 .11 .10 .03],'Callback','SP2_Data_AmplAutoUpdate',...
                               'TooltipString',sprintf('Automatic assignment of amplitude range for visualization'),'FontSize',pars.fontSize);
fm.data.amplDirect = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Direct', ...
                               'Value',flag.dataAmpl==1,'Position',[.405 .08 .10 .03],'Callback','SP2_Data_AmplDirectUpdate',...
                               'TooltipString',sprintf('Direct/explicit assignment of amplitude range for visualization'),'FontSize',pars.fontSize);
fm.data.amplMinLab = text('Position',[0.35, -0.068],'String','Min','FontSize',pars.fontSize);
fm.data.amplMin    = uicontrol('Style','Edit','Position', [275 30 55 18],'String',sprintf('%.0f',data.amplMin),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_Data_AmplWinUpdate',...
                               'TooltipString',sprintf('Minimum amplitude display limit [a.u.]'),'FontSize',pars.fontSize);
fm.data.amplMaxLab = text('Position',[0.35, -0.102],'String','Max','FontSize',pars.fontSize);
fm.data.amplMax    = uicontrol('Style','Edit','Position', [275 10 55 18],'String',sprintf('%.0f',data.amplMax),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_Data_AmplWinUpdate',...
                               'TooltipString',sprintf('Maximum amplitude display limit [a.u.]'),'FontSize',pars.fontSize);

%--- ppm range ---
fm.data.ppmShowFull   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Full', ...
                                  'Value',flag.dataPpmShow==0,'Position',[.60 .11 .10 .03],'Callback','SP2_Data_PpmShowFullUpdate',...
                                  'TooltipString',sprintf('Visualization of full frequency range\n(= experiment bandwidth)'),'FontSize',pars.fontSize);
fm.data.ppmShowDirect = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Direct', ...
                                  'Value',flag.dataPpmShow==1,'Position',[.60 .08 .10 .03],'Callback','SP2_Data_PpmShowDirectUpdate',...
                                  'TooltipString',sprintf('Visualization of selected frequency range in [ppm]'),'FontSize',pars.fontSize);
fm.data.ppmShowMinLab = text('Position',[0.605, -0.068],'String','Min','FontSize',pars.fontSize);
fm.data.ppmShowMin    = uicontrol('Style','Edit','Position', [393 30 40 18],'String',sprintf('%.2f',data.ppmShowMin),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmShowWinUpdate',...
                                  'TooltipString',sprintf('Minimum frequency display limit [ppm]'),'FontSize',pars.fontSize);
fm.data.ppmShowMaxLab = text('Position',[0.605, -0.102],'String','Max','FontSize',pars.fontSize);
fm.data.ppmShowMax    = uicontrol('Style','Edit','Position', [393 10 40 18],'String',sprintf('%.2f',data.ppmShowMax),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_Data_PpmShowWinUpdate',...
                                  'TooltipString',sprintf('Maximum frequency display limit [ppm]'),'FontSize',pars.fontSize);

%--- spectrum visualization: data format ---
fm.data.formatReal   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Real', ...
                                 'Value',flag.dataFormat==1,'Position',[.765 .095 .11 .03],'Callback','SP2_Data_FormatRealUpdate',...
                                 'TooltipString',sprintf('Data format: Real part'),'FontSize',pars.fontSize);
fm.data.formatImag   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Imag', ...
                                 'Value',flag.dataFormat==2,'Position',[.765 .065 .11 .03],'Callback','SP2_Data_FormatImagUpdate',...
                                 'TooltipString',sprintf('Data format: Imaginary part'),'FontSize',pars.fontSize);
fm.data.formatMagn   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Magn', ...
                                 'Value',flag.dataFormat==3,'Position',[.765 .035 .11 .03],'Callback','SP2_Data_FormatMagnUpdate',...
                                 'TooltipString',sprintf('Data format: Magnitude'),'FontSize',pars.fontSize);
fm.data.formatPhase  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Phase', ...
                                 'Value',flag.dataFormat==4,'Position',[.765 .005 .11 .03],'Callback','SP2_Data_FormatPhaseUpdate',...
                                 'TooltipString',sprintf('Data format: Phase'),'FontSize',pars.fontSize);
fm.data.phaseLinCorr = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized', ...
                                 'Value',flag.dataPhaseLinCorr,'Position',[.86 .005 .03 .03],'Callback','SP2_Data_PhaseLinearCorrectionUpdate',...
                                 'TooltipString',sprintf('Linear detrending of FID phases\n(i.e. frequency correction)'),'FontSize',pars.fontSize);

%--- color map ---
fm.data.cMapJet   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.colormap==0,...
                              'String','jet','Position',[.910 .095 .08 .03],'Callback','SP2_Data_ColormapJetUpdate',...
                              'TooltipString',sprintf('Color mode: JET'),'FontSize',pars.fontSize);
fm.data.cMapHsv   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.colormap==1,...
                              'String','hsv','Position',[.910 .065 .08 .03],'Callback','SP2_Data_ColormapHsvUpdate',...
                              'TooltipString',sprintf('Color mode: HSV'),'FontSize',pars.fontSize);
fm.data.cMapHot   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.colormap==2,...
                              'String','hot','Position',[.910 .035 .08 .03],'Callback','SP2_Data_ColormapHotUpdate',...
                              'TooltipString',sprintf('Color mode: HOT'),'FontSize',pars.fontSize);

%--- window update ---                           
SP2_Data_DataWinUpdate
