%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 
    function SP2_MM_AlignDetailsMain
%%
%%  Create window for setting up the automated phase/frequency alignment
%%  of arrayed acquisitions.
%%
%%  09-2012, Christoph Juchem
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global loggingfile pars flag mm fm

FCTNAME = 'SP2_MM_AlignDetailsMain';


%--- consistency check ---
if isfield(fm.mm,'alignDet')              % ROI init open
    if ishandle(fm.mm.align.fig)
        figure(fm.mm.align.fig)
    else
        fm.mm.align.fig = figure;
        set(fm.mm.align.fig,'NumberTitle','off','Position',[30 80 600 600],'Color',pars.bgColor,...
                            'MenuBar','none','Resize','off','Name',' Setup for Automated Spectrum Alignment');
        axes('Visible','off');
    end
else
    fm.mm.align.fig = figure('IntegerHandle','off');
    set(fm.mm.align.fig,'NumberTitle','off','Position',[30 80 600 600],'Color',pars.bgColor,...
                        'MenuBar','none','Resize','off','Name',' Setup for Automated Spectrum Alignment');
    axes('Visible','off');
end

%--- PHASE ALIGNMENT ---
fm.mm.align.phLab       = text('Position',[-0.11, 1.02],'String','Phase Alignment','FontWeight','bold');
fm.mm.align.phase       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAlignPhase,...
                                    'String','Phase','Position',[0.24 0.942 .03 .03],'Callback','SP2_MM_AlignPhaseUpdate');
fm.mm.align.phModeInteg = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAlignPhMode==0,...
                                      'String','Integral','Position',[.04 .90 .25 .03],'Callback','SP2_MM_AlignPhModeIntegralUpdate',...
                                      'TooltipString',sprintf('Optimization mode:\nMaximization of spectral integral'));
fm.mm.align.phModeCongr = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAlignPhMode==1,...
                                      'String','Congruency','Position',[.17 .90 .25 .03],'Callback','SP2_MM_AlignPhModeCongruencyUpdate',...
                                      'TooltipString',sprintf('Optimization mode:\nMaximization of spectrum similarity with reference'));
fm.mm.align.phPpmStrLab = text('Position',[-0.11, 0.88],'String','Frequency window(s)','FontSize',pars.fontSize);
fm.mm.align.phPpmStr    = uicontrol('Style','Edit','Position', [160 517 120 18],'String',mm.phAlignPpmStr,'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignPhasePpmStrUpdate',...
                                      'TooltipString',sprintf('Frequency range(s) in ppm for phase alignment\n(e.g. 1.2:1.8 7:8.3)'));            
fm.mm.align.phExpLbLab  = text('Position',[-0.11, 0.82],'String','Line Broadening','FontSize',pars.fontSize);
fm.mm.align.phExpLb     = uicontrol('Style','Edit','Position', [160 496 45 18],'String',num2str(mm.phAlignExpLb),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignPhaseParsUpdate',...
                                      'TooltipString','Exponential line broadening [Hz]');
fm.mm.align.phFftCutLab = text('Position',[-0.11, 0.76],'String','Apodization','FontSize',pars.fontSize);
fm.mm.align.phFftCut    = uicontrol('Style','Edit','Position', [160 475 45 18],'String',num2str(mm.phAlignFftCut),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignPhaseParsUpdate',...
                                      'TooltipString','Time-domain apodization [pts]');
fm.mm.align.phFftZfLab  = text('Position',[-0.11, 0.70],'String','Zero-Filling','FontSize',pars.fontSize);
fm.mm.align.phFftZf     = uicontrol('Style','Edit','Position', [160 454 45 18],'String',num2str(mm.phAlignFftZf),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignPhaseParsUpdate',...
                                      'TooltipString','Time-domain zero filling [pts]');
fm.mm.align.phPhStepLab  = text('Position',[-0.11, 0.64],'String','Phase Step','FontSize',pars.fontSize);
fm.mm.align.phPhStep     = uicontrol('Style','Edit','Position', [160 433 45 18],'String',num2str(mm.phAlignPhStep),...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignPhaseParsUpdate',...
                                     'TooltipString','Phase step size, i.e. resolution [deg]');
fm.mm.align.phRefFidLab  = text('Position',[-0.11, 0.58],'String','Reference FID','FontSize',pars.fontSize);
fm.mm.align.phRefFid     = uicontrol('Style','Edit','Position', [160 412 45 18],'String',num2str(mm.phAlignRefFid),...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignPhaseParsUpdate',...
                                     'TooltipString','Reference FID for alignment [1]','Enable','off');                                     
fm.mm.align.phIterFidLab = text('Position',[-0.11, 0.52],'String','Iterations','FontSize',pars.fontSize);
fm.mm.align.phIter       = uicontrol('Style','Edit','Position', [160 391 45 18],'String',num2str(mm.phAlignIter),...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignPhaseParsUpdate',...
                                     'TooltipString','Iterations of frequency alignment [1]\nNote that for >1 the summation result is used as reference');
                                     
%--- FREQUENCY ALIGNMENT ---
fm.mm.align.frLab         = text('Position',[-0.11, 0.15],'String','Frequency Alignment','FontWeight','bold');
fm.mm.align.frequency     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAlignFrequ,...
                                      'String','Frequ.','Position',[0.29 0.448 .03 .03],'Callback','SP2_MM_AlignFrequencyUpdate');
fm.mm.align.frPpmStrLab   = text('Position',[-0.11, -0.05],'String','Frequency window(s)','FontSize',pars.fontSize);
fm.mm.align.frPpmStr      = uicontrol('Style','Edit','Position', [160 202 120 18],'String',mm.frAlignPpmStr,'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequPpmStrUpdate',...
                                      'TooltipString',sprintf('Frequency range(s) in ppm for frequency alignment\n(e.g. 1.2:1.8 7:8.3)'));            
fm.mm.align.frExpLbLab    = text('Position',[-0.11, -0.11],'String','Line Broadening','FontSize',pars.fontSize);
fm.mm.align.frExpLb       = uicontrol('Style','Edit','Position', [160 181 45 18],'String',num2str(mm.frAlignExpLb),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequParsUpdate',...
                                      'TooltipString','Exponential line broadening [Hz]');
fm.mm.align.frFftCutLab   = text('Position',[-0.11, -0.17],'String','Apodization','FontSize',pars.fontSize);
fm.mm.align.frFftCut      = uicontrol('Style','Edit','Position', [160 160 45 18],'String',num2str(mm.frAlignFftCut),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequParsUpdate',...
                                      'TooltipString','Time-domain apodization [pts]');
fm.mm.align.frFftZfLab    = text('Position',[-0.11, -0.23],'String','Zero-Filling','FontSize',pars.fontSize);
fm.mm.align.frFftZf       = uicontrol('Style','Edit','Position', [160 139 45 18],'String',num2str(mm.frAlignFftZf),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequParsUpdate',...
                                      'TooltipString','Time-domain zero filling [pts]');
fm.mm.align.frFrequRgLab  = text('Position',[-0.11, -0.29],'String','Variation Range','FontSize',pars.fontSize);
fm.mm.align.frFrequRg     = uicontrol('Style','Edit','Position', [160 118 45 18],'String',num2str(mm.frAlignFrequRg),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequParsUpdate',...
                                      'TooltipString','Minimum/maximum shift range [Hz]');
fm.mm.align.frFrequResLab = text('Position',[-0.11, -0.35],'String','Resolution','FontSize',pars.fontSize);
fm.mm.align.frFrequRes    = uicontrol('Style','Edit','Position', [160 97 45 18],'String',num2str(mm.frAlignFrequRes),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequParsUpdate',...
                                      'TooltipString','Frequency resolution [Hz]');
fm.mm.align.frRefFidLab   = text('Position',[-0.11, -0.41],'String','Reference FID','FontSize',pars.fontSize);
fm.mm.align.frRefFid      = uicontrol('Style','Edit','Position', [160 76 45 18],'String',num2str(mm.frAlignRefFid(1)),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequParsUpdate',...
                                      'TooltipString','Reference FID for alignment [1]','Enable','off');
fm.mm.align.frIterFidLab  = text('Position',[-0.11, -0.47],'String','Iterations','FontSize',pars.fontSize);
fm.mm.align.frIter        = uicontrol('Style','Edit','Position', [160 55 45 18],'String',num2str(mm.frAlignIter),...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignFrequParsUpdate',...
                                      'TooltipString',sprintf('Iterations of frequency alignment [1]\nNote that for >1 the summation result is used as reference'));
                                    
%--- AMPLITUDE ALIGNMENT ---
fm.mm.align.amLab       = text('Position',[0.6, 1.02],'String','Amplitude Alignment','FontWeight','bold');
fm.mm.align.amplitude   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAlignAmpl,...
                                    'String','Ampl.','Position',[0.8 0.942 .03 .03],'Callback','SP2_MM_AlignAmplitudeUpdate');
fm.mm.align.amPpmStrLab = text('Position',[0.6, 0.880],'String','Frequency window(s)','FontSize',pars.fontSize);
fm.mm.align.amPpmStr    = uicontrol('Style','Edit','Position', [465 517 120 18],'String',mm.amAlignPpmStr,'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplPpmStrUpdate',...
                                    'TooltipString',sprintf('Frequency range(s) in ppm for amplitude alignment\n(e.g. 1.2:1.8 7:8.3)'));            
fm.mm.align.amExpLbLab  = text('Position',[0.6, 0.818],'String','Line Broadening','FontSize',pars.fontSize);
fm.mm.align.amExpLb     = uicontrol('Style','Edit','Position', [465 496 45 18],'String',num2str(mm.amAlignExpLb),...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplParsUpdate',...
                                    'TooltipString','Exponential line broadening [Hz]');
fm.mm.align.amFftCutLab = text('Position',[0.6, 0.756],'String','Apodization','FontSize',pars.fontSize);
fm.mm.align.amFftCut    = uicontrol('Style','Edit','Position', [465 475 45 18],'String',num2str(mm.amAlignFftCut),...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplParsUpdate',...
                                    'TooltipString','Time-domain apodization [pts]');
fm.mm.align.amFftZfLab  = text('Position',[0.6, 0.694],'String','Resolution','FontSize',pars.fontSize);
fm.mm.align.amFftZf     = uicontrol('Style','Edit','Position', [465 454 45 18],'String',num2str(mm.amAlignFftZf),...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplParsUpdate',...
                                    'TooltipString','Time-domain zero filling [pts]');
fm.mm.align.amRef1Lab   = text('Position',[0.6, 0.632],'String','Reference FID','FontSize',pars.fontSize);
fm.mm.align.amRef1Str   = uicontrol('Style','Edit','Position', [465 433 60 18],'String',mm.amAlignRef1Str,...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplRef1StrUpdate',...
                                    'TooltipString','Reference FIDs for amplitude alignment [1]\n(e.g. 3:10)','Enable','off');                                     
fm.mm.align.amPolyLab   = text('Position',[0.6, 0.57],'String','Polynomial Order','FontSize',pars.fontSize);
fm.mm.align.amPolyOrder = uicontrol('Style','Edit','Position', [465 412 45 18],'String',num2str(mm.amAlignPolyOrder),...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplParsUpdate',...
                                    'TooltipString','Order of polynomical-based amplitude correction');
fm.mm.align.amExtraLab  = text('Position',[0.6, 0.508],'String','Extra Window','FontSize',pars.fontSize);
fm.mm.align.amExtraWin  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.amAlignExtraWin,...
                                    'Position',[.73 .65 .25 .03],'Callback','SP2_MM_AlignAmplExtraWinUpdate',...
                                    'TooltipString',sprintf('Optimization mode:\nMaximization of spectral integral'));
fm.mm.align.amExtraPpmMin = uicontrol('Style','Edit','Position', [465 391 45 18],'String',num2str(mm.amAlignExtraPpm(1)),...
                                        'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplParsUpdate',...
                                        'TooltipString','Minimum limit [ppm] of extra display window');
fm.mm.align.amExtraPpmMax = uicontrol('Style','Edit','Position', [510 391 45 18],'String',num2str(mm.amAlignExtraPpm(2)),...
                                        'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AlignAmplParsUpdate',...
                                        'TooltipString','Maximum limit [ppm] of extra display window');
                                    
                                    
%--- exit alignment tool ---
fm.mm.align.exit = uicontrol('Style','Pushbutton','String','Exit','FontWeight','bold','Position',[480 30 70 20],...
                               'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_MM_AlignDetailsExit');


                                             
%--- window update ---
SP2_MM_AlignDetailsWinUpdate

