function SP2_FctList4StandAlone
%#function SP2_BatchProc_Jodi
%#function SP2_BatchProc_MARKET
%#function SP2_BatchProc_Neonatal
%#function SP2_BatchTable2Xls_Neonatal
%#function SP2_Batch_MARKET_Processing
%#function SP2_Batch_SerialLcm4Kelley_STEAM_metab
%#function SP2_Batch_SerialLcm4Tecfidera_JDE_GSH
%#function SP2_Batch_SerialLcm4Tecfidera_JDE_metab
%#function SP2_Batch_SerialLcm4Tecfidera_STEAM_metab
%#function SP2_Batch_SerialLcm4Tecfidera_STEAM_waterNR1
%#function SP2_Data_AlignAmplitudeUpdate
%#function SP2_Data_AlignAmplExtraWinUpdate
%#function SP2_Data_AlignAmplParsUpdate
%#function SP2_Data_AlignAmplPpmStrUpdate
%#function SP2_Data_AlignAmplRef1StrUpdate
%#function SP2_Data_AlignAmplRef2StrUpdate
%#function SP2_Data_AlignDetailsExit
%#function SP2_Data_AlignDetailsMain
%#function SP2_Data_AlignDetailsWinUpdate
%#function SP2_Data_AlignFrequParsUpdate
%#function SP2_Data_AlignFrequPpm1StrUpdate
%#function SP2_Data_AlignFrequPpm2StrUpdate
%#function SP2_Data_AlignPhModeCongruencyUpdate
%#function SP2_Data_AlignPhModeIntegralUpdate
%#function SP2_Data_AlignPhaseParsUpdate
%#function SP2_Data_AlignPhasePpm1StrUpdate
%#function SP2_Data_AlignPhasePpm2StrUpdate
%#function SP2_Data_AlignPhaseSpecRgOneUpdate
%#function SP2_Data_AlignPhaseSpecRgTwoUpdate
%#function SP2_Data_AlignFrequencyUpdate
%#function SP2_Data_AlignPhaseUpdate
%#function SP2_Data_AlignRefFidUpdate
%#function SP2_Data_AlignVerboseUpdate
%#function SP2_Data_AmplAutoUpdate
%#function SP2_Data_AmplDirectUpdate
%#function SP2_Data_AmplScaleOptFct
%#function SP2_Data_AmplWinUpdate
%#function SP2_Data_AssignProtDir2Data
%#function SP2_Data_AssignProtRel2Data
%#function SP2_Data_AutoAmplDetRegular
%#function SP2_Data_AutoFrequDet
%#function SP2_Data_AutoFrequDetIndiv
%#function SP2_Data_AutoFrequDetPrep
%#function SP2_Data_AutoPhaseDet
%#function SP2_Data_AvanceConvList
%#function SP2_Data_CheckScanIndexFormat
%#function SP2_Data_CloseAlignFigures
%#function SP2_Data_ColormapHotUpdate
%#function SP2_Data_ColormapHsvUpdate
%#function SP2_Data_ColormapJetUpdate
%#function SP2_Data_Convdta
%#function SP2_Data_ConvdtaFlagUpdate
%#function SP2_Data_CreateAnalysisProtocol
%#function SP2_Data_Dat1FidFileDecr
%#function SP2_Data_Dat1FidFileIncr
%#function SP2_Data_Dat1FidFileLoad
%#function SP2_Data_Dat1FidFileLoadButton
%#function SP2_Data_Dat1FidFileSelect
%#function SP2_Data_Dat1FidFileUpdate
%#function SP2_Data_Dat1SeriesAlign
%#function SP2_Data_Dat1SeriesAlignJde
%#function SP2_Data_Dat1SeriesAlignJdeArray
%#function SP2_Data_Dat1SeriesAlignRegular
%#function SP2_Data_Dat1SeriesAlignSatRec
%#function SP2_Data_Dat1SeriesAnalysis
%#function SP2_Data_Dat1SeriesLoad
%#function SP2_Data_Dat1SeriesLoad_beforeSiemensImaSeries_05Dec2021
%#function SP2_Data_Dat1SeriesOverview
%#function SP2_Data_Dat1SeriesStatistics
%#function SP2_Data_Dat1SeriesSum
%#function SP2_Data_Dat1SeriesUpdate
%#function SP2_Data_Dat2ExtractWater
%#function SP2_Data_Dat2FidFileDecr
%#function SP2_Data_Dat2FidFileIncr
%#function SP2_Data_Dat2FidFileLoad
%#function SP2_Data_Dat2FidFileLoadButton
%#function SP2_Data_Dat2FidFileSelect
%#function SP2_Data_Dat2FidFileUpdate
%#function SP2_Data_DataMain
%#function SP2_Data_DataWinUpdate
%#function SP2_Data_DicomImaParsConversion
%#function SP2_Data_DicomImaReadFid
%#function SP2_Data_DicomImaReadHeader
%#function SP2_Data_DicomParsConversion
%#function SP2_Data_DicomReadFid
%#function SP2_Data_DicomReadHeader
%#function SP2_Data_DoFrequCorr
%#function SP2_Data_DoPhaseCorr
%#function SP2_Data_DoProcTmp
%#function SP2_Data_DoSumRcvrs
%#function SP2_Data_DoSumRcvrsJDE
%#function SP2_Data_DoSumRcvrsMRSI
%#function SP2_Data_DoSumRcvrsSatRec
%#function SP2_Data_DoSumRcvrsSingle
%#function SP2_Data_DoSumRcvrsStability
%#function SP2_Data_DoSumRcvrsT1T2
%#function SP2_Data_DummyScansUpdate
%#function SP2_Data_EditDataOneUpdate
%#function SP2_Data_EditDataTwoUpdate
%#function SP2_Data_ExpTypeDisplay2Pars
%#function SP2_Data_ExpTypeDoubleUpdate
%#function SP2_Data_ExpTypeEditingUpdate
%#function SP2_Data_ExpTypeMrsiUpdate
%#function SP2_Data_ExpTypePars2Display
%#function SP2_Data_ExpTypeSingleUpdate
%#function SP2_Data_ExpTypeStabilityUpdate
%#function SP2_Data_ExpTypeT1T2Update
%#function SP2_Data_ExpTypeUpdate
%#function SP2_Data_ExtractPpmRange
%#function SP2_Data_FIDsAllUpdate
%#function SP2_Data_FIDsSelectStrUpdate
%#function SP2_Data_FIDsSelectUpdate
%#function SP2_Data_FidCutUpdate
%#function SP2_Data_FidZfUpdate
%#function SP2_Data_FigureUpdate
%#function SP2_Data_FormatImagUpdate
%#function SP2_Data_FormatMagnUpdate
%#function SP2_Data_FormatPhaseUpdate
%#function SP2_Data_FormatRealUpdate
%#function SP2_Data_FrequCorrPeakUpdate
%#function SP2_Data_FrequCorrPointUpdate
%#function SP2_Data_FrequCorrUpdate
%#function SP2_Data_GEParsConsistency
%#function SP2_Data_GEParsConversion
%#function SP2_Data_GEReadFid
%#function SP2_Data_GEReadFidJDE
%#function SP2_Data_GEReadHeader
%#function SP2_Data_JmruiReadFid
%#function SP2_Data_KeepFigureUpdate
%#function SP2_Data_MrsiReadEncTable
%#function SP2_Data_NPhaseCycleUpdate
%#function SP2_Data_PhaseCorrFirstUpdate
%#function SP2_Data_PhaseCorrKloseCombinedUpdate
%#function SP2_Data_PhaseCorrKloseRxComb
%#function SP2_Data_PhaseCorrKloseRxCombJdeArray
%#function SP2_Data_PhaseCorrKloseRxCombSatRec
%#function SP2_Data_PhaseCorrKloseSelectedUpdate
%#function SP2_Data_PhaseCorrKloseSeparateUpdate
%#function SP2_Data_PhaseCorrKloseUpdate
%#function SP2_Data_PhaseCorrNrUpdate
%#function SP2_Data_PhaseLinearCorrectionUpdate
%#function SP2_Data_PhilipsRawParsConsistency
%#function SP2_Data_PhilipsRawParsConversion
%#function SP2_Data_PhilipsRawReadFid
%#function SP2_Data_PhilipsRawReadFidJDE
%#function SP2_Data_PhilipsRawReadSinLabFiles
%#function SP2_Data_PhilipsSdatParsConsistency
%#function SP2_Data_PhilipsSdatParsConversion
%#function SP2_Data_PhilipsSdatReadFid
%#function SP2_Data_PhilipsSdatReadSparFile
%#function SP2_Data_PlotAnaArray
%#function SP2_Data_PlotAnaAverage
%#function SP2_Data_PlotAnaFWHM
%#function SP2_Data_PlotAnaFid1Update
%#function SP2_Data_PlotAnaFid2Update
%#function SP2_Data_PlotAnaIntegral
%#function SP2_Data_PlotAnaSNR
%#function SP2_Data_PlotAnaSingle
%#function SP2_Data_PlotAnaSpec1Update
%#function SP2_Data_PlotAnaSpec2Update
%#function SP2_Data_PlotAnaSuperposition
%#function SP2_Data_PlotFid1Array
%#function SP2_Data_PlotFid1Single
%#function SP2_Data_PlotFid1Superposition
%#function SP2_Data_PlotFid2Array
%#function SP2_Data_PlotFid2Single
%#function SP2_Data_PlotFid2Superposition
%#function SP2_Data_PlotSpec1Array
%#function SP2_Data_PlotSpec1Average
%#function SP2_Data_PlotSpec1Single
%#function SP2_Data_PlotSpec1Superposition
%#function SP2_Data_PlotSpec2Array
%#function SP2_Data_PlotSpec2Average
%#function SP2_Data_PlotSpec2Single
%#function SP2_Data_PlotSpec2Superposition
%#function SP2_Data_PpmAssignToPeak
%#function SP2_Data_PpmAssignUpdate
%#function SP2_Data_PpmCalibUpdate
%#function SP2_Data_PpmCorrWinUpdate
%#function SP2_Data_PpmNoiseWinUpdate
%#function SP2_Data_PpmShowDirectUpdate
%#function SP2_Data_PpmShowFullUpdate
%#function SP2_Data_PpmShowWinUpdate
%#function SP2_Data_PpmTargetWinUpdate
%#function SP2_Data_ProcparConsistency
%#function SP2_Data_ProcparConversion
%#function SP2_Data_ProtocolExport
%#function SP2_Data_ProtocolLoad
%#function SP2_Data_ProtocolPathUpdate
%#function SP2_Data_ProtocolSave
%#function SP2_Data_ProtocolSelect
%#function SP2_Data_PvAcqpConsistency
%#function SP2_Data_PvAvanceConvList
%#function SP2_Data_PvConvdta
%#function SP2_Data_PvMethodConsistency
%#function SP2_Data_PvParsConversion
%#function SP2_Data_PvReadAcqp
%#function SP2_Data_PvReadMethod
%#function SP2_Data_PvReadNewFid
%#function SP2_Data_PvReadNewFidJDE
%#function SP2_Data_PvReadNewRawData
%#function SP2_Data_PvReadNewRawDataJDE
%#function SP2_Data_PvReadOldFid
%#function SP2_Data_PvReadOldFidJDE
%#function SP2_Data_PvReadRawData
%#function SP2_Data_QualityAmplAutoUpdate
%#function SP2_Data_QualityAmplDirectUpdate
%#function SP2_Data_QualityArrayBackward
%#function SP2_Data_QualityArrayClose
%#function SP2_Data_QualityArrayForward
%#function SP2_Data_QualityArraySelectNrUpdate
%#function SP2_Data_QualityArrayShow
%#function SP2_Data_QualityArrayShow_02Dec2013_10pm
%#function SP2_Data_QualityCalcFidArrRxComb
%#function SP2_Data_QualityCalcFidArrRxComb_obsSnrErr_Oct2020
%#function SP2_Data_QualityCalcFidArrSerial
%#function SP2_Data_QualityColormapHotUpdate
%#function SP2_Data_QualityColormapHsvUpdate
%#function SP2_Data_QualityColormapJetUpdate
%#function SP2_Data_QualityColormapLegendUpdate
%#function SP2_Data_QualityColormapMatch
%#function SP2_Data_QualityColormapUniUpdate
%#function SP2_Data_QualityDetailsMain
%#function SP2_Data_QualityDetailsWinUpdate
%#function SP2_Data_QualityExcludeStrUpdate
%#function SP2_Data_QualityExitMain
%#function SP2_Data_QualityFormatImagUpdate
%#function SP2_Data_QualityFormatMagnUpdate
%#function SP2_Data_QualityFormatPhaseUpdate
%#function SP2_Data_QualityFormatRealUpdate
%#function SP2_Data_QualityFrequDirectUpdate
%#function SP2_Data_QualityFrequglobalUpdate
%#function SP2_Data_QualityParsUpdate
%#function SP2_Data_QualityPhModeIntegralUpdate
%#function SP2_Data_QualityReplaceApply
%#function SP2_Data_QualityReplaceApply_July2016
%#function SP2_Data_QualityReplaceStrUpdate
%#function SP2_Data_QualitySelectInitJde1
%#function SP2_Data_QualitySelectInitJde2
%#function SP2_Data_QualitySelectInitNonJde
%#function SP2_Data_QualitySelectStrUpdate
%#function SP2_Data_QualitySeriesClose
%#function SP2_Data_QualitySeriesIntegralUpdate
%#function SP2_Data_QualitySeriesMaxUpdate
%#function SP2_Data_QualitySeriesMeanUpdate
%#function SP2_Data_QualitySeriesMedianUpdate
%#function SP2_Data_QualitySeriesMinUpdate
%#function SP2_Data_QualitySeriesShow
%#function SP2_Data_QualitySeriesStdDevUpdate
%#function SP2_Data_QualitySuperposClose
%#function SP2_Data_QualitySuperposShow
%#function SP2_Data_RcvrAllUpdate
%#function SP2_Data_RcvrSelectStrUpdate
%#function SP2_Data_RcvrSelectUpdate
%#function SP2_Data_RcvrVecUpdate
%#function SP2_Data_RcvrWeightUpdate
%#function SP2_Data_ResetDefProtocol
%#function SP2_Data_ResetSpec
%#function SP2_Data_SatRecMinTiIndexCalc
%#function SP2_Data_SatRecMinTiUpdate
%#function SP2_Data_ScrollReceiverDecr
%#function SP2_Data_ScrollReceiverIncr
%#function SP2_Data_ScrollReceiverUpdate
%#function SP2_Data_ScrollRepetitionDecr
%#function SP2_Data_ScrollRepetitionIncr
%#function SP2_Data_ScrollRepetitionUpdate
%#function SP2_Data_SiemensDatParsConsistency
%#function SP2_Data_SiemensDatParsConversion
%#function SP2_Data_SiemensDatReadFid
%#function SP2_Data_SiemensDatReadFidJDE
%#function SP2_Data_SiemensDatReadFidJdeVB
%#function SP2_Data_SiemensDatReadFidJdeVDVE
%#function SP2_Data_SiemensDatReadFidVB
%#function SP2_Data_SiemensDatReadFidVDVE
%#function SP2_Data_SiemensDatReadHeader
%#function SP2_Data_SiemensRdaParsConsistency
%#function SP2_Data_SiemensRdaParsConversion
%#function SP2_Data_SiemensRdaReadFid
%#function SP2_Data_SiemensRdaReadFidJDE
%#function SP2_Data_SiemensRdaReadHeader
%#function SP2_Data_T2SpecialUpdate
%#function SP2_Data_VerboseFlagUpdate
%#function SP2_Data_VnmrReadFid
%#function SP2_Data_VnmrReadFidArray
%#function SP2_Data_VnmrReadFidJDE
%#function SP2_Data_VnmrReadFidJDEArray
%#function SP2_Data_VnmrReadFidMRSI
%#function SP2_Data_VnmrReadFidNR
%#function SP2_Data_VnmrReadFidSatRec
%#function SP2_Data_VnmrReadFidStability
%#function SP2_Data_VnmrReadFidT1T2
%#function SP2_Data_VnmrReadHeader_old
%#function SP2_Data_VnmrReadHeaders
%#function SP2_Data_VnmrReadProcpar
%#function SP2_Exit_ExitFct
%#function SP2_Exit_ExitMain
%#function SP2_BestApprox
%#function SP2_CellArrayToStrList
%#function SP2_Check4Bigger0
%#function SP2_Check4Bigger0R
%#function SP2_Check4Cell
%#function SP2_Check4CellR
%#function SP2_Check4ColVec
%#function SP2_Check4FlagR
%#function SP2_Check4Int
%#function SP2_Check4IntBigger0
%#function SP2_Check4IntBigger0R
%#function SP2_Check4IntR
%#function SP2_Check4Num
%#function SP2_Check4NumR
%#function SP2_Check4RowVec
%#function SP2_Check4RowVecR
%#function SP2_Check4Str
%#function SP2_Check4StrR
%#function SP2_Check4StructR
%#function SP2_CheckDirAccess
%#function SP2_CheckDirAccessR
%#function SP2_CheckDirWritePermR
%#function SP2_CheckFileExistence
%#function SP2_CheckFileExistenceR
%#function SP2_ClearSelExmArrays
%#function SP2_ClearWindow
%#function SP2_ConvertGray2RGB
%#function SP2_ConvertList2Product
%#function SP2_CreateFctList4StandAlone
%#function SP2_DirAccessMax
%#function SP2_DisplPars
%#function SP2_DistMeasure
%#function SP2_ExtractFileDir
%#function SP2_ExtractFileDirAndName
%#function SP2_ExtractFileName
%#function SP2_FWHM
%#function SP2_FWHM_2013
%#function SP2_FctList4StandAlone
%#function SP2_FindAllFiles
%#function SP2_FindFiles
%#function SP2_GetAllFiles
%#function SP2_GuaranteeFinalSlash
%#function SP2_IdealAxisValues
%#function SP2_IdealAxisValuesXGap
%#function SP2_KeepFigure
%#function SP2_MaxMatInd
%#function SP2_ModifyAxisValues
%#function SP2_NSpaces
%#function SP2_PathWinLin
%#function SP2_PathWinLin_Nov2016
%#function SP2_PlotRangeDeterm
%#function SP2_Polyfit2
%#function SP2_PrVersionUscore
%#function SP2_PrVersionUscoreCell
%#function SP2_PrintCell
%#function SP2_PrintStructure
%#function SP2_RagLoadFid
%#function SP2_ReadDefaults
%#function SP2_RoundToNthDigit
%#function SP2_RoundToPowerOfN
%#function SP2_ScrollRight
%#function SP2_Sec2ClockStr
%#function SP2_SetRGBcolor
%#function SP2_Show3D
%#function SP2_SignDigitN
%#function SP2_SlashWinLin
%#function SP2_SplineMaxDeterm
%#function SP2_SubstStrPart
%#function SP2_TransferGray2RGB
%#function SP2_Vec2PrintStr
%#function SP2_Vec2PrintStrSign
%#function SP2_Vec2PrintStr_2013
%#function SP2_Vec2PrintStr_2015
%#function SP2_XTickLabelRotate
%#function SP2_ZeroPhasing
%#function SP2_l1eq_pd
%#function Original_SP2_LCM_Analysis
%#function SP2_LCM_AmplAutoUpdate
%#function SP2_LCM_AmplDirectUpdate
%#function SP2_LCM_AmplWinMaxDecr
%#function SP2_LCM_AmplWinMaxIncr
%#function SP2_LCM_AmplWinMinDecr
%#function SP2_LCM_AmplWinMinIncr
%#function SP2_LCM_AmplWinUpdate
%#function SP2_LCM_AnaComplexUpdate
%#function SP2_LCM_AnaDoAnalysis
%#function SP2_LCM_AnaDoCalcCRLB
%#function SP2_LCM_AnaDoCalcCRLBTotal
%#function SP2_LCM_AnaDoCalcCRLB_Combined
%#function SP2_LCM_AnaDoCalcCRLB_Individual
%#function SP2_LCM_AnaDoCtrlC
%#function SP2_LCM_AnaFitFct
%#function SP2_LCM_AnaFrequDifference
%#function SP2_LCM_AnaFwhmUpdate
%#function SP2_LCM_AnaGbFlagUpdate
%#function SP2_LCM_AnaIntegralUpdate
%#function SP2_LCM_AnaLbFlagUpdate
%#function SP2_LCM_AnaOffsetFlagUpdate
%#function SP2_LCM_AnaPhc0FlagUpdate
%#function SP2_LCM_AnaPhc1FlagUpdate
%#function SP2_LCM_AnaPolyFlagUpdate
%#function SP2_LCM_AnaPolyOrderDec
%#function SP2_LCM_AnaPolyOrderInc
%#function SP2_LCM_AnaPolyOrderUpdate
%#function SP2_LCM_AnaPpmStrUpdate
%#function SP2_LCM_AnaRealUpdate
%#function SP2_LCM_AnaSaveCorrFigures
%#function SP2_LCM_AnaSaveJpegFlagUpdate
%#function SP2_LCM_AnaSaveLogFlagUpdate
%#function SP2_LCM_AnaSaveLogInit
%#function SP2_LCM_AnaSaveSpecs
%#function SP2_LCM_AnaSaveSpxFigures
%#function SP2_LCM_AnaSaveSummaryFigure
%#function SP2_LCM_AnaSaveSuperposFigure
%#function SP2_LCM_AnaSaveXls
%#function SP2_LCM_AnaSaveXls_May2016
%#function SP2_LCM_AnaScaleFlagUpdate
%#function SP2_LCM_AnaShapeFlagUpdate
%#function SP2_LCM_AnaShiftFlagUpdate
%#function SP2_LCM_AnaSnrUpdate
%#function SP2_LCM_AnaSplPtsPerPpmUpdate
%#function SP2_LCM_AnaSplineFlagUpdate
%#function SP2_LCM_AnaStartValReset
%#function SP2_LCM_Analysis
%#function SP2_LCM_BSpline
%#function SP2_LCM_BSpline_tmp10PM
%#function SP2_LCM_BaseMain
%#function SP2_LCM_BaseWinUpdate
%#function SP2_LCM_BaselineCorrInterp
%#function SP2_LCM_BaselineCorrPoly
%#function SP2_LCM_ExitBaseMain
%#function SP2_LCM_InterpModeCubic
%#function SP2_LCM_InterpModeLinear
%#function SP2_LCM_InterpModeNearest
%#function SP2_LCM_InterpModeSpline
%#function SP2_LCM_InterpPpmStrUpdate
%#function SP2_LCM_PolyOrderUpdate
%#function SP2_LCM_PolyPpmStrUpdate
%#function SP2_LCM_SvdPeakAnalysis
%#function SP2_LCM_SvdPeakNumberUpdate
%#function SP2_LCM_SvdPeakRemoval
%#function SP2_LCM_SvdPhaseAndAmpFitFct
%#function SP2_LCM_SvdPpmStrUpdate
%#function SP2_LCM_SvdResultVisualization
%#function SP2_LCM_BasisAdd
%#function SP2_LCM_BasisAnalysis
%#function SP2_LCM_BasisAssign
%#function SP2_LCM_BasisClearWindow
%#function SP2_LCM_BasisCommentUpdate
%#function SP2_LCM_BasisDelete
%#function SP2_LCM_BasisExitMain
%#function SP2_LCM_BasisFigureUpdate
%#function SP2_LCM_BasisImport
%#function SP2_LCM_BasisLoad
%#function SP2_LCM_BasisMain
%#function SP2_LCM_BasisMove
%#function SP2_LCM_BasisNameUpdate
%#function SP2_LCM_BasisPlotSpecSingle
%#function SP2_LCM_BasisPpmCalibUpdate
%#function SP2_LCM_BasisProcAndPlotUpdate
%#function SP2_LCM_BasisProcData
%#function SP2_LCM_BasisReorder
%#function SP2_LCM_BasisReorderUpdate
%#function SP2_LCM_BasisRspBandwidth
%#function SP2_LCM_BasisSave
%#function SP2_LCM_BasisT1Update
%#function SP2_LCM_BasisT2Update
%#function SP2_LCM_BasisWinUpdate
%#function SP2_LCM_CloseLcmFigures
%#function SP2_LCM_ColormapHotUpdate
%#function SP2_LCM_ColormapHsvUpdate
%#function SP2_LCM_ColormapJetUpdate
%#function SP2_LCM_ColormapUniUpdate
%#function SP2_LCM_SerialMetabAnalysis
%#function SP2_LCM_DataDataUpdate
%#function SP2_LCM_DataFormatUpdate
%#function SP2_LCM_DataLcmUpdate
%#function SP2_LCM_DataMarssUpdate
%#function SP2_LCM_DataMrsiUpdate
%#function SP2_LCM_DataProcUpdate
%#function SP2_LCM_DataSynUpdate
%#function SP2_LCM_DoProcAndSave
%#function SP2_LCM_DoSave
%#function SP2_LCM_ExptDataMatUpdate
%#function SP2_LCM_ExptDataPathUpdate
%#function SP2_LCM_ExptDataRawUpdate
%#function SP2_LCM_ExptDataSave
%#function SP2_LCM_ExptDataSelect
%#function SP2_LCM_ExptDataTxtUpdate
%#function SP2_LCM_ExtractPpmRange
%#function SP2_LCM_FigureUpdate
%#function SP2_LCM_FitAnaAdoptLast_obs
%#function SP2_LCM_FitAnaGbFlagUpdate
%#function SP2_LCM_FitAnaLbFlagUpdate
%#function SP2_LCM_FitAnaShiftFlagUpdate
%#function SP2_LCM_FitClearWindow
%#function SP2_LCM_FitComb1FlagUpdate
%#function SP2_LCM_FitComb1StrUpdate
%#function SP2_LCM_FitComb2FlagUpdate
%#function SP2_LCM_FitComb2StrUpdate
%#function SP2_LCM_FitComb3FlagUpdate
%#function SP2_LCM_FitComb3StrUpdate
%#function SP2_LCM_FitDetailsMain
%#function SP2_LCM_FitDetailsWinUpdate
%#function SP2_LCM_FitExitMain
%#function SP2_LCM_FitFigureUpdate
%#function SP2_LCM_FitGbAnaAdoptLast
%#function SP2_LCM_FitGbAnaUpdate
%#function SP2_LCM_FitGbMaxAdoptLast
%#function SP2_LCM_FitGbMaxUpdate
%#function SP2_LCM_FitGbMinAdoptLast
%#function SP2_LCM_FitGbMinUpdate
%#function SP2_LCM_FitGbReset
%#function SP2_LCM_FitGbVarMaxApply
%#function SP2_LCM_FitGbVarMaxUpdate
%#function SP2_LCM_FitGbVarMinApply
%#function SP2_LCM_FitGbVarMinUpdate
%#function SP2_LCM_FitLbAnaAdoptLast
%#function SP2_LCM_FitLbAnaUpdate
%#function SP2_LCM_FitLbMaxAdoptLast
%#function SP2_LCM_FitLbMaxUpdate
%#function SP2_LCM_FitLbMinAdoptLast
%#function SP2_LCM_FitLbMinUpdate
%#function SP2_LCM_FitLbReset
%#function SP2_LCM_FitLbVarMaxApply
%#function SP2_LCM_FitLbVarMaxUpdate
%#function SP2_LCM_FitLbVarMinApply
%#function SP2_LCM_FitLbVarMinUpdate
%#function SP2_LCM_FitLinkGbUpdate
%#function SP2_LCM_FitLinkLbUpdate
%#function SP2_LCM_FitLinkShapeUpdate
%#function SP2_LCM_FitLinkShiftUpdate
%#function SP2_LCM_FitMaxIterUpdate
%#function SP2_LCM_FitPhc0AnaUpdate
%#function SP2_LCM_FitPhc0FlagUpdate
%#function SP2_LCM_FitPhc0Reset
%#function SP2_LCM_FitPhc0VarAdoptLast
%#function SP2_LCM_FitPhc0VarUpdate
%#function SP2_LCM_FitPhc1AnaUpdate
%#function SP2_LCM_FitPhc1FlagUpdate
%#function SP2_LCM_FitPhc1Reset
%#function SP2_LCM_FitPhc1VarAdoptLast
%#function SP2_LCM_FitPhc1VarUpdate
%#function SP2_LCM_FitPolyAmp0Reset
%#function SP2_LCM_FitPolyAmp0Update
%#function SP2_LCM_FitPolyAmp10Reset
%#function SP2_LCM_FitPolyAmp10Update
%#function SP2_LCM_FitPolyAmp1Reset
%#function SP2_LCM_FitPolyAmp1Update
%#function SP2_LCM_FitPolyAmp2Reset
%#function SP2_LCM_FitPolyAmp2Update
%#function SP2_LCM_FitPolyAmp3Reset
%#function SP2_LCM_FitPolyAmp3Update
%#function SP2_LCM_FitPolyAmp4Reset
%#function SP2_LCM_FitPolyAmp4Update
%#function SP2_LCM_FitPolyAmp5Reset
%#function SP2_LCM_FitPolyAmp5Update
%#function SP2_LCM_FitPolyAmp6Reset
%#function SP2_LCM_FitPolyAmp6Update
%#function SP2_LCM_FitPolyAmp7Reset
%#function SP2_LCM_FitPolyAmp7Update
%#function SP2_LCM_FitPolyAmp8Reset
%#function SP2_LCM_FitPolyAmp8Update
%#function SP2_LCM_FitPolyAmp9Reset
%#function SP2_LCM_FitPolyAmp9Update
%#function SP2_LCM_FitPolyAmpAllReset
%#function SP2_LCM_FitPolyFlagUpdate
%#function SP2_LCM_FitScaleAnaAdoptLast
%#function SP2_LCM_FitScaleAnaUpdate
%#function SP2_LCM_FitScaleReset
%#function SP2_LCM_FitSelectAdoptLast
%#function SP2_LCM_FitSelectUpdate
%#function SP2_LCM_FitShapeVarAdoptLast
%#function SP2_LCM_FitShapeVarUpdate
%#function SP2_LCM_FitShiftAnaAdoptLast
%#function SP2_LCM_FitShiftAnaUpdate
%#function SP2_LCM_FitShiftMaxAdoptLast
%#function SP2_LCM_FitShiftMaxUpdate
%#function SP2_LCM_FitShiftMinAdoptLast
%#function SP2_LCM_FitShiftMinUpdate
%#function SP2_LCM_FitShiftReset
%#function SP2_LCM_FitShiftVarMaxApply
%#function SP2_LCM_FitShiftVarMaxUpdate
%#function SP2_LCM_FitShiftVarMinApply
%#function SP2_LCM_FitShiftVarMinUpdate
%#function SP2_LCM_FitTolFunUpdate
%#function SP2_LCM_KeepFigureUpdate
%#function SP2_LCM_LCModelMain
%#function SP2_LCM_LCModelWinUpdate
%#function SP2_LCM_LcmBasisLoad
%#function SP2_LCM_LcmBasisPathUpdate
%#function SP2_LCM_LcmBasisSelect
%#function SP2_LCM_LegendUpdate
%#function SP2_LCM_AnaDoMonteCarloInVivo
%#function SP2_LCM_AnaDoMonteCarloInVivoBatch
%#function SP2_LCM_AnaDoMonteCarloSim
%#function SP2_LCM_MCarloBatchNUpdate
%#function SP2_LCM_MCarloContUpdate
%#function SP2_LCM_MCarloInitUpdate
%#function SP2_LCM_MCarloMasterScript
%#function SP2_LCM_MCarloNUpdate
%#function SP2_LCM_MCarloRefUpdate
%#function SP2_LCM_MCarloSpreadUpdate
%#function SP2_LCM_MCarloStop
%#function SP2_LCM_OffsetAssign
%#function SP2_LCM_OffsetDec1
%#function SP2_LCM_OffsetDec2
%#function SP2_LCM_OffsetDec3
%#function SP2_LCM_OffsetInc1
%#function SP2_LCM_OffsetInc2
%#function SP2_LCM_OffsetInc3
%#function SP2_LCM_OffsetPpmWinFlagUpdate
%#function SP2_LCM_OffsetPpmWinUpdate
%#function SP2_LCM_OffsetValueFlagUpdate
%#function SP2_LCM_OffsetValueUpdate
%#function SP2_LCM_OffsetZero
%#function SP2_LCM_PlotLcmFid
%#function SP2_LCM_PlotLcmFidOrig
%#function SP2_LCM_PlotLcmSpec
%#function SP2_LCM_PlotLineWidthUpdate
%#function SP2_LCM_PlotResultSpecResidual
%#function SP2_LCM_PlotResultSpecSingle
%#function SP2_LCM_PlotResultSpecSum
%#function SP2_LCM_PlotResultSpecSummary
%#function SP2_LCM_PlotResultSpecSuperpos
%#function SP2_LCM_PpmAssignFromProc
%#function SP2_LCM_PpmAssignToPeak
%#function SP2_LCM_PpmAssignToPeakZoom
%#function SP2_LCM_PpmAssignUpdate
%#function SP2_LCM_PpmCalibUpdate
%#function SP2_LCM_PpmNoiseMaxDecr
%#function SP2_LCM_PpmNoiseMaxIncr
%#function SP2_LCM_PpmNoiseMinDecr
%#function SP2_LCM_PpmNoiseMinIncr
%#function SP2_LCM_PpmNoiseWinUpdate
%#function SP2_LCM_PpmOffsetMaxDecr
%#function SP2_LCM_PpmOffsetMaxIncr
%#function SP2_LCM_PpmOffsetMinDecr
%#function SP2_LCM_PpmOffsetMinIncr
%#function SP2_LCM_PpmShowDirectUpdate
%#function SP2_LCM_PpmShowFullUpdate
%#function SP2_LCM_PpmShowMaxDecr
%#function SP2_LCM_PpmShowMaxIncr
%#function SP2_LCM_PpmShowMinDecr
%#function SP2_LCM_PpmShowMinIncr
%#function SP2_LCM_PpmShowPosAssign
%#function SP2_LCM_PpmShowPosFlagUpdate
%#function SP2_LCM_PpmShowPosValUpdate
%#function SP2_LCM_PpmShowWinUpdate
%#function SP2_LCM_PpmTargetMaxDecr
%#function SP2_LCM_PpmTargetMaxIncr
%#function SP2_LCM_PpmTargetMinDecr
%#function SP2_LCM_PpmTargetMinIncr
%#function SP2_LCM_PpmTargetWinUpdate
%#function SP2_LCM_ProcAndPlotFid
%#function SP2_LCM_ProcAndPlotFidOrig
%#function SP2_LCM_ProcAndPlotSpec
%#function SP2_LCM_ProcAndPlotUpdate
%#function SP2_LCM_ProcLcmData
%#function SP2_LCM_ProcResultData
%#function SP2_LCM_ProcessFid
%#function SP2_LCM_ProcessSpec
%#function SP2_LCM_ResultPlotBaseCorrUpdate
%#function SP2_LCM_ResultPlotIncludeBaseUpdate
%#function SP2_LCM_ResultPlotIncludeFitUpdate
%#function SP2_LCM_ResultPlotIncludeResidUpdate
%#function SP2_LCM_ResultPlotIncludeTargetUpdate
%#function SP2_LCM_ResultSpecSingleCurrDecr
%#function SP2_LCM_ResultSpecSingleCurrIncr
%#function SP2_LCM_ResultSpecSingleCurrUpdate
%#function SP2_LCM_ShowSelStrUpdate
%#function SP2_LCM_ShowSelUpdate
%#function SP2_LCM_SpecCutDec1
%#function SP2_LCM_SpecCutDec2
%#function SP2_LCM_SpecCutDec3
%#function SP2_LCM_SpecCutFlagUpdate
%#function SP2_LCM_SpecCutInc1
%#function SP2_LCM_SpecCutInc2
%#function SP2_LCM_SpecCutInc3
%#function SP2_LCM_SpecCutReset
%#function SP2_LCM_SpecCutUpdate
%#function SP2_LCM_SpecDataAndParsAssign
%#function SP2_LCM_SpecDataJmruiUpdate
%#function SP2_LCM_SpecDataLoadFromDataPage
%#function SP2_LCM_SpecDataLoadFromLcmPage
%#function SP2_LCM_SpecDataLoadFromMarssPage
%#function SP2_LCM_SpecDataLoadFromMrsiPage
%#function SP2_LCM_SpecDataLoadFromProcPage
%#function SP2_LCM_SpecDataLoadFromSynPage
%#function SP2_LCM_SpecDataMatUpdate
%#function SP2_LCM_SpecDataParUpdate
%#function SP2_LCM_SpecDataPathUpdate
%#function SP2_LCM_SpecDataRawUpdate
%#function SP2_LCM_SpecDataSelect
%#function SP2_LCM_SpecDataTxtUpdate
%#function SP2_LCM_SpecGbDec1
%#function SP2_LCM_SpecGbDec2
%#function SP2_LCM_SpecGbDec3
%#function SP2_LCM_SpecGbFlagUpdate
%#function SP2_LCM_SpecGbInc1
%#function SP2_LCM_SpecGbInc2
%#function SP2_LCM_SpecGbInc3
%#function SP2_LCM_SpecGbReset
%#function SP2_LCM_SpecGbUpdate
%#function SP2_LCM_SpecLbDec1
%#function SP2_LCM_SpecLbDec2
%#function SP2_LCM_SpecLbDec3
%#function SP2_LCM_SpecLbFlagUpdate
%#function SP2_LCM_SpecLbInc1
%#function SP2_LCM_SpecLbInc2
%#function SP2_LCM_SpecLbInc3
%#function SP2_LCM_SpecLbReset
%#function SP2_LCM_SpecLbUpdate
%#function SP2_LCM_SpecOffsetDec1
%#function SP2_LCM_SpecOffsetDec2
%#function SP2_LCM_SpecOffsetDec3
%#function SP2_LCM_SpecOffsetFlagUpdate
%#function SP2_LCM_SpecOffsetInc1
%#function SP2_LCM_SpecOffsetInc2
%#function SP2_LCM_SpecOffsetInc3
%#function SP2_LCM_SpecOffsetReset
%#function SP2_LCM_SpecOffsetUpdate
%#function SP2_LCM_SpecParsDialogExit
%#function SP2_LCM_SpecParsDialogMain
%#function SP2_LCM_SpecParsNspeccUpdate
%#function SP2_LCM_SpecParsSfUpdate
%#function SP2_LCM_SpecParsSwhUpdate
%#function SP2_LCM_SpecPhc0Dec1
%#function SP2_LCM_SpecPhc0Dec2
%#function SP2_LCM_SpecPhc0Dec3
%#function SP2_LCM_SpecPhc0FlagUpdate
%#function SP2_LCM_SpecPhc0Inc1
%#function SP2_LCM_SpecPhc0Inc2
%#function SP2_LCM_SpecPhc0Inc3
%#function SP2_LCM_SpecPhc0Reset
%#function SP2_LCM_SpecPhc0Update
%#function SP2_LCM_SpecPhc1Dec1
%#function SP2_LCM_SpecPhc1Dec2
%#function SP2_LCM_SpecPhc1Dec3
%#function SP2_LCM_SpecPhc1FlagUpdate
%#function SP2_LCM_SpecPhc1Inc1
%#function SP2_LCM_SpecPhc1Inc2
%#function SP2_LCM_SpecPhc1Inc3
%#function SP2_LCM_SpecPhc1Reset
%#function SP2_LCM_SpecPhc1Update
%#function SP2_LCM_SpecScaleDec1
%#function SP2_LCM_SpecScaleDec2
%#function SP2_LCM_SpecScaleDec3
%#function SP2_LCM_SpecScaleFlagUpdate
%#function SP2_LCM_SpecScaleInc1
%#function SP2_LCM_SpecScaleInc2
%#function SP2_LCM_SpecScaleInc3
%#function SP2_LCM_SpecScaleReset
%#function SP2_LCM_SpecScaleUpdate
%#function SP2_LCM_SpecShiftDec1
%#function SP2_LCM_SpecShiftDec2
%#function SP2_LCM_SpecShiftDec3
%#function SP2_LCM_SpecShiftFlagUpdate
%#function SP2_LCM_SpecShiftInc1
%#function SP2_LCM_SpecShiftInc2
%#function SP2_LCM_SpecShiftInc3
%#function SP2_LCM_SpecShiftReset
%#function SP2_LCM_SpecShiftUpdate
%#function SP2_LCM_SpecZfDec1
%#function SP2_LCM_SpecZfDec2
%#function SP2_LCM_SpecZfDec3
%#function SP2_LCM_SpecZfFlagUpdate
%#function SP2_LCM_SpecZfInc1
%#function SP2_LCM_SpecZfInc2
%#function SP2_LCM_SpecZfInc3
%#function SP2_LCM_SpecZfReset
%#function SP2_LCM_SpecZfUpdate
%#function SP2_LCM_UpdateCalcUpdate
%#function SP2_LCM_UpdateProcBasisUpdate
%#function SP2_LCM_UpdateProcResultUpdate
%#function SP2_LCM_UpdateProcTargetUpdate
%#function SP2_LCM_VerboseFlagUpdate
%#function SP2_MARSS_AmplShowAutoUpdate
%#function SP2_MARSS_AmplShowDirectUpdate
%#function SP2_MARSS_AmplShowMaxDecr
%#function SP2_MARSS_AmplShowMaxIncr
%#function SP2_MARSS_AmplShowMaxUpdate
%#function SP2_MARSS_AmplShowMinDecr
%#function SP2_MARSS_AmplShowMinIncr
%#function SP2_MARSS_AmplShowMinUpdate
%#function SP2_MARSS_AmplShowUpdate
%#function SP2_MARSS_BandwidthInHertzUpdate
%#function SP2_MARSS_BandwidthInPpmUpdate
%#function SP2_MARSS_BasisDirPathUpdate
%#function SP2_MARSS_BasisDirSelect
%#function SP2_MARSS_BasisFileLoad
%#function SP2_MARSS_BasisFileNameUpdate
%#function SP2_MARSS_BasisFileSelect
%#function SP2_MARSS_BasisRmAll
%#function SP2_MARSS_BasisRmSelected
%#function SP2_MARSS_BasisSave
%#function SP2_MARSS_CloseMarssFigures
%#function SP2_MARSS_ColormapHotUpdate
%#function SP2_MARSS_ColormapHsvUpdate
%#function SP2_MARSS_ColormapJetUpdate
%#function SP2_MARSS_ColormapUniUpdate
%#function SP2_MARSS_DoSimulation
%#function SP2_MARSS_ExtractPpmRange
%#function SP2_MARSS_FigureUpdate
%#function SP2_MARSS_AdjustDelays
%#function SP2_MARSS_ReadFileM
%#function SP2_MARSS_RunMARSS
%#function SP2_MARSS_SaveSignals
%#function SP2_MARSS_KeepFigureUpdate
%#function SP2_MARSS_LarmorInHertzUpdate
%#function SP2_MARSS_LarmorInTeslaUpdate
%#function SP2_MARSS_LegendUpdate
%#function SP2_MARSS_MARSSMain
%#function SP2_MARSS_MARSSWinUpdate
%#function SP2_MARSS_PlotSpecSingle
%#function SP2_MARSS_PlotSpecSum
%#function SP2_MARSS_PlotSpecSuperpos
%#function SP2_MARSS_PpmShowDirectUpdate
%#function SP2_MARSS_PpmShowFullUpdate
%#function SP2_MARSS_PpmShowMaxDecr
%#function SP2_MARSS_PpmShowMaxIncr
%#function SP2_MARSS_PpmShowMaxUpdate
%#function SP2_MARSS_PpmShowMinDecr
%#function SP2_MARSS_PpmShowMinIncr
%#function SP2_MARSS_PpmShowMinUpdate
%#function SP2_MARSS_ProcAndPlotSpecSingle
%#function SP2_MARSS_ProcAndPlotSpecSum
%#function SP2_MARSS_ProcAndPlotSpecSuperpos
%#function SP2_MARSS_ProcAndPlotUpdate
%#function SP2_MARSS_ProcComplete
%#function SP2_MARSS_ProcCutDec1
%#function SP2_MARSS_ProcCutDec2
%#function SP2_MARSS_ProcCutDec3
%#function SP2_MARSS_ProcCutFlagUpdate
%#function SP2_MARSS_ProcCutInc1
%#function SP2_MARSS_ProcCutInc2
%#function SP2_MARSS_ProcCutInc3
%#function SP2_MARSS_ProcCutReset
%#function SP2_MARSS_ProcCutUpdate
%#function SP2_MARSS_ProcGbDec1
%#function SP2_MARSS_ProcGbDec2
%#function SP2_MARSS_ProcGbDec3
%#function SP2_MARSS_ProcGbFlagUpdate
%#function SP2_MARSS_ProcGbInc1
%#function SP2_MARSS_ProcGbInc2
%#function SP2_MARSS_ProcGbInc3
%#function SP2_MARSS_ProcGbReset
%#function SP2_MARSS_ProcGbUpdate
%#function SP2_MARSS_ProcLbDec1
%#function SP2_MARSS_ProcLbDec2
%#function SP2_MARSS_ProcLbDec3
%#function SP2_MARSS_ProcLbFlagUpdate
%#function SP2_MARSS_ProcLbInc1
%#function SP2_MARSS_ProcLbInc2
%#function SP2_MARSS_ProcLbInc3
%#function SP2_MARSS_ProcLbReset
%#function SP2_MARSS_ProcLbUpdate
%#function SP2_MARSS_ProcOffsetDec1
%#function SP2_MARSS_ProcOffsetDec2
%#function SP2_MARSS_ProcOffsetDec3
%#function SP2_MARSS_ProcOffsetFlagUpdate
%#function SP2_MARSS_ProcOffsetInc1
%#function SP2_MARSS_ProcOffsetInc2
%#function SP2_MARSS_ProcOffsetInc3
%#function SP2_MARSS_ProcOffsetReset
%#function SP2_MARSS_ProcOffsetUpdate
%#function SP2_MARSS_ProcPhc0Dec1
%#function SP2_MARSS_ProcPhc0Dec2
%#function SP2_MARSS_ProcPhc0Dec3
%#function SP2_MARSS_ProcPhc0FlagUpdate
%#function SP2_MARSS_ProcPhc0Inc1
%#function SP2_MARSS_ProcPhc0Inc2
%#function SP2_MARSS_ProcPhc0Inc3
%#function SP2_MARSS_ProcPhc0Reset
%#function SP2_MARSS_ProcPhc0Update
%#function SP2_MARSS_ProcPhc1Dec1
%#function SP2_MARSS_ProcPhc1Dec2
%#function SP2_MARSS_ProcPhc1Dec3
%#function SP2_MARSS_ProcPhc1FlagUpdate
%#function SP2_MARSS_ProcPhc1Inc1
%#function SP2_MARSS_ProcPhc1Inc2
%#function SP2_MARSS_ProcPhc1Inc3
%#function SP2_MARSS_ProcPhc1Reset
%#function SP2_MARSS_ProcPhc1Update
%#function SP2_MARSS_ProcScaleDec1
%#function SP2_MARSS_ProcScaleDec2
%#function SP2_MARSS_ProcScaleDec3
%#function SP2_MARSS_ProcScaleFlagUpdate
%#function SP2_MARSS_ProcScaleInc1
%#function SP2_MARSS_ProcScaleInc2
%#function SP2_MARSS_ProcScaleInc3
%#function SP2_MARSS_ProcScaleReset
%#function SP2_MARSS_ProcScaleUpdate
%#function SP2_MARSS_ProcShiftDec1
%#function SP2_MARSS_ProcShiftDec2
%#function SP2_MARSS_ProcShiftDec3
%#function SP2_MARSS_ProcShiftFlagUpdate
%#function SP2_MARSS_ProcShiftInc1
%#function SP2_MARSS_ProcShiftInc2
%#function SP2_MARSS_ProcShiftInc3
%#function SP2_MARSS_ProcShiftReset
%#function SP2_MARSS_ProcShiftUpdate
%#function SP2_MARSS_ProcZfDec1
%#function SP2_MARSS_ProcZfDec2
%#function SP2_MARSS_ProcZfDec3
%#function SP2_MARSS_ProcZfFlagUpdate
%#function SP2_MARSS_ProcZfInc1
%#function SP2_MARSS_ProcZfInc2
%#function SP2_MARSS_ProcZfInc3
%#function SP2_MARSS_ProcZfReset
%#function SP2_MARSS_ProcZfUpdate
%#function SP2_MARSS_ProcessFid
%#function SP2_MARSS_ProcessSpec
%#function SP2_MARSS_ResultFormatUpdate
%#function SP2_MARSS_SaveIndivMetabsFlagUpdate
%#function SP2_MARSS_SaveJpegFlagUpdate
%#function SP2_MARSS_SaveLogFlagUpdate
%#function SP2_MARSS_PRESSGETE30ms
%#function SP2_MARSS_PRESSPhilipsTE30ms
%#function SP2_MARSS_PRESSSiemensTE30ms
%#function SP2_MARSS_SLASERGE
%#function SP2_MARSS_SLASERSiemens
%#function SP2_MARSS_STEAMGETE20msTM10ms
%#function SP2_MARSS_STEAMPhilipsTE20msTM16ms
%#function SP2_MARSS_STEAMSiemensTE20msTM10ms
%#function SP2_MARSS_SequOriginUpdate
%#function SP2_MARSS_SequenceUpdate
%#function SP2_MARSS_ShowSelStrUpdate
%#function SP2_MARSS_ShowSelUpdate
%#function SP2_MARSS_SimCaseUpdate
%#function SP2_MARSS_SimParsDefAdopt
%#function SP2_MARSS_SimParsDefUpdate
%#function SP2_MARSS_SimParsLoadFromData
%#function SP2_MARSS_SimParsLoadFromLcm
%#function SP2_MARSS_SimParsLoadFromMrsi
%#function SP2_MARSS_SimParsLoadFromProc
%#function SP2_MARSS_SimParsLoadFromSim
%#function SP2_MARSS_SimParsUpdate
%#function SP2_MARSS_SpecSingleCurrDecr
%#function SP2_MARSS_SpecSingleCurrIncr
%#function SP2_MARSS_SpecSingleCurrUpdate
%#function SP2_MARSS_SpinSysAddAll
%#function SP2_MARSS_SpinSysAddSelected
%#function SP2_MARSS_SpinSysLibLoad
%#function SP2_MARSS_SpinSysLibPathUpdate
%#function SP2_MARSS_SpinSysLibSelect
%#function SP2_MARSS_VerboseFlagUpdate
%#function SP2_MM_2DShowAndDefine
%#function SP2_MM_2DShowSubtract
%#function SP2_MM_2DShowSum
%#function SP2_MM_AlignAmplExtraWinUpdate
%#function SP2_MM_AlignAmplParsUpdate
%#function SP2_MM_AlignAmplPpmStrUpdate
%#function SP2_MM_AlignAmplRef1StrUpdate
%#function SP2_MM_AlignAmplRef2StrUpdate
%#function SP2_MM_AlignAmplitudeUpdate
%#function SP2_MM_AlignDetailsExit
%#function SP2_MM_AlignDetailsMain
%#function SP2_MM_AlignDetailsWinUpdate
%#function SP2_MM_AlignFrequParsUpdate
%#function SP2_MM_AlignFrequPpmStrUpdate
%#function SP2_MM_AlignFrequencyUpdate
%#function SP2_MM_AlignPhModeCongruencyUpdate
%#function SP2_MM_AlignPhModeIntegralUpdate
%#function SP2_MM_AlignPhaseParsUpdate
%#function SP2_MM_AlignPhasePpmStrUpdate
%#function SP2_MM_AlignPhaseSpecRgOneUpdate
%#function SP2_MM_AlignPhaseSpecRgTwoUpdate
%#function SP2_MM_AlignPhaseUpdate
%#function SP2_MM_AmplShowAutoUpdate
%#function SP2_MM_AmplShowDirectUpdate
%#function SP2_MM_AnaFormatMagnUpdate
%#function SP2_MM_AnaFormatRealUpdate
%#function SP2_MM_AnaFrequDirectUpdate
%#function SP2_MM_AnaFrequglobalUpdate
%#function SP2_MM_AnaTOneModeFixedUpdate
%#function SP2_MM_AnaTOneModeFlexibleUpdate
%#function SP2_MM_AnaTOneStrUpdate
%#function SP2_MM_AutoFrequDet
%#function SP2_MM_AutoFrequDet_June2015
%#function SP2_MM_AutoPhaseDet
%#function SP2_MM_AutoPhaseDet_JUne2015
%#function SP2_MM_CalcFidArrRxComb
%#function SP2_MM_CalcFidArrSerial
%#function SP2_MM_ColormapHotUpdate
%#function SP2_MM_ColormapHsvUpdate
%#function SP2_MM_ColormapJetUpdate
%#function SP2_MM_ColormapLegendUpdate
%#function SP2_MM_ColormapUniUpdate
%#function SP2_MM_DataCorr
%#function SP2_MM_DataCorr_June2015
%#function SP2_MM_DataLoad
%#function SP2_MM_DataMetabUpdate
%#function SP2_MM_DataReco
%#function SP2_MM_DataRecoAll
%#function SP2_MM_DataRefUpdate
%#function SP2_MM_DataResort
%#function SP2_MM_DoSatEffAnalysis
%#function SP2_MM_DoSimulation
%#function SP2_MM_DoT1Analysis
%#function SP2_MM_DoT1Analysis_L1Norm
%#function SP2_MM_ExpFitAnalysis
%#function SP2_MM_ExpFitAnalysisFixed
%#function SP2_MM_ExpFitAnalysisFlexible
%#function SP2_MM_ExpPointSelectDecr
%#function SP2_MM_ExpPointSelectIncr
%#function SP2_MM_ExpPointSelectUpdate
%#function SP2_MM_ExpPointToPpmConversion
%#function SP2_MM_ExpPpmLinkFlagUpdate
%#function SP2_MM_ExpPpmSelectDecr
%#function SP2_MM_ExpPpmSelectIncr
%#function SP2_MM_ExpPpmSelectUpdate
%#function SP2_MM_ExpPpmToPointConversion
%#function SP2_MM_ExtractPpmRange
%#function SP2_MM_FunExp001_T1flex
%#function SP2_MM_FunExp002_T1flex
%#function SP2_MM_FunExp003_T1flex
%#function SP2_MM_FunExp005_T1fix
%#function SP2_MM_FunExp006_T1fix
%#function SP2_MM_FunExp006_T1flex
%#function SP2_MM_FunExp007_T1fix
%#function SP2_MM_FunExp008_T1fix
%#function SP2_MM_FunExp009_T1fix
%#function SP2_MM_FunExp010_T1fix
%#function SP2_MM_FunExp011_T1fix
%#function SP2_MM_FunExp012_T1fix
%#function SP2_MM_FunExp013_T1fix
%#function SP2_MM_FunExp014_T1fix
%#function SP2_MM_FunExp015_T1fix
%#function SP2_MM_FunExp020_T1fix
%#function SP2_MM_FunExp029_T1fix
%#function SP2_MM_FunExp030_T1fix
%#function SP2_MM_FunExp045_T1fix
%#function SP2_MM_FormatImagUpdate
%#function SP2_MM_FormatMagnUpdate
%#function SP2_MM_FormatPhaseUpdate
%#function SP2_MM_FormatRealUpdate
%#function SP2_MM_FunExp01
%#function SP2_MM_FunExp01_EffAna03
%#function SP2_MM_FunExp01_EffAna04
%#function SP2_MM_FunExp01_T1fix
%#function SP2_MM_FunExp01_T1fix_offset
%#function SP2_MM_FunExp01_full
%#function SP2_MM_FunExp01_offset
%#function SP2_MM_FunExp02
%#function SP2_MM_FunExp02_T1fix
%#function SP2_MM_FunExp02_T1fix_offset
%#function SP2_MM_FunExp02_full
%#function SP2_MM_FunExp02_offset
%#function SP2_MM_FunExp03
%#function SP2_MM_FunExp03_T1fix
%#function SP2_MM_FunExp03_T1fix_offset
%#function SP2_MM_FunExp03_full
%#function SP2_MM_FunExp03_offset
%#function SP2_MM_FunExp04
%#function SP2_MM_FunExp04_T1fix
%#function SP2_MM_FunExp04_T1fix_offset
%#function SP2_MM_FunExp04_full
%#function SP2_MM_FunExp04_offset
%#function SP2_MM_FunExp05
%#function SP2_MM_FunExp05_T1fix
%#function SP2_MM_FunExp05_T1fix_offset
%#function SP2_MM_FunExp05_full
%#function SP2_MM_FunExp05_offset
%#function SP2_MM_FunExp06
%#function SP2_MM_FunExp06_T1fix
%#function SP2_MM_FunExp06_T1fix_offset
%#function SP2_MM_FunExp06_offset
%#function SP2_MM_FunExp07
%#function SP2_MM_FunExp07_T1fix
%#function SP2_MM_FunExp07_T1fix_offset
%#function SP2_MM_FunExp07_offset
%#function SP2_MM_FunExp08
%#function SP2_MM_FunExp08_T1fix
%#function SP2_MM_FunExp08_T1fix_offset
%#function SP2_MM_FunExp08_offset
%#function SP2_MM_FunExp09
%#function SP2_MM_FunExp09_T1fix
%#function SP2_MM_FunExp09_T1fix_offset
%#function SP2_MM_FunExp09_offset
%#function SP2_MM_FunExp10
%#function SP2_MM_FunExp10_T1fix
%#function SP2_MM_FunExp10_T1fix_offset
%#function SP2_MM_FunExp10_offset
%#function SP2_MM_FunExp15_T1fix_offset
%#function SP2_MM_FunExp20_T1fix
%#function SP2_MM_FunExp20_T1fix_offset
%#function SP2_MM_FunExp30_T1fix_offset
%#function SP2_MM_FunExp40_T1fix_offset
%#function SP2_MM_FunExp50_T1fix_offset
%#function SP2_MM_FunExpT1fixCreateFile
%#function SP2_MM_FunExpT1flexCreateFile
%#function SP2_MM_MacroMain
%#function SP2_MM_MacroWinUpdate
%#function SP2_MM_CreateSatRecArray
%#function SP2_MM_DoMetabSimAll
%#function SP2_MM_DoMetabSimBrain
%#function SP2_MM_DoMetabSimulation
%#function SP2_MM_LoadParFile
%#function SP2_MM_SimDelayCreateLinear
%#function SP2_MM_SimDelayCreateLog
%#function SP2_MM_SimDelayStrUpdate
%#function SP2_MM_SimFidPathUpdate
%#function SP2_MM_SimFidSelect
%#function SP2_MM_SimNoiseUpdate
%#function SP2_MM_MmStructLoad
%#function SP2_MM_MmStructPathUpdate
%#function SP2_MM_MmStructSave
%#function SP2_MM_MmStructSelect
%#function SP2_MM_MmStructShow
%#function SP2_MM_NeighborInitUpdate
%#function SP2_MM_ParsUpdate
%#function SP2_MM_PpmShowDirectUpdate
%#function SP2_MM_PpmShowFullUpdate
%#function SP2_MM_PpmShowPosAssign
%#function SP2_MM_PpmShowPosFlagUpdate
%#function SP2_MM_PpmShowPosValUpdate
%#function SP2_MM_RecoZeroPhaseDec
%#function SP2_MM_RecoZeroPhaseInc
%#function SP2_MM_SatRecConsStrUpdate
%#function SP2_MM_SatRecSelectDecr
%#function SP2_MM_SatRecSelectIncr
%#function SP2_MM_SatRecSelectUpdate
%#function SP2_MM_SatRecShowFidSingle
%#function SP2_MM_SatRecShowSpecArray
%#function SP2_MM_SatRecShowSpecSingle
%#function SP2_MM_SatRecShowSpecSubtract
%#function SP2_MM_SatRecShowSpecSum
%#function SP2_MM_SatRecShowSpecSuper
%#function SP2_MM_T1ConsStrUpdate
%#function SP2_MM_T1SelectDecr
%#function SP2_MM_T1SelectIncr
%#function SP2_MM_T1SelectUpdate
%#function SP2_MM_T1ShowFidSingle
%#function SP2_MM_T1ShowSpec2D
%#function SP2_MM_T1ShowSpecArray
%#function SP2_MM_T1ShowSpecSingle
%#function SP2_MM_T1ShowSpecSubtract
%#function SP2_MM_T1ShowSpecSum
%#function SP2_MM_T1ShowSpecSum_L1norm
%#function SP2_MM_T1ShowSpecSuper
%#function SP2_MM_T1SplineFlagUpdate
%#function SP2_MRSI_AmplAutoUpdate
%#function SP2_MRSI_AmplCorr
%#function SP2_MRSI_AmplCorrFlagUpdate
%#function SP2_MRSI_AmplDirectUpdate
%#function SP2_MRSI_AmplWinMaxDecr
%#function SP2_MRSI_AmplWinMaxIncr
%#function SP2_MRSI_AmplWinMinDecr
%#function SP2_MRSI_AmplWinMinIncr
%#function SP2_MRSI_AmplWinUpdate
%#function SP2_MRSI_AnaBaseCorrUpdate
%#function SP2_MRSI_AnaFwhmUpdate
%#function SP2_MRSI_AnaIntegralUpdate
%#function SP2_MRSI_AnaSnrUpdate
%#function SP2_MRSI_Analysis
%#function SP2_MRSI_BaseMain
%#function SP2_MRSI_BaseWinUpdate
%#function SP2_MRSI_BaselineCorrInterp
%#function SP2_MRSI_BaselineCorrPoly
%#function SP2_MRSI_ExitBaseMain
%#function SP2_MRSI_InterpModeCubic
%#function SP2_MRSI_InterpModeLinear
%#function SP2_MRSI_InterpModeNearest
%#function SP2_MRSI_InterpModeSpline
%#function SP2_MRSI_InterpPpmStrUpdate
%#function SP2_MRSI_PolyOrderUpdate
%#function SP2_MRSI_PolyPpmStrUpdate
%#function SP2_MRSI_SvdPeakAnalysis
%#function SP2_MRSI_SvdPeakNumberUpdate
%#function SP2_MRSI_SvdPeakRemoval
%#function SP2_MRSI_SvdPhaseAndAmpFitFct
%#function SP2_MRSI_SvdPpmStrUpdate
%#function SP2_MRSI_SvdResultVisualization
%#function SP2_MRSI_BaselineCorrFlagUpdate
%#function SP2_MRSI_DataAndParsAssign1
%#function SP2_MRSI_DataAndParsAssign2
%#function SP2_MRSI_DataAndParsAssignRef
%#function SP2_MRSI_DataAssignExp1
%#function SP2_MRSI_DataAssignExp2
%#function SP2_MRSI_DataAssignRef
%#function SP2_MRSI_DataDataUpdate
%#function SP2_MRSI_DataFormatMatlabUpdate
%#function SP2_MRSI_DataFormatTextUpdate
%#function SP2_MRSI_DataMrsiUpdate
%#function SP2_MRSI_DoProcessing
%#function SP2_MRSI_ECCorr
%#function SP2_MRSI_ECCorrFlagUpdate
%#function SP2_MRSI_EccFlagUpdate
%#function SP2_MRSI_CreateHammingEncScheme
%#function SP2_MRSI_CreateRectAndCircEncScheme
%#function SP2_MRSI_ShowEncScheme
%#function SP2_MRSI_ExpLineBroadening
%#function SP2_MRSI_ExptDataMatUpdate
%#function SP2_MRSI_ExptDataPathUpdate
%#function SP2_MRSI_ExptDataSave
%#function SP2_MRSI_ExptDataSelect
%#function SP2_MRSI_ExptDataTxtUpdate
%#function SP2_MRSI_ExtractPpmRange
%#function SP2_MRSI_FigureUpdate
%#function SP2_MRSI_FormatImagUpdate
%#function SP2_MRSI_FormatList2Mat
%#function SP2_MRSI_FormatMagnUpdate
%#function SP2_MRSI_FormatPhaseUpdate
%#function SP2_MRSI_FormatRealUpdate
%#function SP2_MRSI_FreqCorr
%#function SP2_MRSI_FreqCorrFlagUpdate
%#function SP2_MRSI_FreqShift
%#function SP2_MRSI_GaussianLineBroadening
%#function SP2_MRSI_KeepFigureUpdate
%#function SP2_MRSI_MrsiAnalysis
%#function SP2_MRSI_MrsiMain
%#function SP2_MRSI_MrsiWinUpdate
%#function SP2_MRSI_NumSpecOneUpdate
%#function SP2_MRSI_NumSpecTwoUpdate
%#function SP2_MRSI_OffsetAssign
%#function SP2_MRSI_OffsetDec1
%#function SP2_MRSI_OffsetDec2
%#function SP2_MRSI_OffsetDec3
%#function SP2_MRSI_OffsetInc1
%#function SP2_MRSI_OffsetInc2
%#function SP2_MRSI_OffsetInc3
%#function SP2_MRSI_OffsetPpmWinFlagUpdate
%#function SP2_MRSI_OffsetPpmWinUpdate
%#function SP2_MRSI_OffsetValueFlagUpdate
%#function SP2_MRSI_OffsetValueUpdate
%#function SP2_MRSI_OffsetZero
%#function SP2_MRSI_PhaseCorr
%#function SP2_MRSI_PlotFid1
%#function SP2_MRSI_PlotFid1Orig
%#function SP2_MRSI_PlotFid2
%#function SP2_MRSI_PlotFid2Orig
%#function SP2_MRSI_PlotFidDiff
%#function SP2_MRSI_PlotFidFlagUpdate
%#function SP2_MRSI_PlotFidSum
%#function SP2_MRSI_PlotFidSuperpos
%#function SP2_MRSI_PlotSpec1
%#function SP2_MRSI_PlotSpec2
%#function SP2_MRSI_PlotSpecDiff
%#function SP2_MRSI_PlotSpecSum
%#function SP2_MRSI_PlotSpecSuperpos
%#function SP2_MRSI_PpmAssignToPeak
%#function SP2_MRSI_PpmAssignUpdate
%#function SP2_MRSI_PpmCalibUpdate
%#function SP2_MRSI_PpmNoiseMaxDecr
%#function SP2_MRSI_PpmNoiseMaxIncr
%#function SP2_MRSI_PpmNoiseMinDecr
%#function SP2_MRSI_PpmNoiseMinIncr
%#function SP2_MRSI_PpmNoiseWinUpdate
%#function SP2_MRSI_PpmOffsetMaxDecr
%#function SP2_MRSI_PpmOffsetMaxIncr
%#function SP2_MRSI_PpmOffsetMinDecr
%#function SP2_MRSI_PpmOffsetMinIncr
%#function SP2_MRSI_PpmShowDirectUpdate
%#function SP2_MRSI_PpmShowFullUpdate
%#function SP2_MRSI_PpmShowMaxDecr
%#function SP2_MRSI_PpmShowMaxIncr
%#function SP2_MRSI_PpmShowMinDecr
%#function SP2_MRSI_PpmShowMinIncr
%#function SP2_MRSI_PpmShowPosAssign
%#function SP2_MRSI_PpmShowPosFlagUpdate
%#function SP2_MRSI_PpmShowPosMirrorUpdate
%#function SP2_MRSI_PpmShowPosValUpdate
%#function SP2_MRSI_PpmShowWinUpdate
%#function SP2_MRSI_PpmTargetMaxDecr
%#function SP2_MRSI_PpmTargetMaxIncr
%#function SP2_MRSI_PpmTargetMinDecr
%#function SP2_MRSI_PpmTargetMinIncr
%#function SP2_MRSI_PpmTargetWinUpdate
%#function SP2_MRSI_ProcAndPlotFid1
%#function SP2_MRSI_ProcAndPlotFid1Orig
%#function SP2_MRSI_ProcAndPlotFid2
%#function SP2_MRSI_ProcAndPlotFid2Orig
%#function SP2_MRSI_ProcAndPlotFidDiff
%#function SP2_MRSI_ProcAndPlotFidSum
%#function SP2_MRSI_ProcAndPlotFidSuperpos
%#function SP2_MRSI_ProcAndPlotSpec1
%#function SP2_MRSI_ProcAndPlotSpec2
%#function SP2_MRSI_ProcAndPlotSpecDiff
%#function SP2_MRSI_ProcAndPlotSpecSum
%#function SP2_MRSI_ProcAndPlotSpecSuperpos
%#function SP2_MRSI_ProcAndPlotUpdate
%#function SP2_MRSI_ProcComplete
%#function SP2_MRSI_ProcData1
%#function SP2_MRSI_ProcData2
%#function SP2_MRSI_ProcSpecSumAndDiffOnly
%#function SP2_MRSI_ProcessFid1
%#function SP2_MRSI_ProcessFid2
%#function SP2_MRSI_ProcessMain
%#function SP2_MRSI_ProcessSpec1
%#function SP2_MRSI_ProcessSpec2
%#function SP2_MRSI_ProcessWinUpdate
%#function SP2_MRSI_RcvrCombination
%#function SP2_MRSI_RcvrProcInfo
%#function SP2_MRSI_ReadEncTableFromFile
%#function SP2_MRSI_RefDataLoadFromProc
%#function SP2_MRSI_SPECIAL
%#function SP2_MRSI_SelectLrDecr
%#function SP2_MRSI_SelectLrIncr
%#function SP2_MRSI_SelectLrUpdate
%#function SP2_MRSI_SelectPaDecr
%#function SP2_MRSI_SelectPaIncr
%#function SP2_MRSI_SelectPaUpdate
%#function SP2_MRSI_ShowFid1Img
%#function SP2_MRSI_ShowFid2Img
%#function SP2_MRSI_ShowFidDiffImg
%#function SP2_MRSI_ShowFidMrsi
%#function SP2_MRSI_ShowKSpaceEncode
%#function SP2_MRSI_ShowKSpaceMat
%#function SP2_MRSI_ShowSpec1Img
%#function SP2_MRSI_ShowSpec1Mrsi
%#function SP2_MRSI_ShowSpec2Img
%#function SP2_MRSI_ShowSpec2Mrsi
%#function SP2_MRSI_ShowSpecDiffImg
%#function SP2_MRSI_ShowSpecDiffMrsi
%#function SP2_MRSI_SpatFiltFlagUpdate
%#function SP2_MRSI_SpatZeroFillFlagUpdate
%#function SP2_MRSI_SpatZeroFillUpdate
%#function SP2_MRSI_SpatialAcqWeightRescale
%#function SP2_MRSI_SpatialFilter
%#function SP2_MRSI_SpatialFilterMatchRef2Metab
%#function SP2_MRSI_SpatialPhaseCorr
%#function SP2_MRSI_SpatialReco
%#function SP2_MRSI_SpatialZF
%#function SP2_MRSI_Spec1CutDec1
%#function SP2_MRSI_Spec1CutDec2
%#function SP2_MRSI_Spec1CutDec3
%#function SP2_MRSI_Spec1CutFlagUpdate
%#function SP2_MRSI_Spec1CutInc1
%#function SP2_MRSI_Spec1CutInc2
%#function SP2_MRSI_Spec1CutInc3
%#function SP2_MRSI_Spec1CutReset
%#function SP2_MRSI_Spec1CutUpdate
%#function SP2_MRSI_Spec1DataLoadFromProc
%#function SP2_MRSI_Spec1DataMatUpdate
%#function SP2_MRSI_Spec1DataPathUpdate
%#function SP2_MRSI_Spec1DataSelect
%#function SP2_MRSI_Spec1DataTxtUpdate
%#function SP2_MRSI_Spec1GbDec1
%#function SP2_MRSI_Spec1GbDec2
%#function SP2_MRSI_Spec1GbDec3
%#function SP2_MRSI_Spec1GbFlagUpdate
%#function SP2_MRSI_Spec1GbInc1
%#function SP2_MRSI_Spec1GbInc2
%#function SP2_MRSI_Spec1GbInc3
%#function SP2_MRSI_Spec1GbReset
%#function SP2_MRSI_Spec1GbUpdate
%#function SP2_MRSI_Spec1LbDec1
%#function SP2_MRSI_Spec1LbDec2
%#function SP2_MRSI_Spec1LbDec3
%#function SP2_MRSI_Spec1LbFlagUpdate
%#function SP2_MRSI_Spec1LbInc1
%#function SP2_MRSI_Spec1LbInc2
%#function SP2_MRSI_Spec1LbInc3
%#function SP2_MRSI_Spec1LbReset
%#function SP2_MRSI_Spec1LbUpdate
%#function SP2_MRSI_Spec1OffsetDec1
%#function SP2_MRSI_Spec1OffsetDec2
%#function SP2_MRSI_Spec1OffsetDec3
%#function SP2_MRSI_Spec1OffsetFlagUpdate
%#function SP2_MRSI_Spec1OffsetInc1
%#function SP2_MRSI_Spec1OffsetInc2
%#function SP2_MRSI_Spec1OffsetInc3
%#function SP2_MRSI_Spec1OffsetReset
%#function SP2_MRSI_Spec1OffsetUpdate
%#function SP2_MRSI_Spec1Phc0Dec1
%#function SP2_MRSI_Spec1Phc0Dec2
%#function SP2_MRSI_Spec1Phc0Dec3
%#function SP2_MRSI_Spec1Phc0FlagUpdate
%#function SP2_MRSI_Spec1Phc0Inc1
%#function SP2_MRSI_Spec1Phc0Inc2
%#function SP2_MRSI_Spec1Phc0Inc3
%#function SP2_MRSI_Spec1Phc0Reset
%#function SP2_MRSI_Spec1Phc0Update
%#function SP2_MRSI_Spec1Phc1Dec1
%#function SP2_MRSI_Spec1Phc1Dec2
%#function SP2_MRSI_Spec1Phc1Dec3
%#function SP2_MRSI_Spec1Phc1FlagUpdate
%#function SP2_MRSI_Spec1Phc1Inc1
%#function SP2_MRSI_Spec1Phc1Inc2
%#function SP2_MRSI_Spec1Phc1Inc3
%#function SP2_MRSI_Spec1Phc1Reset
%#function SP2_MRSI_Spec1Phc1Update
%#function SP2_MRSI_Spec1ScaleDec1
%#function SP2_MRSI_Spec1ScaleDec2
%#function SP2_MRSI_Spec1ScaleDec3
%#function SP2_MRSI_Spec1ScaleFlagUpdate
%#function SP2_MRSI_Spec1ScaleInc1
%#function SP2_MRSI_Spec1ScaleInc2
%#function SP2_MRSI_Spec1ScaleInc3
%#function SP2_MRSI_Spec1ScaleReset
%#function SP2_MRSI_Spec1ScaleUpdate
%#function SP2_MRSI_Spec1ShiftDec1
%#function SP2_MRSI_Spec1ShiftDec2
%#function SP2_MRSI_Spec1ShiftDec3
%#function SP2_MRSI_Spec1ShiftFlagUpdate
%#function SP2_MRSI_Spec1ShiftInc1
%#function SP2_MRSI_Spec1ShiftInc2
%#function SP2_MRSI_Spec1ShiftInc3
%#function SP2_MRSI_Spec1ShiftReset
%#function SP2_MRSI_Spec1ShiftUpdate
%#function SP2_MRSI_Spec1ZfDec1
%#function SP2_MRSI_Spec1ZfDec2
%#function SP2_MRSI_Spec1ZfDec3
%#function SP2_MRSI_Spec1ZfFlagUpdate
%#function SP2_MRSI_Spec1ZfInc1
%#function SP2_MRSI_Spec1ZfInc2
%#function SP2_MRSI_Spec1ZfInc3
%#function SP2_MRSI_Spec1ZfReset
%#function SP2_MRSI_Spec1ZfUpdate
%#function SP2_MRSI_Spec2CutDec1
%#function SP2_MRSI_Spec2CutDec2
%#function SP2_MRSI_Spec2CutDec3
%#function SP2_MRSI_Spec2CutFlagUpdate
%#function SP2_MRSI_Spec2CutInc1
%#function SP2_MRSI_Spec2CutInc2
%#function SP2_MRSI_Spec2CutInc3
%#function SP2_MRSI_Spec2CutReset
%#function SP2_MRSI_Spec2CutUpdate
%#function SP2_MRSI_Spec2DataLoadFromProc
%#function SP2_MRSI_Spec2DataMatUpdate
%#function SP2_MRSI_Spec2DataPathUpdate
%#function SP2_MRSI_Spec2DataSelect
%#function SP2_MRSI_Spec2DataTxtUpdate
%#function SP2_MRSI_Spec2GbDec1
%#function SP2_MRSI_Spec2GbDec2
%#function SP2_MRSI_Spec2GbDec3
%#function SP2_MRSI_Spec2GbFlagUpdate
%#function SP2_MRSI_Spec2GbInc1
%#function SP2_MRSI_Spec2GbInc2
%#function SP2_MRSI_Spec2GbInc3
%#function SP2_MRSI_Spec2GbReset
%#function SP2_MRSI_Spec2GbUpdate
%#function SP2_MRSI_Spec2LbDec1
%#function SP2_MRSI_Spec2LbDec2
%#function SP2_MRSI_Spec2LbDec3
%#function SP2_MRSI_Spec2LbFlagUpdate
%#function SP2_MRSI_Spec2LbInc1
%#function SP2_MRSI_Spec2LbInc2
%#function SP2_MRSI_Spec2LbInc3
%#function SP2_MRSI_Spec2LbReset
%#function SP2_MRSI_Spec2LbUpdate
%#function SP2_MRSI_Spec2OffsetDec1
%#function SP2_MRSI_Spec2OffsetDec2
%#function SP2_MRSI_Spec2OffsetDec3
%#function SP2_MRSI_Spec2OffsetFlagUpdate
%#function SP2_MRSI_Spec2OffsetInc1
%#function SP2_MRSI_Spec2OffsetInc2
%#function SP2_MRSI_Spec2OffsetInc3
%#function SP2_MRSI_Spec2OffsetReset
%#function SP2_MRSI_Spec2OffsetUpdate
%#function SP2_MRSI_Spec2Phc0Dec1
%#function SP2_MRSI_Spec2Phc0Dec2
%#function SP2_MRSI_Spec2Phc0Dec3
%#function SP2_MRSI_Spec2Phc0FlagUpdate
%#function SP2_MRSI_Spec2Phc0Inc1
%#function SP2_MRSI_Spec2Phc0Inc2
%#function SP2_MRSI_Spec2Phc0Inc3
%#function SP2_MRSI_Spec2Phc0Reset
%#function SP2_MRSI_Spec2Phc0Update
%#function SP2_MRSI_Spec2Phc1Dec1
%#function SP2_MRSI_Spec2Phc1Dec2
%#function SP2_MRSI_Spec2Phc1Dec3
%#function SP2_MRSI_Spec2Phc1FlagUpdate
%#function SP2_MRSI_Spec2Phc1Inc1
%#function SP2_MRSI_Spec2Phc1Inc2
%#function SP2_MRSI_Spec2Phc1Inc3
%#function SP2_MRSI_Spec2Phc1Reset
%#function SP2_MRSI_Spec2Phc1Update
%#function SP2_MRSI_Spec2ScaleDec1
%#function SP2_MRSI_Spec2ScaleDec2
%#function SP2_MRSI_Spec2ScaleDec3
%#function SP2_MRSI_Spec2ScaleFlagUpdate
%#function SP2_MRSI_Spec2ScaleInc1
%#function SP2_MRSI_Spec2ScaleInc2
%#function SP2_MRSI_Spec2ScaleInc3
%#function SP2_MRSI_Spec2ScaleReset
%#function SP2_MRSI_Spec2ScaleUpdate
%#function SP2_MRSI_Spec2ShiftDec1
%#function SP2_MRSI_Spec2ShiftDec2
%#function SP2_MRSI_Spec2ShiftDec3
%#function SP2_MRSI_Spec2ShiftFlagUpdate
%#function SP2_MRSI_Spec2ShiftInc1
%#function SP2_MRSI_Spec2ShiftInc2
%#function SP2_MRSI_Spec2ShiftInc3
%#function SP2_MRSI_Spec2ShiftReset
%#function SP2_MRSI_Spec2ShiftUpdate
%#function SP2_MRSI_Spec2ZfDec1
%#function SP2_MRSI_Spec2ZfDec2
%#function SP2_MRSI_Spec2ZfDec3
%#function SP2_MRSI_Spec2ZfFlagUpdate
%#function SP2_MRSI_Spec2ZfInc1
%#function SP2_MRSI_Spec2ZfInc2
%#function SP2_MRSI_Spec2ZfInc3
%#function SP2_MRSI_Spec2ZfReset
%#function SP2_MRSI_Spec2ZfUpdate
%#function SP2_MRSI_SpectralBaselineCorrPoly
%#function SP2_MRSI_SpectralBaselineCorrPolySingle
%#function SP2_MRSI_SpectralCut
%#function SP2_MRSI_SpectralECC
%#function SP2_MRSI_SpectralFft
%#function SP2_MRSI_SpectralFftMrsi
%#function SP2_MRSI_SpectralLB
%#function SP2_MRSI_SpectralPhaseCorr
%#function SP2_MRSI_SpectralZF
%#function SP2_MRSI_SyncCutFlagUpdate
%#function SP2_MRSI_SyncGbFlagUpdate
%#function SP2_MRSI_SyncLbFlagUpdate
%#function SP2_MRSI_SyncOffsetFlagUpdate
%#function SP2_MRSI_SyncPhc0FlagUpdate
%#function SP2_MRSI_SyncPhc1FlagUpdate
%#function SP2_MRSI_SyncScaleFlagUpdate
%#function SP2_MRSI_SyncShiftFlagUpdate
%#function SP2_MRSI_SyncZfFlagUpdate
%#function SP2_MRSI_UpdateCalcUpdate
%#function SP2_MRSI_VerboseFlagUpdate
%#function SP2_Man_ManualMain
%#function Original_SP2_Proc_Analysis
%#function SP2_Proc_AlignAmpWeightUpdate
%#function SP2_Proc_AlignGbFlagUpdate
%#function SP2_Proc_AlignLbFlagUpdate
%#function SP2_Proc_AlignMaxIterUpdate
%#function SP2_Proc_AlignOffsetFlagUpdate
%#function SP2_Proc_AlignPhc0FlagUpdate
%#function SP2_Proc_AlignPhc1FlagUpdate
%#function SP2_Proc_AlignPolyFlagUpdate
%#function SP2_Proc_AlignPolyOrderDec
%#function SP2_Proc_AlignPolyOrderInc
%#function SP2_Proc_AlignPolyOrderUpdate
%#function SP2_Proc_AlignPpmStrUpdate
%#function SP2_Proc_AlignScaleFlagUpdate
%#function SP2_Proc_AlignShiftFlagUpdate
%#function SP2_Proc_AlignSpec1
%#function SP2_Proc_AlignSpec1FitFct
%#function SP2_Proc_AlignSpec2
%#function SP2_Proc_AlignSpec2FitFct
%#function SP2_Proc_AlignStretchFlagUpdate
%#function SP2_Proc_AlignTolFunUpdate
%#function SP2_Proc_AmplAutoUpdate
%#function SP2_Proc_AmplCorr
%#function SP2_Proc_AmplCorrFlagUpdate
%#function SP2_Proc_AmplDirectUpdate
%#function SP2_Proc_AmplWinMaxDecr
%#function SP2_Proc_AmplWinMaxIncr
%#function SP2_Proc_AmplWinMinDecr
%#function SP2_Proc_AmplWinMinIncr
%#function SP2_Proc_AmplWinUpdate
%#function SP2_Proc_AnaAbsOfRealUpdate
%#function SP2_Proc_AnaBaseCorrUpdate
%#function SP2_Proc_AnaFrequDifference
%#function SP2_Proc_AnaFwhmUpdate
%#function SP2_Proc_AnaIntegralUpdate
%#function SP2_Proc_AnaSignNegativeUpdate
%#function SP2_Proc_AnaSignPositiveUpdate
%#function SP2_Proc_AnaSnrUpdate
%#function SP2_Proc_Analysis
%#function SP2_Proc_ApplyKloseCorr
%#function SP2_Proc_ApplyPoly1Update
%#function SP2_Proc_ApplyPoly2Update
%#function SP2_Proc_BaseMain
%#function SP2_Proc_BaseWinUpdate
%#function SP2_Proc_BaselineCorrInterp
%#function SP2_Proc_BaselineCorrPoly
%#function SP2_Proc_ExitBaseMain
%#function SP2_Proc_InterpModeCubic
%#function SP2_Proc_InterpModeLinear
%#function SP2_Proc_InterpModeNearest
%#function SP2_Proc_InterpModeSpline
%#function SP2_Proc_InterpPpmStrUpdate
%#function SP2_Proc_PolyOrderUpdate
%#function SP2_Proc_PolyPpmStrUpdate
%#function SP2_Proc_SvdPeakAnalysis
%#function SP2_Proc_SvdPeakNumberUpdate
%#function SP2_Proc_SvdPeakRemoval
%#function SP2_Proc_SvdPhaseAndAmpFitFct
%#function SP2_Proc_SvdPpmStrUpdate
%#function SP2_Proc_SvdResultVisualization
%#function SP2_Proc_Batch1Minus2
%#function SP2_Proc_CloseProcFigures
%#function SP2_Proc_ConvExtStrUpdate
%#function SP2_Proc_ConvertPar2Mat
%#function SP2_Proc_DataAndParsAssign1
%#function SP2_Proc_DataAndParsAssign2
%#function SP2_Proc_DataDataUpdate
%#function SP2_Proc_DataFormatMatlabUpdate
%#function SP2_Proc_DataFormatParMetabUpdate
%#function SP2_Proc_DataFormatTextUpdate
%#function SP2_Proc_DataFormatUpdate
%#function SP2_Proc_DataLcmUpdate
%#function SP2_Proc_DataMarssUpdate
%#function SP2_Proc_DataMrsiUpdate
%#function SP2_Proc_DataProcUpdate
%#function SP2_Proc_DataSynUpdate
%#function SP2_Proc_DoProcessing
%#function SP2_Proc_ECCorr
%#function SP2_Proc_ECCorrFlagUpdate
%#function SP2_Proc_ExpLineBroadening
%#function SP2_Proc_ExptDataMatUpdate
%#function SP2_Proc_ExptDataPathUpdate
%#function SP2_Proc_ExptDataRawUpdate
%#function SP2_Proc_ExptDataSave
%#function SP2_Proc_ExptDataSelect
%#function SP2_Proc_ExptDataTxtUpdate
%#function SP2_Proc_ExtractPpmRange
%#function SP2_Proc_FigureUpdate
%#function SP2_Proc_FormatImagUpdate
%#function SP2_Proc_FormatMagnUpdate
%#function SP2_Proc_FormatPhaseUpdate
%#function SP2_Proc_FormatRealUpdate
%#function SP2_Proc_FreqCorr
%#function SP2_Proc_FreqCorrFlagUpdate
%#function SP2_Proc_FreqShift
%#function SP2_Proc_GaussianLineBroadening
%#function SP2_Proc_JdeEffAnalysis
%#function SP2_Proc_JdeEffOffsetAssign
%#function SP2_Proc_JdeEfficiencyMain
%#function SP2_Proc_JdeEfficiencyParsUpdate
%#function SP2_Proc_JdeEfficiencyWinUpdate
%#function SP2_Proc_JmruiReadFid
%#function SP2_Proc_KeepFigureUpdate
%#function SP2_Proc_LcmSetHeader
%#function SP2_Proc_LcmWritePars
%#function SP2_Proc_LcmWriteRaw
%#function SP2_Proc_NumSpecOneUpdate
%#function SP2_Proc_NumSpecTwoUpdate
%#function SP2_Proc_OffsetAssign
%#function SP2_Proc_OffsetDec1
%#function SP2_Proc_OffsetDec2
%#function SP2_Proc_OffsetDec3
%#function SP2_Proc_OffsetInc1
%#function SP2_Proc_OffsetInc2
%#function SP2_Proc_OffsetInc3
%#function SP2_Proc_OffsetPpmWinFlagUpdate
%#function SP2_Proc_OffsetPpmWinUpdate
%#function SP2_Proc_OffsetValueFlagUpdate
%#function SP2_Proc_OffsetValueUpdate
%#function SP2_Proc_OffsetZero
%#function SP2_Proc_PhaseCorr
%#function SP2_Proc_PlcmFormatCoord
%#function SP2_Proc_PlcmReadCoord
%#function SP2_Proc_PlotFid1
%#function SP2_Proc_PlotFid1Orig
%#function SP2_Proc_PlotFid2
%#function SP2_Proc_PlotFid2Orig
%#function SP2_Proc_PlotFidDiff
%#function SP2_Proc_PlotFidFlagUpdate
%#function SP2_Proc_PlotFidSum
%#function SP2_Proc_PlotFidSuperpos
%#function SP2_Proc_PlotSpec1
%#function SP2_Proc_PlotSpec2
%#function SP2_Proc_PlotSpecDiff
%#function SP2_Proc_PlotSpecSum
%#function SP2_Proc_PlotSpecSuperpos
%#function SP2_Proc_PpmAssignToPeak
%#function SP2_Proc_PpmAssignToPeakZoom
%#function SP2_Proc_PpmAssignToPeak_2014
%#function SP2_Proc_PpmAssignUpdate
%#function SP2_Proc_PpmCalibUpdate
%#function SP2_Proc_PpmNoiseMaxDecr
%#function SP2_Proc_PpmNoiseMaxIncr
%#function SP2_Proc_PpmNoiseMinDecr
%#function SP2_Proc_PpmNoiseMinIncr
%#function SP2_Proc_PpmNoiseWinUpdate
%#function SP2_Proc_PpmOffsetMaxDecr
%#function SP2_Proc_PpmOffsetMaxIncr
%#function SP2_Proc_PpmOffsetMinDecr
%#function SP2_Proc_PpmOffsetMinIncr
%#function SP2_Proc_PpmShowDirectUpdate
%#function SP2_Proc_PpmShowFullUpdate
%#function SP2_Proc_PpmShowMaxDecr
%#function SP2_Proc_PpmShowMaxIncr
%#function SP2_Proc_PpmShowMinDecr
%#function SP2_Proc_PpmShowMinIncr
%#function SP2_Proc_PpmShowPosAssign
%#function SP2_Proc_PpmShowPosFlagUpdate
%#function SP2_Proc_PpmShowPosMirrorUpdate
%#function SP2_Proc_PpmShowPosValUpdate
%#function SP2_Proc_PpmShowWinUpdate
%#function SP2_Proc_PpmTargetMaxDecr
%#function SP2_Proc_PpmTargetMaxIncr
%#function SP2_Proc_PpmTargetMinDecr
%#function SP2_Proc_PpmTargetMinIncr
%#function SP2_Proc_PpmTargetWinUpdate
%#function SP2_Proc_ProcAndPlotFid1
%#function SP2_Proc_ProcAndPlotFid1Orig
%#function SP2_Proc_ProcAndPlotFid2
%#function SP2_Proc_ProcAndPlotFid2Orig
%#function SP2_Proc_ProcAndPlotFidDiff
%#function SP2_Proc_ProcAndPlotFidSum
%#function SP2_Proc_ProcAndPlotFidSuperpos
%#function SP2_Proc_ProcAndPlotSpec1
%#function SP2_Proc_ProcAndPlotSpec2
%#function SP2_Proc_ProcAndPlotSpecDiff
%#function SP2_Proc_ProcAndPlotSpecSum
%#function SP2_Proc_ProcAndPlotSpecSuperpos
%#function SP2_Proc_ProcAndPlotUpdate
%#function SP2_Proc_ProcComplete
%#function SP2_Proc_ProcData1
%#function SP2_Proc_ProcData2
%#function SP2_Proc_ProcSpecSumAndDiffOnly
%#function SP2_Proc_ProcessFid1
%#function SP2_Proc_ProcessFid2
%#function SP2_Proc_ProcessMain
%#function SP2_Proc_ProcessSpec1
%#function SP2_Proc_ProcessSpec2
%#function SP2_Proc_ProcessWinUpdate
%#function SP2_Proc_SPECIAL
%#function SP2_Proc_Spec1CutDec1
%#function SP2_Proc_Spec1CutDec2
%#function SP2_Proc_Spec1CutDec3
%#function SP2_Proc_Spec1CutFlagUpdate
%#function SP2_Proc_Spec1CutInc1
%#function SP2_Proc_Spec1CutInc2
%#function SP2_Proc_Spec1CutInc3
%#function SP2_Proc_Spec1CutReset
%#function SP2_Proc_Spec1CutUpdate
%#function SP2_Proc_Spec1DataCoordUpdate
%#function SP2_Proc_Spec1DataLoadFromData
%#function SP2_Proc_Spec1DataLoadFromLcm
%#function SP2_Proc_Spec1DataLoadFromMarss
%#function SP2_Proc_Spec1DataLoadFromMrsi
%#function SP2_Proc_Spec1DataLoadFromProc
%#function SP2_Proc_Spec1DataLoadFromSyn
%#function SP2_Proc_Spec1DataMatUpdate
%#function SP2_Proc_Spec1DataParUpdate
%#function SP2_Proc_Spec1DataPathUpdate
%#function SP2_Proc_Spec1DataRawUpdate
%#function SP2_Proc_Spec1DataSelect
%#function SP2_Proc_Spec1DataTxtUpdate
%#function SP2_Proc_Spec1GbDec1
%#function SP2_Proc_Spec1GbDec2
%#function SP2_Proc_Spec1GbDec3
%#function SP2_Proc_Spec1GbFlagUpdate
%#function SP2_Proc_Spec1GbInc1
%#function SP2_Proc_Spec1GbInc2
%#function SP2_Proc_Spec1GbInc3
%#function SP2_Proc_Spec1GbReset
%#function SP2_Proc_Spec1GbUpdate
%#function SP2_Proc_Spec1LbDec1
%#function SP2_Proc_Spec1LbDec2
%#function SP2_Proc_Spec1LbDec3
%#function SP2_Proc_Spec1LbFlagUpdate
%#function SP2_Proc_Spec1LbInc1
%#function SP2_Proc_Spec1LbInc2
%#function SP2_Proc_Spec1LbInc3
%#function SP2_Proc_Spec1LbReset
%#function SP2_Proc_Spec1LbUpdate
%#function SP2_Proc_Spec1OffsetDec1
%#function SP2_Proc_Spec1OffsetDec2
%#function SP2_Proc_Spec1OffsetDec3
%#function SP2_Proc_Spec1OffsetFlagUpdate
%#function SP2_Proc_Spec1OffsetInc1
%#function SP2_Proc_Spec1OffsetInc2
%#function SP2_Proc_Spec1OffsetInc3
%#function SP2_Proc_Spec1OffsetReset
%#function SP2_Proc_Spec1OffsetUpdate
%#function SP2_Proc_Spec1ParsDialogExit
%#function SP2_Proc_Spec1ParsDialogMain
%#function SP2_Proc_Spec1ParsNspeccUpdate
%#function SP2_Proc_Spec1ParsSfUpdate
%#function SP2_Proc_Spec1ParsSwhUpdate
%#function SP2_Proc_Spec1Phc0Dec1
%#function SP2_Proc_Spec1Phc0Dec2
%#function SP2_Proc_Spec1Phc0Dec3
%#function SP2_Proc_Spec1Phc0FlagUpdate
%#function SP2_Proc_Spec1Phc0Inc1
%#function SP2_Proc_Spec1Phc0Inc2
%#function SP2_Proc_Spec1Phc0Inc3
%#function SP2_Proc_Spec1Phc0Reset
%#function SP2_Proc_Spec1Phc0Update
%#function SP2_Proc_Spec1Phc1Dec1
%#function SP2_Proc_Spec1Phc1Dec2
%#function SP2_Proc_Spec1Phc1Dec3
%#function SP2_Proc_Spec1Phc1FlagUpdate
%#function SP2_Proc_Spec1Phc1Inc1
%#function SP2_Proc_Spec1Phc1Inc2
%#function SP2_Proc_Spec1Phc1Inc3
%#function SP2_Proc_Spec1Phc1Reset
%#function SP2_Proc_Spec1Phc1Update
%#function SP2_Proc_Spec1ScaleDec1
%#function SP2_Proc_Spec1ScaleDec2
%#function SP2_Proc_Spec1ScaleDec3
%#function SP2_Proc_Spec1ScaleFlagUpdate
%#function SP2_Proc_Spec1ScaleInc1
%#function SP2_Proc_Spec1ScaleInc2
%#function SP2_Proc_Spec1ScaleInc3
%#function SP2_Proc_Spec1ScaleReset
%#function SP2_Proc_Spec1ScaleUpdate
%#function SP2_Proc_Spec1ShiftDec1
%#function SP2_Proc_Spec1ShiftDec2
%#function SP2_Proc_Spec1ShiftDec3
%#function SP2_Proc_Spec1ShiftFlagUpdate
%#function SP2_Proc_Spec1ShiftInc1
%#function SP2_Proc_Spec1ShiftInc2
%#function SP2_Proc_Spec1ShiftInc3
%#function SP2_Proc_Spec1ShiftReset
%#function SP2_Proc_Spec1ShiftUpdate
%#function SP2_Proc_Spec1StretchDec1
%#function SP2_Proc_Spec1StretchDec2
%#function SP2_Proc_Spec1StretchDec3
%#function SP2_Proc_Spec1StretchFlagUpdate
%#function SP2_Proc_Spec1StretchInc1
%#function SP2_Proc_Spec1StretchInc2
%#function SP2_Proc_Spec1StretchInc3
%#function SP2_Proc_Spec1StretchReset
%#function SP2_Proc_Spec1StretchUpdate
%#function SP2_Proc_Spec1ZfDec1
%#function SP2_Proc_Spec1ZfDec2
%#function SP2_Proc_Spec1ZfDec3
%#function SP2_Proc_Spec1ZfFlagUpdate
%#function SP2_Proc_Spec1ZfInc1
%#function SP2_Proc_Spec1ZfInc2
%#function SP2_Proc_Spec1ZfInc3
%#function SP2_Proc_Spec1ZfReset
%#function SP2_Proc_Spec1ZfUpdate
%#function SP2_Proc_Spec2Align
%#function SP2_Proc_Spec2CutDec1
%#function SP2_Proc_Spec2CutDec2
%#function SP2_Proc_Spec2CutDec3
%#function SP2_Proc_Spec2CutFlagUpdate
%#function SP2_Proc_Spec2CutInc1
%#function SP2_Proc_Spec2CutInc2
%#function SP2_Proc_Spec2CutInc3
%#function SP2_Proc_Spec2CutReset
%#function SP2_Proc_Spec2CutUpdate
%#function SP2_Proc_Spec2DataCoordUpdate
%#function SP2_Proc_Spec2DataLoadFromData
%#function SP2_Proc_Spec2DataLoadFromLcm
%#function SP2_Proc_Spec2DataLoadFromMarss
%#function SP2_Proc_Spec2DataLoadFromMrsi
%#function SP2_Proc_Spec2DataLoadFromProc
%#function SP2_Proc_Spec2DataLoadFromSim
%#function SP2_Proc_Spec2DataLoadFromSyn
%#function SP2_Proc_Spec2DataMatUpdate
%#function SP2_Proc_Spec2DataParUpdate
%#function SP2_Proc_Spec2DataPathUpdate
%#function SP2_Proc_Spec2DataRawUpdate
%#function SP2_Proc_Spec2DataSelect
%#function SP2_Proc_Spec2DataTxtUpdate
%#function SP2_Proc_Spec2GbDec1
%#function SP2_Proc_Spec2GbDec2
%#function SP2_Proc_Spec2GbDec3
%#function SP2_Proc_Spec2GbFlagUpdate
%#function SP2_Proc_Spec2GbInc1
%#function SP2_Proc_Spec2GbInc2
%#function SP2_Proc_Spec2GbInc3
%#function SP2_Proc_Spec2GbReset
%#function SP2_Proc_Spec2GbUpdate
%#function SP2_Proc_Spec2LbDec1
%#function SP2_Proc_Spec2LbDec2
%#function SP2_Proc_Spec2LbDec3
%#function SP2_Proc_Spec2LbFlagUpdate
%#function SP2_Proc_Spec2LbInc1
%#function SP2_Proc_Spec2LbInc2
%#function SP2_Proc_Spec2LbInc3
%#function SP2_Proc_Spec2LbReset
%#function SP2_Proc_Spec2LbUpdate
%#function SP2_Proc_Spec2OffsetDec1
%#function SP2_Proc_Spec2OffsetDec2
%#function SP2_Proc_Spec2OffsetDec3
%#function SP2_Proc_Spec2OffsetFlagUpdate
%#function SP2_Proc_Spec2OffsetInc1
%#function SP2_Proc_Spec2OffsetInc2
%#function SP2_Proc_Spec2OffsetInc3
%#function SP2_Proc_Spec2OffsetReset
%#function SP2_Proc_Spec2OffsetUpdate
%#function SP2_Proc_Spec2ParsDialogExit
%#function SP2_Proc_Spec2ParsDialogMain
%#function SP2_Proc_Spec2ParsNspeccUpdate
%#function SP2_Proc_Spec2ParsSfUpdate
%#function SP2_Proc_Spec2ParsSwhUpdate
%#function SP2_Proc_Spec2Phc0Dec1
%#function SP2_Proc_Spec2Phc0Dec2
%#function SP2_Proc_Spec2Phc0Dec3
%#function SP2_Proc_Spec2Phc0FlagUpdate
%#function SP2_Proc_Spec2Phc0Inc1
%#function SP2_Proc_Spec2Phc0Inc2
%#function SP2_Proc_Spec2Phc0Inc3
%#function SP2_Proc_Spec2Phc0Reset
%#function SP2_Proc_Spec2Phc0Update
%#function SP2_Proc_Spec2Phc1Dec1
%#function SP2_Proc_Spec2Phc1Dec2
%#function SP2_Proc_Spec2Phc1Dec3
%#function SP2_Proc_Spec2Phc1FlagUpdate
%#function SP2_Proc_Spec2Phc1Inc1
%#function SP2_Proc_Spec2Phc1Inc2
%#function SP2_Proc_Spec2Phc1Inc3
%#function SP2_Proc_Spec2Phc1Reset
%#function SP2_Proc_Spec2Phc1Update
%#function SP2_Proc_Spec2ScaleDec1
%#function SP2_Proc_Spec2ScaleDec2
%#function SP2_Proc_Spec2ScaleDec3
%#function SP2_Proc_Spec2ScaleFlagUpdate
%#function SP2_Proc_Spec2ScaleInc1
%#function SP2_Proc_Spec2ScaleInc2
%#function SP2_Proc_Spec2ScaleInc3
%#function SP2_Proc_Spec2ScaleReset
%#function SP2_Proc_Spec2ScaleUpdate
%#function SP2_Proc_Spec2ShiftDec1
%#function SP2_Proc_Spec2ShiftDec2
%#function SP2_Proc_Spec2ShiftDec3
%#function SP2_Proc_Spec2ShiftFlagUpdate
%#function SP2_Proc_Spec2ShiftInc1
%#function SP2_Proc_Spec2ShiftInc2
%#function SP2_Proc_Spec2ShiftInc3
%#function SP2_Proc_Spec2ShiftReset
%#function SP2_Proc_Spec2ShiftUpdate
%#function SP2_Proc_Spec2StretchDec1
%#function SP2_Proc_Spec2StretchDec2
%#function SP2_Proc_Spec2StretchDec3
%#function SP2_Proc_Spec2StretchFlagUpdate
%#function SP2_Proc_Spec2StretchInc1
%#function SP2_Proc_Spec2StretchInc2
%#function SP2_Proc_Spec2StretchInc3
%#function SP2_Proc_Spec2StretchReset
%#function SP2_Proc_Spec2StretchUpdate
%#function SP2_Proc_Spec2ZfDec1
%#function SP2_Proc_Spec2ZfDec2
%#function SP2_Proc_Spec2ZfDec3
%#function SP2_Proc_Spec2ZfFlagUpdate
%#function SP2_Proc_Spec2ZfInc1
%#function SP2_Proc_Spec2ZfInc2
%#function SP2_Proc_Spec2ZfInc3
%#function SP2_Proc_Spec2ZfReset
%#function SP2_Proc_Spec2ZfUpdate
%#function SP2_Proc_SpectralFft
%#function SP2_Proc_SyncCutFlagUpdate
%#function SP2_Proc_SyncGbFlagUpdate
%#function SP2_Proc_SyncLbFlagUpdate
%#function SP2_Proc_SyncOffsetFlagUpdate
%#function SP2_Proc_SyncPhc0FlagUpdate
%#function SP2_Proc_SyncPhc1FlagUpdate
%#function SP2_Proc_SyncScaleFlagUpdate
%#function SP2_Proc_SyncShiftFlagUpdate
%#function SP2_Proc_SyncStretchFlagUpdate
%#function SP2_Proc_SyncZfFlagUpdate
%#function SP2_Proc_UpdateCalcUpdate
%#function SP2_Proc_VerboseFlagUpdate
%#function SP2_Stab_BinAllUpdate
%#function SP2_Stab_BinSelectUpdate
%#function SP2_Stab_DataAssignment
%#function SP2_Stab_DoBinMaxFFT
%#function SP2_Stab_DoNoiseAnalysis
%#function SP2_Stab_DoNoiseAnalysis_tmp
%#function SP2_Stab_DoSignalAnalysis
%#function SP2_Stab_ExtractPpmRange
%#function SP2_Stab_PhaseZeroUpdate
%#function SP2_Stab_PpmBinSelectUpdate
%#function SP2_Stab_PpmBinsUpdate
%#function SP2_Stab_PpmCalibUpdate
%#function SP2_Stab_RcvrNumDecrease
%#function SP2_Stab_RcvrNumIncrease
%#function SP2_Stab_RcvrNumUpdate
%#function SP2_Stab_SpecFirstUpdate
%#function SP2_Stab_SpecLastUpdate
%#function SP2_Stab_SpecMagnUpdate
%#function SP2_Stab_SpecRealUpdate
%#function SP2_Stab_SpecSelectUpdate
%#function SP2_Stab_StabilityAnalysis
%#function SP2_Stab_StabilityMain
%#function SP2_Stab_StabilityWinUpdate
%#function SP2_Stab_TotalAllUpdate
%#function SP2_Stab_TotalSelectUpdate
%#function SP2_Stab_TransmitNumDecrease
%#function SP2_Stab_TransmitNumIncrease
%#function SP2_Stab_TransmitNumUpdate
%#function Original_SP2_Syn_Analysis
%#function SP2_Syn_AmplShowAutoUpdate
%#function SP2_Syn_AmplShowDirectUpdate
%#function SP2_Syn_AmplWinMaxDecr
%#function SP2_Syn_AmplWinMaxIncr
%#function SP2_Syn_AmplWinMinDecr
%#function SP2_Syn_AmplWinMinIncr
%#function SP2_Syn_AmplWinUpdate
%#function SP2_Syn_AnaFrequDifference
%#function SP2_Syn_AnaFwhmUpdate
%#function SP2_Syn_AnaIntegralUpdate
%#function SP2_Syn_AnaSignNegativeUpdate
%#function SP2_Syn_AnaSignPositiveUpdate
%#function SP2_Syn_AnaSnrUpdate
%#function SP2_Syn_Analysis
%#function SP2_Syn_BaseAmpUpdate
%#function SP2_Syn_BaseUpdate
%#function SP2_Syn_ColormapHotUpdate
%#function SP2_Syn_ColormapHsvUpdate
%#function SP2_Syn_ColormapJetUpdate
%#function SP2_Syn_ColormapUniUpdate
%#function SP2_Syn_CreateSatRecArray
%#function SP2_Syn_DoLoadLCM
%#function SP2_Syn_DoLoadProc
%#function SP2_Syn_DoSimMetabBrain
%#function SP2_Syn_DoSimMetabSingle
%#function SP2_Syn_DoSimNoise
%#function SP2_Syn_DoSimSinglets
%#function SP2_Syn_ExtractPpmRange
%#function SP2_Syn_FigureUpdate
%#function SP2_Syn_FormatImagUpdate
%#function SP2_Syn_FormatMagnUpdate
%#function SP2_Syn_FormatPhaseUpdate
%#function SP2_Syn_FormatRealUpdate
%#function SP2_Syn_KeepFigureUpdate
%#function SP2_Syn_LoadMatFile
%#function SP2_Syn_LoadParFile
%#function SP2_Syn_LoadRawFile
%#function SP2_Syn_MetabCharStrUpdate
%#function SP2_Syn_MetabFidPathUpdate
%#function SP2_Syn_MetabFidSelect
%#function SP2_Syn_NoiseAmpUpdate
%#function SP2_Syn_NoiseKeepUpdate
%#function SP2_Syn_NoiseUpdate
%#function SP2_Syn_OffsetAssign
%#function SP2_Syn_OffsetDec1
%#function SP2_Syn_OffsetDec2
%#function SP2_Syn_OffsetDec3
%#function SP2_Syn_OffsetInc1
%#function SP2_Syn_OffsetInc2
%#function SP2_Syn_OffsetInc3
%#function SP2_Syn_OffsetPpmWinFlagUpdate
%#function SP2_Syn_OffsetPpmWinUpdate
%#function SP2_Syn_OffsetValueFlagUpdate
%#function SP2_Syn_OffsetValueUpdate
%#function SP2_Syn_OffsetZero
%#function SP2_Syn_ParsUpdate
%#function SP2_Syn_PlotFid
%#function SP2_Syn_PlotFidOrig
%#function SP2_Syn_PlotSpec
%#function SP2_Syn_PolyAmpUpdate
%#function SP2_Syn_PolyCenterPpmUpdate
%#function SP2_Syn_PolyUpdate
%#function SP2_Syn_PpmCalibUpdate
%#function SP2_Syn_PpmNoiseMaxDecr
%#function SP2_Syn_PpmNoiseMaxIncr
%#function SP2_Syn_PpmNoiseMinDecr
%#function SP2_Syn_PpmNoiseMinIncr
%#function SP2_Syn_PpmNoiseWinUpdate
%#function SP2_Syn_PpmOffsetMaxDecr
%#function SP2_Syn_PpmOffsetMaxIncr
%#function SP2_Syn_PpmOffsetMinDecr
%#function SP2_Syn_PpmOffsetMinIncr
%#function SP2_Syn_PpmShowDirectUpdate
%#function SP2_Syn_PpmShowFullUpdate
%#function SP2_Syn_PpmShowMaxDecr
%#function SP2_Syn_PpmShowMaxIncr
%#function SP2_Syn_PpmShowMinDecr
%#function SP2_Syn_PpmShowMinIncr
%#function SP2_Syn_PpmShowPosAssign
%#function SP2_Syn_PpmShowPosFlagUpdate
%#function SP2_Syn_PpmShowPosValUpdate
%#function SP2_Syn_PpmTargetMaxDecr
%#function SP2_Syn_PpmTargetMaxIncr
%#function SP2_Syn_PpmTargetMinDecr
%#function SP2_Syn_PpmTargetMinIncr
%#function SP2_Syn_PpmTargetWinUpdate
%#function SP2_Syn_ProcAndPlotFid
%#function SP2_Syn_ProcAndPlotFidOrig
%#function SP2_Syn_ProcAndPlotSpec
%#function SP2_Syn_ProcAndPlotUpdate
%#function SP2_Syn_ProcCutDec1
%#function SP2_Syn_ProcCutDec2
%#function SP2_Syn_ProcCutDec3
%#function SP2_Syn_ProcCutFlagUpdate
%#function SP2_Syn_ProcCutInc1
%#function SP2_Syn_ProcCutInc2
%#function SP2_Syn_ProcCutInc3
%#function SP2_Syn_ProcCutReset
%#function SP2_Syn_ProcCutUpdate
%#function SP2_Syn_ProcData
%#function SP2_Syn_ProcGbDec1
%#function SP2_Syn_ProcGbDec2
%#function SP2_Syn_ProcGbDec3
%#function SP2_Syn_ProcGbFlagUpdate
%#function SP2_Syn_ProcGbInc1
%#function SP2_Syn_ProcGbInc2
%#function SP2_Syn_ProcGbInc3
%#function SP2_Syn_ProcGbReset
%#function SP2_Syn_ProcGbUpdate
%#function SP2_Syn_ProcLbDec1
%#function SP2_Syn_ProcLbDec2
%#function SP2_Syn_ProcLbDec3
%#function SP2_Syn_ProcLbFlagUpdate
%#function SP2_Syn_ProcLbInc1
%#function SP2_Syn_ProcLbInc2
%#function SP2_Syn_ProcLbInc3
%#function SP2_Syn_ProcLbReset
%#function SP2_Syn_ProcLbUpdate
%#function SP2_Syn_ProcOffsetDec1
%#function SP2_Syn_ProcOffsetDec2
%#function SP2_Syn_ProcOffsetDec3
%#function SP2_Syn_ProcOffsetFlagUpdate
%#function SP2_Syn_ProcOffsetInc1
%#function SP2_Syn_ProcOffsetInc2
%#function SP2_Syn_ProcOffsetInc3
%#function SP2_Syn_ProcOffsetReset
%#function SP2_Syn_ProcOffsetUpdate
%#function SP2_Syn_ProcPhc0Dec1
%#function SP2_Syn_ProcPhc0Dec2
%#function SP2_Syn_ProcPhc0Dec3
%#function SP2_Syn_ProcPhc0FlagUpdate
%#function SP2_Syn_ProcPhc0Inc1
%#function SP2_Syn_ProcPhc0Inc2
%#function SP2_Syn_ProcPhc0Inc3
%#function SP2_Syn_ProcPhc0Reset
%#function SP2_Syn_ProcPhc0Update
%#function SP2_Syn_ProcPhc1Dec1
%#function SP2_Syn_ProcPhc1Dec2
%#function SP2_Syn_ProcPhc1Dec3
%#function SP2_Syn_ProcPhc1FlagUpdate
%#function SP2_Syn_ProcPhc1Inc1
%#function SP2_Syn_ProcPhc1Inc2
%#function SP2_Syn_ProcPhc1Inc3
%#function SP2_Syn_ProcPhc1Reset
%#function SP2_Syn_ProcPhc1Update
%#function SP2_Syn_ProcScaleDec1
%#function SP2_Syn_ProcScaleDec2
%#function SP2_Syn_ProcScaleDec3
%#function SP2_Syn_ProcScaleFlagUpdate
%#function SP2_Syn_ProcScaleInc1
%#function SP2_Syn_ProcScaleInc2
%#function SP2_Syn_ProcScaleInc3
%#function SP2_Syn_ProcScaleReset
%#function SP2_Syn_ProcScaleUpdate
%#function SP2_Syn_ProcShiftDec1
%#function SP2_Syn_ProcShiftDec2
%#function SP2_Syn_ProcShiftDec3
%#function SP2_Syn_ProcShiftFlagUpdate
%#function SP2_Syn_ProcShiftInc1
%#function SP2_Syn_ProcShiftInc2
%#function SP2_Syn_ProcShiftInc3
%#function SP2_Syn_ProcShiftReset
%#function SP2_Syn_ProcShiftUpdate
%#function SP2_Syn_ProcZfDec1
%#function SP2_Syn_ProcZfDec2
%#function SP2_Syn_ProcZfDec3
%#function SP2_Syn_ProcZfFlagUpdate
%#function SP2_Syn_ProcZfInc1
%#function SP2_Syn_ProcZfInc2
%#function SP2_Syn_ProcZfInc3
%#function SP2_Syn_ProcZfReset
%#function SP2_Syn_ProcZfUpdate
%#function SP2_Syn_ProcessFid
%#function SP2_Syn_ProcessSpec
%#function SP2_Syn_SynthesisMain
%#function SP2_Syn_SynthesisWinUpdate
%#function SP2_Syn_UpdateCalcUpdate
%#function SP2_Syn_VerboseFlagUpdate
%#function SP2_T1T2_AmplShowAutoUpdate
%#function SP2_T1T2_AmplShowDirectUpdate
%#function SP2_T1T2_AnaAmplCalcT1
%#function SP2_T1T2_AnaAmplCalcT2
%#function SP2_T1T2_AnaAmplitudeStrUpdate
%#function SP2_T1T2_AnaDataFidUpdate
%#function SP2_T1T2_AnaDataPeakHeightUpdate
%#function SP2_T1T2_AnaDataPeakIntegralUpdate
%#function SP2_T1T2_AnaDataUpdate
%#function SP2_T1T2_AnaFitOffsetUpdate
%#function SP2_T1T2_AnaFormatMagnUpdate
%#function SP2_T1T2_AnaFormatRealUpdate
%#function SP2_T1T2_AnaIntegOffsetCorrUpdate
%#function SP2_T1T2_AnaModeFixedUpdate
%#function SP2_T1T2_AnaModeFlex1FixUpdate
%#function SP2_T1T2_AnaModeFlexibleUpdate
%#function SP2_T1T2_AnaSignFlipUpdate
%#function SP2_T1T2_AnaTConstStrUpdate
%#function SP2_T1T2_AnaTimeStrUpdate
%#function SP2_T1T2_DataLoad
%#function SP2_T1T2_DataLoadAndReco
%#function SP2_T1T2_DataReco
%#function SP2_T1T2_DataResort
%#function SP2_T1T2_DoT1Analysis
%#function SP2_T1T2_DoT2Analysis
%#function SP2_T1T2_DoTConstAnalysis
%#function SP2_T1T2_ExtractPpmRange
%#function SP2_T1T2_FormatMagnUpdate
%#function SP2_T1T2_FormatRealUpdate
%#function SP2_T1T2_ParsUpdate
%#function SP2_T1T2_PlotFidArray
%#function SP2_T1T2_PlotRawData
%#function SP2_T1T2_PlotSpecArray
%#function SP2_T1T2_PpmAssignToPeak
%#function SP2_T1T2_PpmShowDirectUpdate
%#function SP2_T1T2_PpmShowFullUpdate
%#function SP2_T1T2_T1DecayCalcDelay
%#function SP2_T1T2_T1DecayCalcScale
%#function SP2_T1T2_T1FunExp01
%#function SP2_T1T2_T1FunExp01_Offset
%#function SP2_T1T2_T1FunExp01_OneFix_Offset
%#function SP2_T1T2_T1FunExp02
%#function SP2_T1T2_T1FunExp02_Offset
%#function SP2_T1T2_T1FunExp02_OneFix
%#function SP2_T1T2_T1FunExp02_OneFix_Offset
%#function SP2_T1T2_T1FunExp03
%#function SP2_T1T2_T1FunExp03_Offset
%#function SP2_T1T2_T1FunExp03_OneFix
%#function SP2_T1T2_T1FunExp03_OneFix_Offset
%#function SP2_T1T2_T1FunExp04
%#function SP2_T1T2_T1FunExp04_Offset
%#function SP2_T1T2_T1FunExp04_OneFix
%#function SP2_T1T2_T1FunExp04_OneFix_Offset
%#function SP2_T1T2_T1FunExp05
%#function SP2_T1T2_T1FunExp05_Offset
%#function SP2_T1T2_T1FunExp05_OneFix
%#function SP2_T1T2_T1FunExp05_OneFix_Offset
%#function SP2_T1T2_T1T2Main
%#function SP2_T1T2_T1T2WinUpdate
%#function SP2_T1T2_T2DecayCalcDelay
%#function SP2_T1T2_T2DecayCalcScale
%#function SP2_T1T2_T2FunExp01
%#function SP2_T1T2_T2FunExp01_Offset
%#function SP2_T1T2_T2FunExp01_OneFix_Offset
%#function SP2_T1T2_T2FunExp02
%#function SP2_T1T2_T2FunExp02_Offset
%#function SP2_T1T2_T2FunExp02_OneFix
%#function SP2_T1T2_T2FunExp02_OneFix_Offset
%#function SP2_T1T2_T2FunExp03
%#function SP2_T1T2_T2FunExp03_Offset
%#function SP2_T1T2_T2FunExp03_OneFix
%#function SP2_T1T2_T2FunExp03_OneFix_Offset
%#function SP2_T1T2_T2FunExp04
%#function SP2_T1T2_T2FunExp04_Offset
%#function SP2_T1T2_T2FunExp04_OneFix
%#function SP2_T1T2_T2FunExp04_OneFix_Offset
%#function SP2_T1T2_T2FunExp05
%#function SP2_T1T2_T2FunExp05_Offset
%#function SP2_T1T2_T2FunExp05_OneFix
%#function SP2_T1T2_T2FunExp05_OneFix_Offset
%#function SP2_Tools_AnonDirApply
%#function SP2_Tools_AnonDirPathUpdate
%#function SP2_Tools_AnonDirSelect
%#function SP2_Tools_AnonymizeProcpar
%#function SP2_Tools_ToolsMain
%#function SP2_Tools_ToolsWinUpdate
%#function atamult
