%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
    function SP2_Proc_ProcessMain
%% 
%%  Main window for processing of multiple MR spectra
%%
%%  08-2008, Christoph Juchem
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global fm fmfig pars flag proc


if ~SP2_ClearWindow
    fprintf('\n--- WARNING ---\nClearing of window figure handles failed.\n\n');
    return
end
flag.fmWin = 4;
pars.figPos = get(fmfig,'Position');
set(fmfig,'Name',' INSPECTOR: Data Processing','Position',...
    [pars.figPos(1) pars.figPos(2) pars.mainDims(3) pars.mainDims(4)])


%**************************************************************************************************
%    O N E    V S .    T W O    S P E C T R A
%**************************************************************************************************
fm.proc.numSpecOne = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','1', ...
                               'Value',flag.procNumSpec==0,'Position',[.02 .96 .06 .03],'Callback','SP2_Proc_NumSpecOneUpdate',...
                               'TooltipString',sprintf('Processing of a single spectrum'),'FontSize',pars.fontSize);
fm.proc.numSpecTwo = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','2', ...
                               'Value',flag.procNumSpec==1,'Position',[.08 .96 .06 .03],'Callback','SP2_Proc_NumSpecTwoUpdate',...
                               'TooltipString',sprintf('Processing of two spectra'),'FontSize',pars.fontSize);

%**************************************************************************************************
%    D A T A     O R I G I N    A N D    F O R M A T  
%**************************************************************************************************
fm.proc.datData    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Data', ...
                               'Value',flag.procData==1,'Position',[.16 .96 .09 .03],'Callback','SP2_Proc_DataDataUpdate',...
                               'TooltipString',sprintf('Data origin:\nExperimental data from data page'),'FontSize',pars.fontSize);
fm.proc.datProc    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Proc', ...
                               'Value',flag.procData==2,'Position',[.25 .96 .09 .03],'Callback','SP2_Proc_DataProcUpdate',...
                               'TooltipString',sprintf('Data origin:\nLoad data from file(s) below'),'FontSize',pars.fontSize);
fm.proc.dataFormat = uicontrol('Style','Popup','String',SP2_CellArrayToStrList(proc.dataFormatCell,'|'),'Value',flag.procDataFormat,...
                               'Position',[200 689 140 8],'Callback','SP2_Proc_DataFormatUpdate;', ...
                               'TooltipString',sprintf('Processing and export data format'),'FontSize',pars.fontSize);
fm.proc.datMrsi    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','MRSI', ...
                               'Value',flag.procData==3,'Position',[.59 .96 .09 .03],'Callback','SP2_Proc_DataMrsiUpdate',...
                               'TooltipString',sprintf('Data origin:\nLoad data from file(s) below'),'FontSize',pars.fontSize);
fm.proc.datSyn     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Syn', ...
                               'Value',flag.procData==4,'Position',[.69 .96 .09 .03],'Callback','SP2_Proc_DataSynUpdate',...
                               'TooltipString',sprintf('Data origin:\nLoad data from file(s) below'),'FontSize',pars.fontSize);
fm.proc.datMarss   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','MARSS', ...
                               'Value',flag.procData==5,'Position',[.78 .96 .11 .03],'Callback','SP2_Proc_DataMarssUpdate',...
                               'TooltipString',sprintf('Data origin:\nLoad data from file(s) below'),'FontSize',pars.fontSize);
fm.proc.datLcm     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','LCM', ...
                               'Value',flag.procData==6,'Position',[.90 .96 .09 .03],'Callback','SP2_Proc_DataLcmUpdate',...
                               'TooltipString',sprintf('Data origin:\nLoad data from file(s) below'),'FontSize',pars.fontSize);
                        
                        
%**************************************************************************
%****
%   L O A D     D A T A     F R O M      F I L E 
%******************************************************************************
%--- data set 1 ---
fm.proc.spec1DataLab    = text('Position',[-0.145, 1.025],'String','Spec 1','FontSize',pars.fontSize);
if flag.procDataFormat==1        % matlab format
    fm.proc.spec1DataPath   = uicontrol('Style','Edit','Position', [60 655 440 18],'String',proc.spec1.dataPathMat,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec1DataPathUpdate;','FontSize',pars.fontSize);
elseif flag.procDataFormat==2    % text format 
    fm.proc.spec1DataPath   = uicontrol('Style','Edit','Position', [60 655 440 18],'String',proc.spec1.dataPathTxt,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec1DataPathUpdate;','FontSize',pars.fontSize);
elseif flag.procDataFormat==3    % metabolite (.par) format 
    fm.proc.spec1DataPath   = uicontrol('Style','Edit','Position', [60 655 440 18],'String',proc.spec1.dataPathPar,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec1DataPathUpdate;','FontSize',pars.fontSize);
else                             % LCModel (.raw) format 
    fm.proc.spec1DataPath   = uicontrol('Style','Edit','Position', [60 655 440 18],'String',proc.spec1.dataPathRaw,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec1DataPathUpdate;','FontSize',pars.fontSize);
end
fm.proc.spec1DataSelect = uicontrol('Style','Pushbutton','String','Select','Position',[500 655 45 18],...
                                    'Callback','SP2_Proc_Spec1DataSelect','FontSize',pars.fontSize);
fm.proc.spec1DataLoad   = uicontrol('Style','Pushbutton','String','Load','Position',[545 655 45 18],...
                                    'Callback','SP2_Proc_DataAndParsAssign1;','FontSize',pars.fontSize);

%--- data set 2 ---
fm.proc.spec2DataLab    = text('Position',[-0.145, 0.990],'String','Spec 2','FontSize',pars.fontSize);
if flag.procDataFormat==1        % matlab format
    fm.proc.spec2DataPath   = uicontrol('Style','Edit','Position', [60 635 440 18],'String',proc.spec2.dataPathMat,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec2DataPathUpdate;','FontSize',pars.fontSize);
elseif flag.procDataFormat==2    % text format 
    fm.proc.spec2DataPath   = uicontrol('Style','Edit','Position', [60 635 440 18],'String',proc.spec2.dataPathTxt,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec2DataPathUpdate;','FontSize',pars.fontSize);
elseif flag.procDataFormat==3    % .par format 
    fm.proc.spec2DataPath   = uicontrol('Style','Edit','Position', [60 635 440 18],'String',proc.spec2.dataPathPar,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec2DataPathUpdate;','FontSize',pars.fontSize);
else                             % .raw format 
    fm.proc.spec2DataPath   = uicontrol('Style','Edit','Position', [60 635 440 18],'String',proc.spec2.dataPathRaw,...
                                        'HorizontalAlignment','Left','Callback','SP2_Proc_Spec2DataPathUpdate;','FontSize',pars.fontSize);
end
fm.proc.spec2DataSelect = uicontrol('Style','Pushbutton','String','Select','Position',[500 635 45 18],...
                                    'Callback','SP2_Proc_Spec2DataSelect','FontSize',pars.fontSize);
fm.proc.spec2DataLoad   = uicontrol('Style','Pushbutton','String','Load','Position',[545 635 45 18],...
                                    'Callback','SP2_Proc_DataAndParsAssign2;','FontSize',pars.fontSize);

%--- export data ---
fm.proc.exptDataLab    = text('Position',[-0.145, 0.955],'String','Export','FontSize',pars.fontSize);
if flag.procDataFormat==1 || flag.procDataFormat==3     % matlab format
    fm.proc.exptDataPath   = uicontrol('Style','Edit','Position', [60 615 440 18],'String',proc.expt.dataPathMat,...
                                       'HorizontalAlignment','Left','Callback','SP2_Proc_ExptDataPathUpdate;','FontSize',pars.fontSize);
elseif flag.procDataFormat==2                           % text format 
    fm.proc.exptDataPath   = uicontrol('Style','Edit','Position', [60 615 440 18],'String',proc.expt.dataPathTxt,...
                                       'HorizontalAlignment','Left','Callback','SP2_Proc_ExptDataPathUpdate;','FontSize',pars.fontSize);
else                                                    % raw format 
    fm.proc.exptDataPath   = uicontrol('Style','Edit','Position', [60 615 440 18],'String',proc.expt.dataPathRaw,...
                                       'HorizontalAlignment','Left','Callback','SP2_Proc_ExptDataRawUpdate;','FontSize',pars.fontSize);
end
fm.proc.exptDataSelect = uicontrol('Style','Pushbutton','String','Select','Position',[500 615 45 18],...
                                   'Callback','SP2_Proc_ExptDataSelect','FontSize',pars.fontSize);
fm.proc.exptDataSave   = uicontrol('Style','Pushbutton','String','Save','Position',[545 615 45 18],...
                                   'Callback','SP2_Proc_ExptDataSave;','FontSize',pars.fontSize);

% spectrum 1: FID apodization
fm.proc.specCutLab    = text('Position',[-0.13, 0.8930],'String','Cut','FontSize',pars.fontSize);
fm.proc.spec1CutFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                  'FontSize',10,'Units','Normalized','Value',flag.procSpec1Cut==1,...
                                  'Position',[.12 .822 .03 .03],'Callback','SP2_Proc_Spec1CutFlagUpdate',...
                                  'TooltipString',sprintf('Apodization of FID data vector [pts]'));
fm.proc.spec1CutDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1CutDec3');
fm.proc.spec1CutDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1CutDec2');
fm.proc.spec1CutDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1CutDec1');
fm.proc.spec1CutVal   = uicontrol('Style','Edit','Position', [161 580 55 18],'String',sprintf('%.0f',proc.spec1.cut),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1CutUpdate','FontSize',pars.fontSize);
fm.proc.spec1CutInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1CutInc1');
fm.proc.spec1CutInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1CutInc2');
fm.proc.spec1CutInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1CutInc3');
fm.proc.spec1CutReset = uicontrol('Style','Pushbutton','String','R','Position',[285 580 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1CutReset');

% spectrum 2: FID apodization
fm.proc.spec2CutFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                  'FontSize',10,'Units','Normalized','Value',flag.procSpec2Cut==1,...
                                  'Position',[.55 .822 .03 .03],'Callback','SP2_Proc_Spec2CutFlagUpdate',...
                                  'TooltipString',sprintf('Apodization of FID data vector [pts]'),'FontSize',pars.fontSize);
fm.proc.spec2CutDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2CutDec3');
fm.proc.spec2CutDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2CutDec2');
fm.proc.spec2CutDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2CutDec1');
fm.proc.spec2CutVal   = uicontrol('Style','Edit','Position', [419 580 55 18],'String',sprintf('%.0f',proc.spec2.cut),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2CutUpdate','FontSize',pars.fontSize);
fm.proc.spec2CutInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2CutInc1');
fm.proc.spec2CutInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2CutInc2');
fm.proc.spec2CutInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 580 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2CutInc3');              
fm.proc.spec2CutReset = uicontrol('Style','Pushbutton','String','R','Position',[543  580 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2CutReset');              
fm.proc.syncCut       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                  'Normalized','Value',flag.procSyncCut,'Position',[.96 .822 .03 .03],...
                                  'Callback','SP2_Proc_SyncCutFlagUpdate','TooltipString',...
                                  sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);
                          
% spectrum 1: FID zero-filling
fm.proc.specZfLab    = text('Position',[-0.13, 0.8491],'String','ZF','FontSize',pars.fontSize);
fm.proc.spec1ZfFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                 'FontSize',10,'Units','Normalized','Value',flag.procSpec1Zf==1,...
                                 'Position',[.12 .7864 .03 .03],'Callback','SP2_Proc_Spec1ZfFlagUpdate',...
                                 'TooltipString',sprintf('Time domain zero-filling [pts]'),'FontSize',pars.fontSize);
fm.proc.spec1ZfDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ZfDec3');
fm.proc.spec1ZfDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ZfDec2');
fm.proc.spec1ZfDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ZfDec1');
fm.proc.spec1ZfVal   = uicontrol('Style','Edit','Position', [161 555 55 18],'String',sprintf('%.0f',proc.spec1.zf),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1ZfUpdate','FontSize',pars.fontSize);
fm.proc.spec1ZfInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ZfInc1');
fm.proc.spec1ZfInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ZfInc2');
fm.proc.spec1ZfInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ZfInc3');
fm.proc.spec1ZfReset = uicontrol('Style','Pushbutton','String','R','Position',[285 555 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1ZfReset');
                            
% spectrum 2: FID zero-filling
fm.proc.spec2ZfFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                 'FontSize',10,'Units','Normalized','Value',flag.procSpec2Zf==1,...
                                 'Position',[.55 .7864 .03 .03],'Callback','SP2_Proc_Spec2ZfFlagUpdate',...
                                 'TooltipString',sprintf('Time domain zero-filling [pts]'),'FontSize',pars.fontSize);
fm.proc.spec2ZfDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ZfDec3');
fm.proc.spec2ZfDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ZfDec2');
fm.proc.spec2ZfDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ZfDec1');
fm.proc.spec2ZfVal   = uicontrol('Style','Edit','Position', [419 555 55 18],'String',sprintf('%.0f',proc.spec2.zf),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2ZfUpdate','FontSize',pars.fontSize);
fm.proc.spec2ZfInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ZfInc1');
fm.proc.spec2ZfInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ZfInc2');
fm.proc.spec2ZfInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 555 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ZfInc3');
fm.proc.spec2ZfReset = uicontrol('Style','Pushbutton','String','R','Position',[543  555 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2ZfReset');
fm.proc.syncZf       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                 'Normalized','Value',flag.procSyncZf,'Position',[.96 .7864 .03 .03],...
                                 'Callback','SP2_Proc_SyncZfFlagUpdate','TooltipString',...
                                 sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);
                            
% spectrum 1: exponential line broadening
fm.proc.specLbLab    = text('Position',[-0.13, 0.8053],'String','LB','FontSize',pars.fontSize);
fm.proc.spec1LbFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                 'FontSize',10,'Units','Normalized','Value',flag.procSpec1Lb==1,...
                                 'Position',[.12 .7508 .03 .03],'Callback','SP2_Proc_Spec1LbFlagUpdate',...
                                 'TooltipString',sprintf('Exponential line broadening [Hz]\n(compare Gaussian broadening, GB)'),'FontSize',pars.fontSize);
fm.proc.spec1LbDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1LbDec3');
fm.proc.spec1LbDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1LbDec2');
fm.proc.spec1LbDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1LbDec1');
fm.proc.spec1LbVal   = uicontrol('Style','Edit','Position', [161 530 55 18],'String',sprintf('%.2f',proc.spec1.lb),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1LbUpdate','FontSize',pars.fontSize);
fm.proc.spec1LbInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1LbInc1');
fm.proc.spec1LbInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1LbInc2');
fm.proc.spec1LbInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1LbInc3');
fm.proc.spec1LbReset = uicontrol('Style','Pushbutton','String','R','Position',[285 530 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1LbReset');

% spectrum 2: exponential line broadening
fm.proc.spec2LbFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                 'FontSize',10,'Units','Normalized','Value',flag.procSpec2Lb==1,...
                                 'Position',[.55 .7508 .03 .03],'Callback','SP2_Proc_Spec2LbFlagUpdate',...
                                 'TooltipString',sprintf('Exponential line broadening [Hz]\n(compare Gaussian broadening, GB)'),'FontSize',pars.fontSize);
fm.proc.spec2LbDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2LbDec3');
fm.proc.spec2LbDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2LbDec2');
fm.proc.spec2LbDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2LbDec1');
fm.proc.spec2LbVal   = uicontrol('Style','Edit','Position', [419 530 55 18],'String',sprintf('%.2f',proc.spec2.lb),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2LbUpdate','FontSize',pars.fontSize);
fm.proc.spec2LbInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2LbInc1');
fm.proc.spec2LbInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2LbInc2');
fm.proc.spec2LbInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 530 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2LbInc3');
fm.proc.spec2LbReset = uicontrol('Style','Pushbutton','String','R','Position',[543  530 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2LbReset');
fm.proc.syncLb       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                 'Normalized','Value',flag.procSyncLb,'Position',[.96 .7508 .03 .03],...
                                 'Callback','SP2_Proc_SyncLbFlagUpdate','TooltipString',...
                                 sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);
                         
% spectrum 1: Gaussian line broadening
fm.proc.specGbLab    = text('Position',[-0.13, 0.7614],'String','GB','FontSize',pars.fontSize);
fm.proc.spec1GbFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                 'FontSize',10,'Units','Normalized','Value',flag.procSpec1Gb==1,...
                                 'Position',[.12 .7151 .03 .03],'Callback','SP2_Proc_Spec1GbFlagUpdate',...
                                 'TooltipString',sprintf('Gaussian line broadening [Hz^2]\n(compare exponential broadening, LB)'),'FontSize',pars.fontSize);
fm.proc.spec1GbDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1GbDec3');
fm.proc.spec1GbDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1GbDec2');
fm.proc.spec1GbDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1GbDec1');
fm.proc.spec1GbVal   = uicontrol('Style','Edit','Position', [161 505 55 18],'String',sprintf('%.2f',proc.spec1.gb),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1GbUpdate','FontSize',pars.fontSize);
fm.proc.spec1GbInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1GbInc1');
fm.proc.spec1GbInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1GbInc2');
fm.proc.spec1GbInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1GbInc3');
fm.proc.spec1GbReset = uicontrol('Style','Pushbutton','String','R','Position',[285 505 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1GbReset');

% spectrum 2: Gaussian line broadening
fm.proc.spec2GbFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                 'FontSize',10,'Units','Normalized','Value',flag.procSpec2Gb==1,...
                                 'Position',[.55 .7151 .03 .03],'Callback','SP2_Proc_Spec2GbFlagUpdate',...
                                 'TooltipString',sprintf('Gaussian line broadening [Hz^2]\n(compare exponential broadening, LB)'),'FontSize',pars.fontSize);
fm.proc.spec2GbDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2GbDec3');
fm.proc.spec2GbDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2GbDec2');
fm.proc.spec2GbDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2GbDec1');
fm.proc.spec2GbVal   = uicontrol('Style','Edit','Position', [419 505 55 18],'String',sprintf('%.2f',proc.spec2.gb),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2GbUpdate','FontSize',pars.fontSize);
fm.proc.spec2GbInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2GbInc1');
fm.proc.spec2GbInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2GbInc2');
fm.proc.spec2GbInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 505 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2GbInc3');
fm.proc.spec2GbReset = uicontrol('Style','Pushbutton','String','R','Position',[543  505 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2GbReset');
fm.proc.syncGb       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                 'Normalized','Value',flag.procSyncGb,'Position',[.96 .7151 .03 .03],...
                                 'Callback','SP2_Proc_SyncGbFlagUpdate','TooltipString',...
                                 sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);
                         
% phase correction: spectrum 1, zero order          
fm.proc.specPhc0Lab    = text('Position',[-0.13, 0.7175],'String','PHC0','FontSize',pars.fontSize);
fm.proc.spec1Phc0Flag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',10,'Units','Normalized','Value',flag.procSpec1Phc0==1,...
                                   'Position',[.12 .6795 .03 .03],'Callback','SP2_Proc_Spec1Phc0FlagUpdate',...
                                   'TooltipString',sprintf('Zero order phase correction [deg]'),'FontSize',pars.fontSize);
fm.proc.spec1Phc0Dec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc0Dec3');
fm.proc.spec1Phc0Dec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc0Dec2');
fm.proc.spec1Phc0Dec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc0Dec1');
fm.proc.spec1Phc0Val   = uicontrol('Style','Edit','Position', [161 480 55 18],'String',sprintf('%.1f',proc.spec1.phc0), ...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1Phc0Update','FontSize',pars.fontSize);
fm.proc.spec1Phc0Inc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc0Inc1');
fm.proc.spec1Phc0Inc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc0Inc2');
fm.proc.spec1Phc0Inc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc0Inc3');
fm.proc.spec1Phc0Reset = uicontrol('Style','Pushbutton','String','R','Position',[285 480 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1Phc0Reset');

% phase correction: spectrum 2, zero order          
fm.proc.spec2Phc0Flag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',10,'Units','Normalized','Value',flag.procSpec2Phc0==1,...
                                   'Position',[.55 .6795 .03 .03],'Callback','SP2_Proc_Spec2Phc0FlagUpdate',...
                                   'TooltipString',sprintf('Zero order phase correction [deg]'),'FontSize',pars.fontSize);
fm.proc.spec2Phc0Dec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc0Dec3');
fm.proc.spec2Phc0Dec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc0Dec2');
fm.proc.spec2Phc0Dec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc0Dec1');
fm.proc.spec2Phc0Val   = uicontrol('Style','Edit','Position', [419 480 55 18],'String',sprintf('%.1f',proc.spec2.phc0), ...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2Phc0Update','FontSize',pars.fontSize);
fm.proc.spec2Phc0Inc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc0Inc1');
fm.proc.spec2Phc0Inc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc0Inc2');
fm.proc.spec2Phc0Inc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 480 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc0Inc3');
fm.proc.spec2Phc0Reset = uicontrol('Style','Pushbutton','String','R','Position',[543  480 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2Phc0Reset');
fm.proc.syncPhc0       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                 'Normalized','Value',flag.procSyncPhc0,'Position',[.96 .6795 .03 .03],...
                                 'Callback','SP2_Proc_SyncPhc0FlagUpdate','TooltipString',...
                                 sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);

% phase correction: spectrum 1, first order          
fm.proc.specPhc1Lab    = text('Position',[-0.13, 0.6736],'String','PHC1','FontSize',pars.fontSize);
fm.proc.spec1Phc1Flag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',10,'Units','Normalized','Value',flag.procSpec1Phc1==1,...
                                   'Position',[.12 .6439 .03 .03],'Callback','SP2_Proc_Spec1Phc1FlagUpdate',...
                                   'TooltipString',sprintf('First order phase correction [deg]'),'FontSize',pars.fontSize);
fm.proc.spec1Phc1Dec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc1Dec3');
fm.proc.spec1Phc1Dec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc1Dec2');
fm.proc.spec1Phc1Dec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc1Dec1');
fm.proc.spec1Phc1Val   = uicontrol('Style','Edit','Position', [161 455 55 18],'String',sprintf('%.1f',proc.spec1.phc1), ...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1Phc1Update','FontSize',pars.fontSize);
fm.proc.spec1Phc1Inc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc1Inc1');
fm.proc.spec1Phc1Inc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc1Inc2');
fm.proc.spec1Phc1Inc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1Phc1Inc3');
fm.proc.spec1Phc1Reset = uicontrol('Style','Pushbutton','String','R','Position',[285 455 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1Phc1Reset');

% phase correction: spectrum 2, first order          
fm.proc.spec2Phc1Flag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                   'FontSize',10,'Units','Normalized','Value',flag.procSpec2Phc1==1,...
                                   'Position',[.55 .6439 .03 .03],'Callback','SP2_Proc_Spec2Phc1FlagUpdate',...
                                   'TooltipString',sprintf('First order phase correction [deg]'),'FontSize',pars.fontSize);
fm.proc.spec2Phc1Dec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 455 22 18],'FontWeight','bold','Callback','SP2_Proc_Spec2Phc1Dec3');
fm.proc.spec2Phc1Dec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 455 22 18],'FontWeight','bold','Callback','SP2_Proc_Spec2Phc1Dec2');
fm.proc.spec2Phc1Dec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 455 22 18],'FontWeight','bold','Callback','SP2_Proc_Spec2Phc1Dec1');
fm.proc.spec2Phc1Val   = uicontrol('Style','Edit','Position', [419 455 55 18],'String',sprintf('%.1f',proc.spec2.phc1), ...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2Phc1Update','FontSize',pars.fontSize);
fm.proc.spec2Phc1Inc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc1Inc1');
fm.proc.spec2Phc1Inc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc1Inc2');
fm.proc.spec2Phc1Inc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 455 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2Phc1Inc3');
fm.proc.spec2Phc1Reset = uicontrol('Style','Pushbutton','String','R','Position',[543  455 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2Phc1Reset');
fm.proc.syncPhc1       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                 'Normalized','Value',flag.procSyncPhc1,'Position',[.96 .6439 .03 .03],...
                                 'Callback','SP2_Proc_SyncPhc1FlagUpdate','TooltipString',...
                                 sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);

% amplitude scaling: spectrum 1
fm.proc.specScaleLab    = text('Position',[-0.13, 0.6298],'String','Scale','FontSize',pars.fontSize);
fm.proc.spec1ScaleFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                    'FontSize',10,'Units','Normalized','Value',flag.procSpec1Scale==1,...
                                    'Position',[.12 .6082 .03 .03],'Callback','SP2_Proc_Spec1ScaleFlagUpdate',...
                                    'TooltipString',sprintf('Amplitude scaling [1]'),'FontSize',pars.fontSize);
fm.proc.spec1ScaleDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ScaleDec3');
fm.proc.spec1ScaleDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ScaleDec2');
fm.proc.spec1ScaleDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ScaleDec1');
fm.proc.spec1ScaleVal   = uicontrol('Style','Edit','Position', [161 430 55 18],'String',sprintf('%.3f',proc.spec1.scale), ...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1ScaleUpdate','FontSize',pars.fontSize);
fm.proc.spec1ScaleInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ScaleInc1');
fm.proc.spec1ScaleInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ScaleInc2');
fm.proc.spec1ScaleInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ScaleInc3');
fm.proc.spec1ScaleReset = uicontrol('Style','Pushbutton','String','R','Position',[285 430 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1ScaleReset');

% amplitude scaling: spectrum 2
fm.proc.spec2ScaleFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                    'FontSize',10,'Units','Normalized','Value',flag.procSpec2Scale==1,...
                                    'Position',[.55 .6082 .03 .03],'Callback','SP2_Proc_Spec2ScaleFlagUpdate',...
                                    'TooltipString',sprintf('Amplitude scaling [1]'),'FontSize',pars.fontSize);
fm.proc.spec2ScaleDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ScaleDec3');
fm.proc.spec2ScaleDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ScaleDec2');
fm.proc.spec2ScaleDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ScaleDec1');
fm.proc.spec2ScaleVal   = uicontrol('Style','Edit','Position', [419 430 55 18],'String',sprintf('%.3f',proc.spec2.scale), ...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2ScaleUpdate','FontSize',pars.fontSize);
fm.proc.spec2ScaleInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ScaleInc1');
fm.proc.spec2ScaleInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ScaleInc2');
fm.proc.spec2ScaleInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 430 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ScaleInc3');
fm.proc.spec2ScaleReset = uicontrol('Style','Pushbutton','String','R','Position',[543  430 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2ScaleReset');
fm.proc.syncScale       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                 'Normalized','Value',flag.procSyncScale,'Position',[.96 .6082 .03 .03],...
                                 'Callback','SP2_Proc_SyncScaleFlagUpdate','TooltipString',...
                                 sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);

% frequency shift: spectrum 1          
fm.proc.specShiftLab    = text('Position',[-0.13, 0.5859],'String','Shift','FontSize',pars.fontSize);
fm.proc.spec1ShiftFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                    'FontSize',10,'Units','Normalized','Value',flag.procSpec1Shift==1,...
                                    'Position',[.12 .5726 .03 .03],'Callback','SP2_Proc_Spec1ShiftFlagUpdate',...
                                    'TooltipString',sprintf('Spectral shift [Hz]'),'FontSize',pars.fontSize);
fm.proc.spec1ShiftDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ShiftDec3');
fm.proc.spec1ShiftDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ShiftDec2');
fm.proc.spec1ShiftDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ShiftDec1');
fm.proc.spec1ShiftVal   = uicontrol('Style','Edit','Position', [161 405 55 18],'String',sprintf('%.3f',proc.spec1.shift), ...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1ShiftUpdate','FontSize',pars.fontSize);
fm.proc.spec1ShiftInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ShiftInc1');
fm.proc.spec1ShiftInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ShiftInc2');
fm.proc.spec1ShiftInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1ShiftInc3');
fm.proc.spec1ShiftReset = uicontrol('Style','Pushbutton','String','R','Position',[285 405 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1ShiftReset');

% frequency shift: spectrum 2
fm.proc.spec2ShiftFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                    'FontSize',10,'Units','Normalized','Value',flag.procSpec2Shift==1,...
                                    'Position',[.55 .5726 .03 .03],'Callback','SP2_Proc_Spec2ShiftFlagUpdate',...
                                    'TooltipString',sprintf('Spectral shift [Hz]'),'FontSize',pars.fontSize);
fm.proc.spec2ShiftDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ShiftDec3');
fm.proc.spec2ShiftDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ShiftDec2');
fm.proc.spec2ShiftDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ShiftDec1');
fm.proc.spec2ShiftVal   = uicontrol('Style','Edit','Position', [419 405 55 18],'String',sprintf('%.3f',proc.spec2.shift), ...
                                    'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2ShiftUpdate','FontSize',pars.fontSize);
fm.proc.spec2ShiftInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ShiftInc1');
fm.proc.spec2ShiftInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ShiftInc2');
fm.proc.spec2ShiftInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 405 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2ShiftInc3');
fm.proc.spec2ShiftReset = uicontrol('Style','Pushbutton','String','R','Position',[543  405 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2ShiftReset');
fm.proc.syncShift       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                 'Normalized','Value',flag.procSyncShift,'Position',[.96 .5726 .03 .03],...
                                 'Callback','SP2_Proc_SyncShiftFlagUpdate','TooltipString',...
                                 sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);

% baseline offset: spectrum 1          
fm.proc.specOffsetLab    = text('Position',[-0.13, 0.5420],'String','Offset','FontSize',pars.fontSize);
fm.proc.spec1OffsetFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                     'FontSize',10,'Units','Normalized','Value',flag.procSpec1Offset==1,...
                                     'Position',[.12 .537 .03 .03],'Callback','SP2_Proc_Spec1OffsetFlagUpdate',...
                                     'TooltipString',sprintf('Baseline offset [a.u.]'),'FontSize',pars.fontSize);
fm.proc.spec1OffsetDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1OffsetDec3');
fm.proc.spec1OffsetDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1OffsetDec2');
fm.proc.spec1OffsetDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1OffsetDec1');
fm.proc.spec1OffsetVal   = uicontrol('Style','Edit','Position', [161 380 55 18],'String',num2str(proc.spec1.offset), ...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1OffsetUpdate','FontSize',pars.fontSize);
fm.proc.spec1OffsetInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1OffsetInc1');
fm.proc.spec1OffsetInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1OffsetInc2');
fm.proc.spec1OffsetInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1OffsetInc3');
fm.proc.spec1OffsetReset = uicontrol('Style','Pushbutton','String','R','Position',[285 380 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1OffsetReset');

% baseline offset: spectrum 2
fm.proc.spec2OffsetFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                     'FontSize',10,'Units','Normalized','Value',flag.procSpec2Offset==1,...
                                     'Position',[.55 .537 .03 .03],'Callback','SP2_Proc_Spec2OffsetFlagUpdate',...
                                     'TooltipString',sprintf('Baseline offset [a.u.]'),'FontSize',pars.fontSize);
fm.proc.spec2OffsetDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2OffsetDec3');
fm.proc.spec2OffsetDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2OffsetDec2');
fm.proc.spec2OffsetDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2OffsetDec1');
fm.proc.spec2OffsetVal   = uicontrol('Style','Edit','Position', [419 380 55 18],'String',num2str(proc.spec2.offset), .../
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2OffsetUpdate','FontSize',pars.fontSize);
fm.proc.spec2OffsetInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2OffsetInc1');
fm.proc.spec2OffsetInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2OffsetInc2');
fm.proc.spec2OffsetInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 380 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2OffsetInc3');
fm.proc.spec2OffsetReset = uicontrol('Style','Pushbutton','String','R','Position',[543  380 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2OffsetReset');
fm.proc.syncOffset       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                     'Normalized','Value',flag.procSyncOffset,'Position',[.96 .537 .03 .03],...
                                     'Callback','SP2_Proc_SyncOffsetFlagUpdate','TooltipString',...
                                     sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);

% spectral stretch: spectrum 1          
fm.proc.specStretchLab    = text('Position',[-0.13, 0.4981],'String','Stretch','FontSize',pars.fontSize);
fm.proc.spec1StretchFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                     'FontSize',10,'Units','Normalized','Value',flag.procSpec1Stretch==1,...
                                     'Position',[.12 .5014 .03 .03],'Callback','SP2_Proc_Spec1StretchFlagUpdate',...
                                     'TooltipString',sprintf('Stretching of frequency axis [Hz/ppm]'),'FontSize',pars.fontSize);
fm.proc.spec1StretchDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[95 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1StretchDec3');
fm.proc.spec1StretchDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[117 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1StretchDec2');
fm.proc.spec1StretchDec1  = uicontrol('Style','Pushbutton','String','<','Position',[139 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1StretchDec1');
fm.proc.spec1StretchVal   = uicontrol('Style','Edit','Position', [161 355 55 18],'String',num2str(proc.spec1.stretch), ...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec1StretchUpdate','FontSize',pars.fontSize);
fm.proc.spec1StretchInc1  = uicontrol('Style','Pushbutton','String','>','Position',[216 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1StretchInc1');
fm.proc.spec1StretchInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[238 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1StretchInc2');
fm.proc.spec1StretchInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[260 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec1StretchInc3');
fm.proc.spec1StretchReset = uicontrol('Style','Pushbutton','String','R','Position',[285 355 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec1StretchReset');

% spectral stretch: spectrum 2
fm.proc.spec2StretchFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,...
                                     'FontSize',10,'Units','Normalized','Value',flag.procSpec2Stretch==1,...
                                     'Position',[.55 .5014 .03 .03],'Callback','SP2_Proc_Spec2StretchFlagUpdate',...
                                     'TooltipString',sprintf('Stretching of frequency axis [Hz/ppm]'),'FontSize',pars.fontSize);
fm.proc.spec2StretchDec3  = uicontrol('Style','Pushbutton','String','<<<','Position',[353 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2StretchDec3');
fm.proc.spec2StretchDec2  = uicontrol('Style','Pushbutton','String','<<','Position',[375 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2StretchDec2');
fm.proc.spec2StretchDec1  = uicontrol('Style','Pushbutton','String','<','Position',[397 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2StretchDec1');
fm.proc.spec2StretchVal   = uicontrol('Style','Edit','Position', [419 355 55 18],'String',num2str(proc.spec2.stretch), ...
                                      'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_Spec2StretchUpdate','FontSize',pars.fontSize);
fm.proc.spec2StretchInc1  = uicontrol('Style','Pushbutton','String','>','Position',[474 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2StretchInc1');
fm.proc.spec2StretchInc2  = uicontrol('Style','Pushbutton','String','>>','Position',[496 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2StretchInc2');
fm.proc.spec2StretchInc3  = uicontrol('Style','Pushbutton','String','>>>','Position',[518 355 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_Spec2StretchInc3');
fm.proc.spec2StretchReset = uicontrol('Style','Pushbutton','String','R','Position',[543  355 22 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_Spec2StretchReset');
fm.proc.syncStretch       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,'Units',...
                                     'Normalized','Value',flag.procSyncStretch,'Position',[.96 .5014 .03 .03],...
                                     'Callback','SP2_Proc_SyncStretchFlagUpdate','TooltipString',...
                                     sprintf('Apply modifications to both FID 1 and FID 2'),'FontSize',pars.fontSize);

% % separation line
% fm.proc.line2 = text('Position',[-0.12, 0.5],'String','______________________________________________________________________');

% spectrum visualization: data format
fm.proc.formatLab   = text('Position',[-0.13, 0.45],'String','Format','FontSize',pars.fontSize);
fm.proc.formatReal  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Real', ...
                                'Value',flag.procFormat==1,'Position',[.13 .46 .15 .03],'Callback','SP2_Proc_FormatRealUpdate','FontSize',pars.fontSize);
fm.proc.formatImag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Imag', ...
                                'Value',flag.procFormat==2,'Position',[.22 .46 .15 .03],'Callback','SP2_Proc_FormatImagUpdate','FontSize',pars.fontSize);
fm.proc.formatMagn  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Magn', ...
                                'Value',flag.procFormat==3,'Position',[.305 .46 .15 .03],'Callback','SP2_Proc_FormatMagnUpdate','FontSize',pars.fontSize);
fm.proc.formatPhase = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Phase', ...
                                'Value',flag.procFormat==4,'Position',[.40 .46 .15 .03],'Callback','SP2_Proc_FormatPhaseUpdate','FontSize',pars.fontSize);

% spectrum visualization: ppm calibration
fm.proc.ppmCalibLab         = text('Position',[0.55, 0.450],'String','Calibration','FontSize',pars.fontSize);
fm.proc.ppmCalib            = uicontrol('Style','Edit','Position', [405 327 50 18],'String',num2str(proc.ppmCalib),'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmCalibUpdate',...
                                        'TooltipString',sprintf('Frequency [ppm] calibration of center (water) frequency'),'FontSize',pars.fontSize);
fm.proc.ppmAssign           = uicontrol('Style','Edit','Position', [470 327 45 18],'String',num2str(proc.ppmAssign),'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmAssignUpdate',...
                                        'TooltipString',sprintf('Frequency [ppm] value to be assigned to selected peak'),'FontSize',pars.fontSize);
fm.proc.ppmAssignToPeak     = uicontrol('Style','Pushbutton','String','Assign','Position',[515 327 55 18],...
                                        'FontSize',pars.fontSize,'Callback','SP2_Proc_PpmAssignToPeak',...
                                        'TooltipString',sprintf('Assign ppm value (to the left) to\nspectral position in selected spectrum'),'FontSize',pars.fontSize);
fm.proc.ppmAssignToPeakZoom = uicontrol('Style','Pushbutton','String','Z ','Position',[570 327 22 18],...
                                        'FontSize',pars.fontSize,'Callback','SP2_Proc_PpmAssignToPeakZoom',...
                                        'TooltipString',sprintf('Assign ppm value to spectral position\nin selected spectrum\nZoomed window: Current value +/- 0.3 ppm'),'FontSize',pars.fontSize);
                       
% spectrum visualization: ppm position display
fm.proc.ppmShowPosLab    = text('Position',[0.55, 0.40],'String','Position','FontSize',pars.fontSize);
fm.proc.ppmShowPos       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.procPpmShowPos,...
                                     'Position',[0.64 0.42 .03 .03],'Callback','SP2_Proc_PpmShowPosFlagUpdate','FontSize',pars.fontSize);
fm.proc.ppmShowPosVal    = uicontrol('Style','Edit','Position',[405 298 50 18],'String',num2str(proc.ppmShowPos),'BackGroundColor',pars.bgColor,...
                                     'Callback','SP2_Proc_PpmShowPosValUpdate','TooltipString',sprintf('Frequency [ppm] position to be displayed'),'FontSize',pars.fontSize);
fm.proc.ppmShowPosAssign = uicontrol('Style','Pushbutton','String','Assign','Position',[455 298 55 18],...
                                     'FontSize',pars.fontSize,'Callback','SP2_Proc_PpmShowPosAssign',...
                                     'TooltipString',sprintf('Manual assignment of frequency position [ppm]'),'FontSize',pars.fontSize);
fm.proc.ppmShowPosMirr   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.procPpmShowPosMirr,...
                                     'String','Mirror','Position',[0.87 0.42 .10 .03],'Callback','SP2_Proc_PpmShowPosMirrorUpdate',...
                                     'TooltipString',sprintf('Display also the frequency mirrored\naround the synthesizer (/water) position'),'FontSize',pars.fontSize);

% spectrum visualization: ppm window
fm.proc.ppmShowLab    = text('Position',[-0.13, 0.40],'String','Frequ.','FontSize',pars.fontSize);
fm.proc.ppmShowFull   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Full', ...
                                  'Value',flag.procPpmShow==0,'Position',[.13 .42 .15 .03],'Callback','SP2_Proc_PpmShowFullUpdate','FontSize',pars.fontSize);
fm.proc.ppmShowDirect = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized', ...
                                  'Value',flag.procPpmShow==1,'Position',[.21 .42 .15 .03],'Callback','SP2_Proc_PpmShowDirectUpdate','FontSize',pars.fontSize);
fm.proc.ppmShowMinDecr = uicontrol('Style','Pushbutton','String','-','Position',[145 298 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmShowMinDecr','FontSize',pars.fontSize);
fm.proc.ppmShowMin     = uicontrol('Style','Edit','Position', [163 298 40 18],'String',sprintf('%.2f',proc.ppmShowMin),...
                                   'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmShowWinUpdate');
fm.proc.ppmShowMinIncr = uicontrol('Style','Pushbutton','String','+','Position',[203 298 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmShowMinIncr','FontSize',pars.fontSize);
fm.proc.ppmShowMaxDecr = uicontrol('Style','Pushbutton','String','-','Position',[226 298 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmShowMaxDecr','FontSize',pars.fontSize);
fm.proc.ppmShowMax     = uicontrol('Style','Edit','Position', [244 298 40 18],'String',sprintf('%.2f',proc.ppmShowMax),...
                                   'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmShowWinUpdate');
fm.proc.ppmShowMaxIncr = uicontrol('Style','Pushbutton','String','+','Position',[284 298 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmShowMaxIncr','FontSize',pars.fontSize);

% spectrum visualization: amplitude window
fm.proc.amplLab    = text('Position',[-0.13, 0.35],'String','Ampl.','FontSize',pars.fontSize);
fm.proc.amplAuto   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Auto', ...
                               'Value',flag.procAmpl==0,'Position',[.13 .38 .15 .03],'Callback','SP2_Proc_AmplAutoUpdate','FontSize',pars.fontSize);
fm.proc.amplDirect = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized', ...
                               'Value',flag.procAmpl==1,'Position',[.21 .38 .15 .03],'Callback','SP2_Proc_AmplDirectUpdate');
fm.proc.amplMinDecr = uicontrol('Style','Pushbutton','String','-','Position',[145 270 18 18],'FontWeight','bold','Callback','SP2_Proc_AmplWinMinDecr','FontSize',pars.fontSize);
fm.proc.amplMin     = uicontrol('Style','Edit','Position', [163 270 50 18],'String',sprintf('%.0f',proc.amplMin),'BackGroundColor',pars.bgColor,...
                                'FontSize',pars.fontSize,'Callback','SP2_Proc_AmplWinMinUpdate');
fm.proc.amplMinIncr = uicontrol('Style','Pushbutton','String','+','Position',[213 270 18 18],'FontWeight','bold','Callback','SP2_Proc_AmplWinMinIncr','FontSize',pars.fontSize);
fm.proc.amplMaxDecr = uicontrol('Style','Pushbutton','String','-','Position',[236 270 18 18],'FontWeight','bold','Callback','SP2_Proc_AmplWinMaxDecr','FontSize',pars.fontSize);
fm.proc.amplMax     = uicontrol('Style','Edit','Position', [254 270 50 18],'String',sprintf('%.0f',proc.amplMax),'BackGroundColor',pars.bgColor,...
                                'FontSize',pars.fontSize,'Callback','SP2_Proc_AmplWinMaxUpdate');
fm.proc.amplMaxIncr = uicontrol('Style','Pushbutton','String','+','Position',[304 270 18 18],'FontWeight','bold','Callback','SP2_Proc_AmplWinMaxIncr','FontSize',pars.fontSize);

%--- FWHM / integral area definition ---
fm.proc.ppmTargetLab     = text('Position',[-0.13, 0.30],'String','Target','FontSize',pars.fontSize);
fm.proc.ppmTargetMinDecr = uicontrol('Style','Pushbutton','String','-','Position',[75 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmTargetMinDecr','FontSize',pars.fontSize);
fm.proc.ppmTargetMin     = uicontrol('Style','Edit','Position', [93 242 45 18],'String',sprintf('%.2f',proc.ppmTargetMin),...
                                     'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmTargetWinUpdate');
fm.proc.ppmTargetMinIncr = uicontrol('Style','Pushbutton','String','+','Position',[138 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmTargetMinIncr','FontSize',pars.fontSize);
fm.proc.ppmTargetMaxDecr = uicontrol('Style','Pushbutton','String','-','Position',[161 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmTargetMaxDecr','FontSize',pars.fontSize);
fm.proc.ppmTargetMax     = uicontrol('Style','Edit','Position', [179 242 45 18],'String',sprintf('%.2f',proc.ppmTargetMax),...
                                     'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmTargetWinUpdate');
fm.proc.ppmTargetMaxIncr = uicontrol('Style','Pushbutton','String','+','Position',[224 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmTargetMaxIncr','FontSize',pars.fontSize);

%--- noise area definition ---
fm.proc.ppmNoiseLab     = text('Position',[-0.13, 0.25],'String','Noise','FontSize',pars.fontSize);
fm.proc.ppmNoiseMinDecr = uicontrol('Style','Pushbutton','String','-','Position',[75 213 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmNoiseMinDecr','FontSize',pars.fontSize);
fm.proc.ppmNoiseMin     = uicontrol('Style','Edit','Position', [93 213 45 18],'String',sprintf('%.2f',proc.ppmNoiseMin),...
                                    'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmNoiseWinUpdate');
fm.proc.ppmNoiseMinIncr = uicontrol('Style','Pushbutton','String','+','Position',[138 213 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmNoiseMinIncr','FontSize',pars.fontSize);
fm.proc.ppmNoiseMaxDecr = uicontrol('Style','Pushbutton','String','-','Position',[161 213 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmNoiseMaxDecr','FontSize',pars.fontSize);
fm.proc.ppmNoiseMax     = uicontrol('Style','Edit','Position', [179 213 45 18],'String',sprintf('%.2f',proc.ppmNoiseMax),...
                                    'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_PpmNoiseWinUpdate');
fm.proc.ppmNoiseMaxIncr = uicontrol('Style','Pushbutton','String','+','Position',[224 213 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmNoiseMaxIncr','FontSize',pars.fontSize);

%--- offset definition ---
fm.proc.offsetLab  = text('Position',[0.44, 0.30],'String','Offset','FontSize',pars.fontSize);

fm.proc.offsetPpmFlag = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Range', ...
                                  'Value',flag.procOffset,'Position',[.540 .34 .10 .03],'Callback','SP2_Proc_OffsetPpmWinFlagUpdate','FontSize',pars.fontSize);
fm.proc.ppmOffsetMinDecr = uicontrol('Style','Pushbutton','String','-','Position',[381 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmOffsetMinDecr','FontSize',pars.fontSize);
fm.proc.ppmOffsetMin     = uicontrol('Style','Edit','Position', [399 242 40 18],'String',sprintf('%.2f',proc.ppmOffsetMin),...
                                     'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_OffsetPpmWinUpdate');
fm.proc.ppmOffsetMinIncr = uicontrol('Style','Pushbutton','String','+','Position',[439 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmOffsetMinIncr','FontSize',pars.fontSize);
fm.proc.ppmOffsetMaxDecr = uicontrol('Style','Pushbutton','String','-','Position',[462 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmOffsetMaxDecr','FontSize',pars.fontSize);
fm.proc.ppmOffsetMax     = uicontrol('Style','Edit','Position', [480 242 40 18],'String',sprintf('%.2f',proc.ppmOffsetMax),...
                                     'FontSize',pars.fontSize,'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_OffsetPpmWinUpdate');
fm.proc.ppmOffsetMaxIncr = uicontrol('Style','Pushbutton','String','+','Position',[520 242 18 18],'FontWeight','bold','Callback','SP2_Proc_PpmOffsetMaxIncr','FontSize',pars.fontSize);
fm.proc.offsetValFlag    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Value', ...
                                     'Value',~flag.procOffset,'Position',[.540 .30 .10 .03],'Callback','SP2_Proc_OffsetValueFlagUpdate','FontSize',pars.fontSize);
fm.proc.offsetDec3    = uicontrol('Style','Pushbutton','String','<<<','Position',[381 213 22 18],'FontWeight','bold','Callback','SP2_Proc_OffsetDec3','FontSize',pars.fontSize);
fm.proc.offsetDec2    = uicontrol('Style','Pushbutton','String','<<','Position',[403 213 22 18],'FontWeight','bold','Callback','SP2_Proc_OffsetDec2','FontSize',pars.fontSize);
fm.proc.offsetDec1    = uicontrol('Style','Pushbutton','String','<','Position',[425 213 22 18],'FontWeight','bold','Callback','SP2_Proc_OffsetDec1','FontSize',pars.fontSize);
fm.proc.offsetVal     = uicontrol('Style','Edit','Position', [447 213 70 18],'String',num2str(proc.offsetVal),'BackGroundColor',pars.bgColor, ...
                                  'Callback','SP2_Proc_OffsetValueUpdate','FontSize',pars.fontSize);
fm.proc.offsetInc1    = uicontrol('Style','Pushbutton','String','>','Position',[517 213 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_OffsetInc1');
fm.proc.offsetInc2    = uicontrol('Style','Pushbutton','String','>>','Position',[539 213 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_OffsetInc2');
fm.proc.offsetInc3    = uicontrol('Style','Pushbutton','String','>>>','Position',[561 213 22 18],'FontSize',pars.fontSize,'FontWeight','bold','Callback','SP2_Proc_OffsetInc3');
fm.proc.offsetReset   = uicontrol('Style','Pushbutton','String','Zero','Position',[381 193 60 18],...
                                  'FontSize',pars.fontSize,'Callback','SP2_Proc_OffsetZero','TooltipString',sprintf('Reset of amplitude offset\nfor SNR, FWHM & Integral calcuations'));
fm.proc.offsetAssign  = uicontrol('Style','Pushbutton','String','Assign','Position',[441 193 60 18],'FontSize',pars.fontSize,'Callback','SP2_Proc_OffsetAssign',...
                                  'TooltipString',sprintf('Manual assignment of amplitude offset\nfor SNR, FWHM & Integral calcuations'));
                              
%--- analysis options ---
fm.proc.anaLab       = text('Position',[-0.13, 0.20],'String','Analysis','FontSize',pars.fontSize);
fm.proc.anaSNR       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','SNR', ...
                                 'Value',flag.procAnaSNR,'Position',[.13 .26 .15 .03],'Callback','SP2_Proc_AnaSnrUpdate',...
                                 'TooltipString',sprintf('Signal-to-noise analysis of selected spectrum'),'FontSize',pars.fontSize);
fm.proc.anaFWHM      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','FWHM', ...
                                 'Value',flag.procAnaFWHM,'Position',[.23 .26 .15 .03],'Callback','SP2_Proc_AnaFwhmUpdate',...
                                 'TooltipString',sprintf('Full width at half maximum (FWHM) analysis of selected spectrum'),'FontSize',pars.fontSize);
fm.proc.anaIntegr    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Integral', ...
                                 'Value',flag.procAnaIntegr,'Position',[.33 .26 .15 .03],'Callback','SP2_Proc_AnaIntegralUpdate',...
                                 'TooltipString',sprintf('Spectral integration of selected spectrum'),'FontSize',pars.fontSize);
fm.proc.anaSignPos   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','(+)', ...
                                 'Value',flag.procAnaSign,'Position',[.13 .23 .15 .03],'Callback','SP2_Proc_AnaSignPositiveUpdate',...
                                 'TooltipString',sprintf('Perform SNR/FWHM/integration analysis for peak of positive polarity'),'FontSize',pars.fontSize);
fm.proc.anaSignNeg   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','(-)', ...
                                 'Value',~flag.procAnaSign,'Position',[.20 .23 .15 .03],'Callback','SP2_Proc_AnaSignNegativeUpdate',...
                                 'TooltipString',sprintf('Perform SNR/FWHM/integration analysis for peak of negative polarity'),'FontSize',pars.fontSize);
fm.proc.anaAbsOfReal = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','| Real |','FontSize',pars.fontSize, ...
                                 'Value',flag.procAnaAbsOfReal,'Position',[.265 .23 .15 .03],'Callback','SP2_Proc_AnaAbsOfRealUpdate',...
                                 'TooltipString',sprintf('Substitute real part of spectrum by magnitude of real part for integral analysis\nas opposed to true magnitude mode which also considers the imaginary part\n(Note that this is a very specific case and the default of this flag should be OFF!)'));
fm.proc.anaFrequDiff = uicontrol('Style','Pushbutton','String','Delta','Position',[262 186 40 18],'FontSize',pars.fontSize,...
                                 'FontName','Helvetica','Callback','SP2_Proc_AnaFrequDifference',...
                                 'TooltipString',sprintf('Measurement of frequency difference between two spectral positions'));
                          
%--- polynomial baseline correction ---
fm.proc.baseCorr  = uicontrol('Style','Pushbutton','String','Baseline Handling','FontWeight','bold','Position',[10 130 130 18],...
                              'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_BaseMain',...
                              'TooltipString',sprintf('Open window for baseline handling'));
% if ~flag.compile4publ
    fm.proc.ecc   = uicontrol('Style','Pushbutton','String','ECC','Position',[10 110 50 18],...
                              'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ApplyKloseCorr;',...
                              'TooltipString',sprintf('Apply Klose eddy-current correction'));
% end

%--- spectrum alignment ---
fm.proc.spec1Align       = uicontrol('Style','Pushbutton','String','Align 1','FontWeight','bold','Position',[210 140 60 18],...
                                     'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_AlignSpec1;',...
                                     'TooltipString',sprintf('Automated alignment of spectrum 1 with spectrum 2.\n \nFormat selection:\nReal -> real part\nImag -> imaginary part\nMagn -> magnitude\nPhase -> real and imaginary part (!)'));
fm.proc.spec2Align       = uicontrol('Style','Pushbutton','String','Align 2','FontWeight','bold','Position',[270 140 60 18],...
                                     'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_AlignSpec2;',...
                                     'TooltipString',sprintf('Automated alignment of spectrum 2 with spectrum 1.\n \nFormat selection:\nReal -> real part\nImag -> imaginary part\nMagn -> magnitude\nPhase -> real and imaginary part (!)'));
fm.proc.alignAmpWeight   = uicontrol('Style','Edit','Position', [330 140 50 18],'String',sprintf('%.4f',proc.alignAmpWeight),...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_AlignAmpWeightUpdate','FontSize',pars.fontSize,...
                                     'TooltipString',sprintf('Amplitude weighting for spectrum alignment:\n1: regular least-squares\n>1: emphasis on peak suppression\n<1: emphasis on noise suppression'));
fm.proc.alignPpmStr      = uicontrol('Style','Edit','Position', [210 120 170 18],'String',proc.alignPpmStr,'BackGroundColor',pars.bgColor, ...
                                     'Callback','SP2_Proc_AlignPpmStrUpdate;','FontSize',pars.fontSize,...
                                     'TooltipString',sprintf('Frequency range(s) in ppm for spectrum alignment\n(e.g. 1.2:1.8 7:8.3)'));            
fm.proc.alignLbFlag      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','LB',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignLb==1,...
                                     'Position',[.66 .198 .13 .03],'Callback','SP2_Proc_AlignLbFlagUpdate',...
                                     'TooltipString',sprintf('Include exponential line broadening [Hz]\nin spectrum alignment procedure'));
fm.proc.alignGbFlag      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','GB',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignGb==1,...
                                     'Position',[.77 .198 .13 .03],'Callback','SP2_Proc_AlignGbFlagUpdate',...
                                     'TooltipString',sprintf('Include Gaussian line broadening [Hz]\nin spectrum alignment procedure'));
fm.proc.alignPhc0Flag    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','PHC0',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignPhc0==1,...
                                     'Position',[.88 .198 .13 .03],'Callback','SP2_Proc_AlignPhc0FlagUpdate',...
                                     'TooltipString',sprintf('Include zero order phase correction [deg]\nin spectrum alignment procedure'));
fm.proc.alignPhc1Flag    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','PHC1',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignPhc1==1,...
                                     'Position',[.66 .166 .13 .03],'Callback','SP2_Proc_AlignPhc1FlagUpdate',...
                                     'TooltipString',sprintf('Include first order phase correction [deg]\nin spectrum alignment procedure'));
fm.proc.alignScaleFlag   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','Scale',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignScale==1,...
                                     'Position',[.77 .166 .13 .03],'Callback','SP2_Proc_AlignScaleFlagUpdate',...
                                     'TooltipString',sprintf('Include amplitude scaling [1]\nin spectrum alignment procedure'));
fm.proc.alignShiftFlag   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','Shift',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignShift==1,...
                                     'Position',[.88 .166 .13 .03],'Callback','SP2_Proc_AlignShiftFlagUpdate',...
                                     'TooltipString',sprintf('Include spectral shift [Hz]\nin spectrum alignment procedure'));
fm.proc.alignMaxIterLab  = text('Position',[0.25, 0.048],'String','Iter','FontSize',pars.fontSize);
fm.proc.alignMaxIter     = uicontrol('Style','Edit','Position', [219 97 38 18],'String',sprintf('%g',proc.alignMaxIter),...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_AlignMaxIterUpdate',...
                                     'TooltipString',sprintf('Maximum number of iterations for least-squares optimization'),'FontSize',pars.fontSize);
fm.proc.alignTolFunLab   = text('Position',[0.405, 0.048],'String','Tol','FontSize',pars.fontSize);
fm.proc.alignTolFun      = uicontrol('Style','Edit','Position', [290 97 38 18],'String',sprintf('%g',proc.alignTolFun),...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_AlignTolFunUpdate',...
                                     'TooltipString',sprintf('Tolerance range of least-squares optimization'),'FontSize',pars.fontSize);
fm.proc.alignOffsetFlag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','Offset',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignOffset==1,...
                                     'Position',[.56 .134 .13 .03],'Callback','SP2_Proc_AlignOffsetFlagUpdate',...
                                     'TooltipString',sprintf('Include baseline offset [a.u.]\nin spectrum alignment procedure'),'FontSize',pars.fontSize);
fm.proc.alignPolyFlag    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','Polyn',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignPoly==1,...
                                     'Position',[.66 .134 .18 .03],'Callback','SP2_Proc_AlignPolyFlagUpdate',...
                                     'TooltipString',sprintf('Include polynomial function\nin spectrum alignment procedure'),'FontSize',pars.fontSize);
fm.proc.alignPolyOrdDec  = uicontrol('Style','Pushbutton','String','-','Position',[453 97 18 18],'FontWeight','bold','Callback','SP2_Proc_AlignPolyOrderDec');
fm.proc.alignPolyOrder   = uicontrol('Style','Edit','Position', [471 97 28 18],'String',sprintf('%.0f',proc.alignPolyOrder),...
                                     'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_AlignPolyOrderUpdate',...
                                     'TooltipString',sprintf('Order of polynomial included\nin spectra alignment'),'FontSize',pars.fontSize);
fm.proc.alignPolyOrdInc  = uicontrol('Style','Pushbutton','String','+','Position',[499 97 18 18],'FontWeight','bold','Callback','SP2_Proc_AlignPolyOrderInc');
fm.proc.alignStretchFlag = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'String','Stretch',...
                                     'FontSize',pars.fontSize,'Units','Normalized','Value',flag.procAlignStretch==1,...
                                     'Position',[.88 .134 .13 .03],'Callback','SP2_Proc_AlignStretchFlagUpdate',...
                                     'TooltipString',sprintf('Include spectral stretch [Hz/ppm]\nin spectrum alignment procedure'),'FontSize',pars.fontSize);

%--- spectral processing ---
fm.proc.plotFid1Orig = uicontrol('Style','Pushbutton','String','FID 1 Orig','FontWeight','bold','Position',[10 80 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotFid1Orig(1);',...
                                 'TooltipString',sprintf('Show original FID 1 before data manipulation'));
fm.proc.plotFid2Orig = uicontrol('Style','Pushbutton','String','FID 2 Orig','FontWeight','bold','Position',[95 80 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotFid2Orig(1);',...
                                 'TooltipString',sprintf('Show original FID 2 before data manipulation'));
fm.proc.plotFid1     = uicontrol('Style','Pushbutton','String','FID 1','FontWeight','bold','Position',[10 60 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotFid1(1);',...
                                 'TooltipString',sprintf('Show FID 1 including data manipulation'));
fm.proc.plotFid2     = uicontrol('Style','Pushbutton','String','FID 2','FontWeight','bold','Position',[95 60 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotFid2(1);',...
                                 'TooltipString',sprintf('Show FID 2 including data manipulation'));
fm.proc.procData1    = uicontrol('Style','Pushbutton','String','Proc 1','FontWeight','bold','Position',[10 40 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcData1(1);',...
                                 'TooltipString',sprintf('Explicit data processing of FID 1'));
fm.proc.procData2    = uicontrol('Style','Pushbutton','String','Proc 2','FontWeight','bold','Position',[95 40 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcData2(1);',...
                                 'TooltipString',sprintf('Explicit data processing of FID 2'));
fm.proc.plotSpec1    = uicontrol('Style','Pushbutton','String','Spec 1','FontWeight','bold','Position',[10 20 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotSpec1(1);',...
                                 'TooltipString',sprintf('Show spectrum 1'));
fm.proc.plotSpec2    = uicontrol('Style','Pushbutton','String','Spec 2','FontWeight','bold','Position',[95 20 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotSpec2(1);',...
                                 'TooltipString',sprintf('Show spectrum 2'));

%--- FID combinations ---                             
fm.proc.fidSuperpos  = uicontrol('Style','Pushbutton','String','FID Super','FontWeight','bold','Position',[180 60 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotFidSuperpos(1);',...
                                 'TooltipString',sprintf('Show superposition of FIDs 1 and 2'));
fm.proc.fidSum       = uicontrol('Style','Pushbutton','String','FID Sum','FontWeight','bold','Position',[180 40 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotFidSum(1);',...
                                 'TooltipString',sprintf('Show sum of FIDs 1 and 2'));
fm.proc.fidDiff      = uicontrol('Style','Pushbutton','String','FID Diff','FontWeight','bold','Position',[180 20 80 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotFidDiff(1);',...
                                 'TooltipString',sprintf('Show FID difference (FID 1 - FID 2)'));

%--- spectrum combinations ---
fm.proc.specSuperpos = uicontrol('Style','Pushbutton','String','Spec Super','FontWeight','bold','Position',[265 60 90 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotSpecSuperpos(1);',...
                                 'TooltipString',sprintf('Show superposition of spectra 1 and 2'));
fm.proc.specSum      = uicontrol('Style','Pushbutton','String','Spec Sum','FontWeight','bold','Position',[265 40 90 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotSpecSum(1);',...
                                 'TooltipString',sprintf('Show sum of spectra 1 and 2'));
fm.proc.specDiff     = uicontrol('Style','Pushbutton','String','Spec Diff','FontWeight','bold','Position',[265 20 90 20],...
                                 'FontSize',pars.fontSize,'FontName','Helvetica','Callback','SP2_Proc_ProcAndPlotSpecDiff(1);',...
                                 'TooltipString',sprintf('Show difference spectrum (1 minus 2)'));

%--- freeze/keep figure ---
fm.proc.updateCalc   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Update', ...
                                 'Value',flag.procUpdateCalc,'Position',[.62 .085 .12 .03],'Callback','SP2_Proc_UpdateCalcUpdate',...
                                 'TooltipString',sprintf('Automated processing if needed and update every time a parameter is changed'),'FontSize',pars.fontSize);
fm.proc.keepFigure   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Keep', ...
                                 'Value',flag.procKeepFig,'Position',[.62 .055 .10 .03],'Callback','SP2_Proc_KeepFigureUpdate',...
                                 'TooltipString',sprintf('1: figures are kept, ie. parameter changes are plotted to new figures\n0: Parameter changes are updated in the same figure'),'FontSize',pars.fontSize);
fm.proc.verbose      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.verbose,...
                                 'String','Verbose','Position',[0.62 0.025 .17 .03],'Callback','SP2_Proc_VerboseFlagUpdate','FontSize',pars.fontSize);

%--- apply/ignore polynomial baseline ---
fm.proc.applyPoly1   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Poly 1','FontSize',pars.fontSize, ...
                                 'Value',flag.procApplyPoly1,'Position',[.74 .085 .12 .03],'Callback','SP2_Proc_ApplyPoly1Update',...
                                 'TooltipString',sprintf('Apply/ignore the polynomial baseline\ndetermined by the spetrum alignment procedure\nfor the processing of spectrum 1'));
fm.proc.applyPoly2   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Poly 2','FontSize',pars.fontSize, ...
                                 'Value',flag.procApplyPoly2,'Position',[.74 .055 .12 .03],'Callback','SP2_Proc_ApplyPoly2Update',...
                                 'TooltipString',sprintf('Apply/ignore the polynomial baseline\ndetermined by the spetrum alignment procedure\nfor the processing of spectrum 2'));

%--- clear all spectral processing figures ---                              
fm.proc.closeProcFigs = uicontrol('Style','Pushbutton','String','X Figs','Position',[445 20 56 18],'Callback','SP2_Proc_CloseProcFigures;',...
                                  'TooltipString',sprintf('Close all spectral processing figures'),'FontSize',pars.fontSize);

                             
%--- additional analysis options ---
fm.proc.jdeEffWin    = uicontrol('Style','Pushbutton','String','JDE Eff.','Position',[520 60 70 20],'Callback','SP2_Proc_JdeEfficiencyMain',...
                                 'TooltipString',sprintf('JDE efficiency determination for GABA'),'FontSize',pars.fontSize);
% fm.proc.special      = uicontrol('Style','Pushbutton','String','SPECIAL','Position',[520 20 65 20],'Callback','SP2_Proc_SPECIAL',...
%                                  'TooltipString',sprintf('SPECIAL'));
fm.proc.convPar2mat  = uicontrol('Style','Pushbutton','String','.par 2 .mat','Position',[520 40 70 20],'Callback','SP2_Proc_ConvertPar2Mat;','FontSize',pars.fontSize,...
                                 'TooltipString',sprintf('Perform data conversion from .par to .mat for\nall data sets found in the directory of data set 1.\nThe results are written to the export directory.\nNote that the processing selected for data set 1 is applied.'));
fm.proc.convExtStr   = uicontrol('Style','Edit','Position', [520 20 45 18],'String',sprintf('%s',proc.convExtStr),'FontSize',pars.fontSize,...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_Proc_ConvExtStrUpdate',...
                                 'TooltipString',sprintf('Potential file extension for above .par-to-.mat data conversion'));
fm.proc.batch1minus2 = uicontrol('Style','Pushbutton','String','1-2','Position',[565 20 25 20],'Callback','SP2_Proc_Batch1Minus2;','FontSize',pars.fontSize,...
                                 'TooltipString',sprintf('Perfrom batch calculuation and file handling:\nData set 1 minus data set 2 for all FIDs that exist in both directories.\nResults are written to the export directory.\n(Note: .mat format only)'));

  
                             
                             
%--- window update ---
SP2_Proc_ProcessWinUpdate
