%--- exponential fitting function ---
function f = SP2_MM_FunExp06_T1fix_offset(a,x)

global loggingfile mm

f = a(1) * (1 - exp(-(x-mm.xOff)/mm.anaTOne(1))) + ...
    a(2) * (1 - exp(-(x-mm.xOff)/mm.anaTOne(2))) + ...
    a(3) * (1 - exp(-(x-mm.xOff)/mm.anaTOne(3))) + ...
    a(4) * (1 - exp(-(x-mm.xOff)/mm.anaTOne(4))) + ...
    a(5) * (1 - exp(-(x-mm.xOff)/mm.anaTOne(5))) + ...
    a(6) * (1 - exp(-(x-mm.xOff)/mm.anaTOne(6))) + mm.yOff;
       


