%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
    function SP2_MM_MacroMain
%% 
%%  Main window for the metabolite / macromolecule (MM) separation.
%%
%%  01-2014, Christoph Juchem
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global fm fmfig pars mm flag


SP2_ClearWindow
flag.fmWin = 3;
pars.figPos = get(fmfig,'Position');
set(fmfig,'Name',' INSPECTOR: Macromolecule / Metabolite Separation','Position',...
    [pars.figPos(1) pars.figPos(2) pars.mainDims(3) pars.mainDims(4)])

%--- pre-processing ---
fm.mm.alignDetails = uicontrol('Style','Pushbutton','String','Alignment Details','Position',[27 670 183 18],'Callback','SP2_MM_AlignDetailsMain',...
                               'TooltipString',sprintf('Start setup page to define criteria for\n phase and frequency alignment.\n'));
fm.mm.expLbLab     = text('Position',[-0.11, 0.985],'String','Line broadening','FontSize',pars.fontSize);
fm.mm.expLbVal     = uicontrol('Style','Edit','Position', [160 632 50 18],'String',num2str(mm.lb),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Exponential line broadening [Hz]');
fm.mm.fftCutLab    = text('Position',[-0.11, 0.945],'String','Apodization','FontSize',pars.fontSize);
fm.mm.fftCutVal    = uicontrol('Style','Edit','Position', [160 609 50 18],'String',num2str(mm.cut),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Spectral apodization [pts]');
fm.mm.fftZfLab     = text('Position',[-0.11, 0.905],'String','Zero filling','FontSize',pars.fontSize);
fm.mm.fftZfVal     = uicontrol('Style','Edit','Position', [160 586 50 18],'String',num2str(mm.zf),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Spectral zero-filling [pts]');
fm.mm.ppmCalibLab  = text('Position',[-0.11, 0.865],'String','ppm reference','FontSize',pars.fontSize);
fm.mm.ppmCalib     = uicontrol('Style','Edit','Position', [160 563 50 18],'String',sprintf('%.2f',mm.ppmCalib),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Number of rows in spectra display');
fm.mm.phaseZeroLab = text('Position',[-0.11, 0.825],'String','Zero Phase','FontSize',pars.fontSize);
fm.mm.phaseZeroDec = uicontrol('Style','Pushbutton','String','-','Position',[142 540 18 18],'Callback','SP2_MM_RecoZeroPhaseDec',...
                               'TooltipString','PHC0 reduction by 10 degrees');
fm.mm.phaseZero    = uicontrol('Style','Edit','Position', [160 540 50 18],'String',num2str(mm.phaseZero),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Global zero-order phase offset [deg]');
fm.mm.phaseZeroInc = uicontrol('Style','Pushbutton','String','+','Position',[210 540 18 18],'Callback','SP2_MM_RecoZeroPhaseInc',...
                               'TooltipString','PHC0 increase by 10 degrees');
% fm.mm.dataMetab    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Metabolites', ...
%                                'Value',flag.mmMetabRef,'Position',[.04 .765 .23 .03],'Callback','SP2_MM_DataMetabUpdate',...
%                                'TooltipString','Data type: Metabolite spectra');
% fm.mm.dataRef      = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Reference', ...
%                                'Value',~flag.mmMetabRef,'Position',[.19 .765 .23 .03],'Callback','SP2_MM_DataRefUpdate',...
%                                'TooltipString','Data type: Reference (water) spectra');
fm.mm.boxCarLab    = text('Position',[-0.11, 0.785],'String','Box Car Average','FontSize',pars.fontSize);
fm.mm.boxCar       = uicontrol('Style','Edit','Position', [160 517 50 18],'String',num2str(mm.boxCar),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString',sprintf('Box car window for spectral smoothing [# pts]\n(Applied in T1 analysis!)'));
fm.mm.boxCarHz     = text('Position',[0.3, 0.78],'String',sprintf('/ %.1f Hz',mm.boxCarHz));

%--- load data ---
fm.mm.dataRecoAll = uicontrol('Style','Pushbutton','String','Reco Complete','Position',[330 670 265 18],'Callback','SP2_MM_DataRecoAll;',...
                              'TooltipString','Combine all steps from row of buttons below');
fm.mm.dataLoad    = uicontrol('Style','Pushbutton','String','Load','Position',[330 650 60 18],'Callback','SP2_MM_DataLoad;',...
                              'TooltipString','Load saturation-recovery data from ''Data'' page');
fm.mm.dataResort  = uicontrol('Style','Pushbutton','String','Resort','Position',[390 650 60 18],'Callback','SP2_MM_DataResort;',...
                              'TooltipString','Resort saturation-recovery data with ascending delays');
fm.mm.dataCorr    = uicontrol('Style','Pushbutton','String','Corr','Position',[450 650 60 18],'Callback','SP2_MM_DataCorr(1);',...
                              'TooltipString','Phase and frequency correction of saturation-recovery spectra');
fm.mm.dataReco    = uicontrol('Style','Pushbutton','String','Reco','Position',[510 650 60 18],'Callback','SP2_MM_DataReco;',...
                              'TooltipString','Spectrum reconstruction');
fm.mm.dataExtFac  = uicontrol('Style','Edit','Position', [570 650 25 18],'String',num2str(mm.dataExtFac),...
                              'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                              'TooltipString','Data extension factor');
fm.mm.simSinglets = uicontrol('Style','Pushbutton','String','Simulate Singlets','Position',[330 620 110 18],'Callback','SP2_MM_DoSimulation(1);',...
                              'TooltipString','Simulate saturation-recovery data set for (noise-free) singlets');
fm.mm.simReal     = uicontrol('Style','Pushbutton','String','Basic','Position',[440 620 60 18],'Callback','SP2_MM_DoSimulation(2);',...
                              'TooltipString',sprintf('Simulate saturation-recovery data set for (noisy)\ncombination of humps and peaks'));
fm.mm.simNoise    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Add Noise', ...
                              'Value',flag.mmSimNoise,'Position',[.85 .879 .2 .03],'Callback','SP2_MM_SimNoiseUpdate');
fm.mm.simMetab    = uicontrol('Style','Pushbutton','String','Simulate Metab','Position',[330 600 110 18],'Callback','SP2_MM_DoMetabSimulation;',...
                              'TooltipString',sprintf('Simulate saturation-recovery data set for (noisy)\n1H metabolite of the human brain\n(default: NAA)'));
fm.mm.simMetabAll = uicontrol('Style','Pushbutton','String','All Metabs','Position',[440 600 80 18],'Callback','SP2_MM_DoMetabSimAll;',...
                              'TooltipString',sprintf('Simulate saturation-recovery data set for all\n1H metabolites of the human brain'));
fm.mm.simMetabBrain = uicontrol('Style','Pushbutton','String','Brain','Position',[520 600 75 18],'Callback','SP2_MM_DoMetabSimBrain;',...
                                'TooltipString',sprintf('Simulate saturation-recovery data set for all\n1H metabolites of the human brain'));
fm.mm.simFidPath    = uicontrol('Style','Edit','Position', [330 580 215 18],'String',mm.sim.fidPath, ...
                                'HorizontalAlignment','Left','Callback','SP2_MM_SimFidPathUpdate',...
                                'TooltipString','File path of single FID for simulation of single-metabolite sat-rec. array');
fm.mm.simFidSelect  = uicontrol('Style','Pushbutton','String','Select','Position',[545 580 50 18],'Callback','SP2_MM_SimFidSelect;',...
                                'TooltipString','Select single FID file for simulation of single-metabolite sat-rec. array');

%--- delay handling for sat-rec. simulation ---                            
fm.mm.simDelayLab  = text('Position',[0.43, 0.825],'String','Delays','FontSize',pars.fontSize);
fm.mm.simDelayMin  = uicontrol('Style','Edit','Position', [330 540 40 18],'String',num2str(mm.sim.delayMin),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Shortest saturation-recovery delay [sec] for simulation of FID array');
fm.mm.simDelayMax  = uicontrol('Style','Edit','Position', [370 540 40 18],'String',num2str(mm.sim.delayMax),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Longest saturation-recovery delay [sec] for simulation of FID array');
fm.mm.simDelayNLab = text('Position',[0.74, 0.825],'String','N','FontSize',pars.fontSize);
fm.mm.simDelayN    = uicontrol('Style','Edit','Position', [440 540 40 18],'String',num2str(mm.sim.delayN),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                               'TooltipString','Number of saturation-recovery delays for simulation of FID array');
fm.mm.simLinDelays = uicontrol('Style','Pushbutton','String','Linear','Position',[505 540 45 18],'Callback','SP2_MM_SimDelayCreateLinear',...
                               'TooltipString','Define linear vector of saturation-recovery delays between min/max');
fm.mm.simLogDelays = uicontrol('Style','Pushbutton','String','Log','Position',[550 540 45 18],'Callback','SP2_MM_SimDelayCreateLog',...
                               'TooltipString','Define log-scale vector of saturation-recovery delays between min/max');
fm.mm.simDelayStr  = uicontrol('Style','Edit','Position', [280 520 315 18],'String',mm.sim.delayStr,...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_MM_SimDelayStrUpdate',...
                               'TooltipString',sprintf('Delay selection for simulation of sat-rec. FID array [sec]'));             
                           
%--- saturation-recovery efficiency analysis ---
fm.mm.effAna = uicontrol('Style','Pushbutton','String','Sat. Efficiency','Position',[450 480 120 18],'Callback','SP2_MM_DoSatEffAnalysis;',...
                         'TooltipString','Efficiency analysis of saturation module');
                           
%--- analysis options ---
fm.mm.anaH2oRmLab    = text('Position',[-0.11, 0.7],'String','Water removal','FontSize',pars.fontSize);
fm.mm.anaH2oHLSVD    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAnaWaterMode,...
                                 'String','HLSVD','Position',[.24 .664 .2 .03],'Callback','SP2_MM_AnaWaterRmHlsvdUpdate',...
                                 'TooltipString',sprintf('HLSVD'),'Enable','off');
fm.mm.anaH2oLowPass  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',~flag.mmAnaWaterMode,...
                                 'String','Low-pass Filter','Position',[.36 .664 .3 .03],'Callback','SP2_MM_AnaWaterRmLowPassUpdate',...
                                 'TooltipString',sprintf('Low-pass filter'),'Enable','off');
fm.mm.anaFrequLab    = text('Position',[-0.11, 0.648],'String','Frequency','FontSize',pars.fontSize);
fm.mm.anaFrequGlobal = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAnaFrequMode,...
                                 'String','Global','Position',[.24 .622 .2 .03],'Callback','SP2_MM_AnaFrequGlobalUpdate',...
                                 'TooltipString',sprintf('Global frequency range'));
fm.mm.anaFrequDirect = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',~flag.mmAnaFrequMode,...
                                 'String','Direct','Position',[.36 .622 .03 .03],'Callback','SP2_MM_AnaFrequDirectUpdate',...
                                 'TooltipString',sprintf('Direct assignment of frequency range'));
fm.mm.anaFrequMin    = uicontrol('Style','Edit','Position', [240 440 50 18],'String',num2str(mm.anaFrequMin),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                 'TooltipString','Lower frequency limit [ppm]');
fm.mm.anaFrequMax    = uicontrol('Style','Edit','Position', [290 440 50 18],'String',num2str(mm.anaFrequMax),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                 'TooltipString','Upper frequency limit [ppm]');
% fm.mm.anaFormatLab   = text('Position',[-0.11, 0.596],'String','Format','FontSize',pars.fontSize);
% fm.mm.anaFormatReal  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Real', ...
%                                  'Value',flag.mmAnaFormat,'Position',[.24 .58 .2 .03],'Callback','SP2_MM_AnaFormatRealUpdate');
% fm.mm.anaFormatMagn  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Magn', ...
%                                  'Value',~flag.mmAnaFormat,'Position',[.34 .58 .2 .03],'Callback','SP2_MM_AnaFormatMagnUpdate');
fm.mm.anaTOneModeLab = text('Position',[-0.11, 0.596],'String','T1 Mode','FontSize',pars.fontSize);
fm.mm.anaTOneModeFix  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Fixed', ...
                                  'Value',flag.mmAnaTOneMode,'Position',[.24 .58 .2 .03],'Callback','SP2_MM_AnaTOneModeFixedUpdate');
fm.mm.anaTOneModeFlex = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Flexible', ...
                                  'Value',~flag.mmAnaTOneMode,'Position',[.34 .58 .2 .03],'Callback','SP2_MM_AnaTOneModeFlexibleUpdate');
fm.mm.anaTOneFlexN    = uicontrol('Style','Edit','Position', [270 410 40 18],'String',num2str(mm.anaTOneFlexN),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                  'TooltipString','Number of T1 components for flexible fitting');
fm.mm.anaTOneFlexThLab = text('Position',[0.55, 0.596],'String','Threshold','FontSize',pars.fontSize);
fm.mm.anaTOneFlexThMin = uicontrol('Style','Edit','Position', [400 410 40 18],'String',num2str(mm.anaTOneFlexThMin),...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                   'TooltipString','Maximum threshold in [sec] of short T1 range');
fm.mm.anaTOneFlexThMax = uicontrol('Style','Edit','Position', [440 410 40 18],'String',num2str(mm.anaTOneFlexThMax),...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                   'TooltipString','Minimum threshold in [sec] of long T1 range');
fm.mm.anaTOneLab     = text('Position',[-0.11, 0.544],'String',sprintf('T1 selection (%.0f)',mm.anaTOneN),'FontSize',pars.fontSize);
fm.mm.anaTOneStr     = uicontrol('Style','Edit','Position', [147 380 400 18],'String',mm.anaTOneStr,...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_AnaTOneStrUpdate',...
                                 'TooltipString',sprintf('T1 selection for metabolite/MM fitting [sec]'));             

                             
%--- T1 analysis ---
fm.mm.doT1Ana  = uicontrol('Style','Pushbutton','String','T1 Analysis','Position',[30 335 80 18],'Callback','SP2_MM_DoT1Analysis;',...
                           'TooltipString','Perform T1 analysis of saturation-recovery data set');
fm.mm.anaOptNLab      = text('Position',[0.15, 0.465],'String','N Opt','FontSize',pars.fontSize);
fm.mm.anaOptN         = uicontrol('Style','Edit','Position', [190 335 35 18],'String',num2str(mm.anaOptN),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                  'TooltipString','Number of optimization steps per spectral point');
fm.mm.anaOptAmpRgLab  = text('Position',[0.37, 0.465],'String','Range','FontSize',pars.fontSize);
fm.mm.anaOptAmpRg     = uicontrol('Style','Edit','Position', [295 335 40 18],'String',num2str(mm.anaOptAmpRg),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                  'TooltipString','Relative amplitude range around first init/fit');
fm.mm.anaOptAmpRedLab = text('Position',[0.60, 0.465],'String','Reduction','FontSize',pars.fontSize);
fm.mm.anaOptAmpRed    = uicontrol('Style','Edit','Position', [422 335 40 18],'String',num2str(mm.anaOptAmpRed),...
                                  'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                  'TooltipString','Relative reduction of considered amplitude range');
fm.mm.neighInit       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Neighbor Init', ...
                                  'Value',flag.mmNeighInit,'Position',[.80 .475 .18 .03],'Callback','SP2_MM_NeighborInitUpdate',...
                                  'TooltipString','Init multi-exponential fit result from neighboring frequency');
                    
                       
%--- load/save full mm structure ---
fm.mm.mmStructPath   = uicontrol('Style','Edit','Position', [147 310 433 18],'String',mm.mmStructPath, ...
                                 'HorizontalAlignment','Left','Callback','SP2_MM_MmStructPathUpdate',...
                                 'TooltipString','File path of full data structure');
fm.mm.mmStructSelect = uicontrol('Style','Pushbutton','String','Select','Position',[380 292 50 18],'Callback','SP2_MM_MmStructSelect;',...
                                 'TooltipString','Select file to load/save full data structure');
fm.mm.mmStructSave   = uicontrol('Style','Pushbutton','String','Save','Position',[430 292 50 18],'Callback','SP2_MM_MmStructSave;',...
                                 'TooltipString','Save full data structure to file');
fm.mm.mmStructLoad   = uicontrol('Style','Pushbutton','String','Load','Position',[480 292 50 18],'Callback','SP2_MM_MmStructLoad;',...
                                 'TooltipString','Load full data structure from file');
fm.mm.mmStructShow   = uicontrol('Style','Pushbutton','String','Show','Position',[530 292 50 18],'Callback','SP2_MM_MmStructShow;',...
                                 'TooltipString','Display current ''mm'' structure');
                                   
%--- analysis/visualization: saturation-recovery ---
fm.mm.satRecLab        = text('Position',[-0.11, 0.326],'String','Sat. Recovery','FontSize',pars.fontSize);
fm.mm.satRecFidSingle  = uicontrol('Style','Pushbutton','String','FID','Position',[120 255 60 18],'Callback','SP2_MM_SatRecShowFidSingle(1);',...
                                   'TooltipString','Show single saturation-recovery spectrum');
fm.mm.satRecSpecSingle = uicontrol('Style','Pushbutton','String','Spec','Position',[180 255 60 18],'Callback','SP2_MM_SatRecShowSpecSingle(1);',...
                                  'TooltipString','Show single saturation-recovery spectrum');
fm.mm.satRecSelDecr    = uicontrol('Style','Pushbutton','String','<<','Position',[120 235 30 18],'Callback','SP2_MM_SatRecSelectDecr',...
                                   'TooltipString','Scroll downwards through the saturation-recovery acquisitions');
fm.mm.satRecSelect     = uicontrol('Style','Edit','Position', [150 235 40 18],'String',num2str(mm.satRecSelect),...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MM_SatRecSelectUpdate',...
                                   'TooltipString','Number of saturation-delay to be displayed');
fm.mm.satRecSelIncr    = uicontrol('Style','Pushbutton','String','>>','Position',[190 235 30 18],'Callback','SP2_MM_SatRecSelectIncr',...
                                   'TooltipString','Scroll upwards through the saturation-recovery acquisitions');
fm.mm.satRecShowSuper  = uicontrol('Style','Pushbutton','String','Superpos','Position',[260 255 70 18],'Callback','SP2_MM_SatRecShowSpecSuper(1);',...
                                   'TooltipString','Visualize spectrum superposition');
fm.mm.satRecShowArray  = uicontrol('Style','Pushbutton','String','Array','Position',[330 255 50 18],'Callback','SP2_MM_SatRecShowSpecArray(1);',...
                                   'TooltipString','Visualize spectrum array');
fm.mm.satRecShowSum    = uicontrol('Style','Pushbutton','String','Sum','Position',[380 255 50 18],'Callback','SP2_MM_SatRecShowSpecSum(1);',...
                                   'TooltipString','Visualize summation spectrum');
fm.mm.satRecShowSubtr  = uicontrol('Style','Pushbutton','String','Subtract','Position',[430 255 65 18],'Callback','SP2_MM_SatRecShowSpecSubtract(1);',...
                                   'TooltipString','Visualize subraction spectrum');
fm.mm.satRecConsStr    = uicontrol('Style','Edit','Position', [260 235 260 18],'String',mm.satRecConsStr,...
                                   'BackGroundColor',pars.bgColor,'Callback','SP2_MM_SatRecConsStrUpdate',...
                                   'TooltipString',sprintf('Selection of saturation-recovery spectra to\nbe considered for display/summation [#]'));
                             
%--- analysis/visualization: T1 components (incl. summed T1 ranges) ---
fm.mm.tOneDisplLab   = text('Position',[-0.11, 0.229],'String','T1 Component','FontSize',pars.fontSize);
fm.mm.tOneFidSingle  = uicontrol('Style','Pushbutton','String','FID','Position',[120 200 60 18],'Callback','SP2_MM_T1ShowFidSingle(1);',...
                                 'TooltipString','Show single T1 component');
fm.mm.tOneSpecSingle = uicontrol('Style','Pushbutton','String','Spec','Position',[180 200 60 18],'Callback','SP2_MM_T1ShowSpecSingle(1);',...
                                 'TooltipString','Show single T1 component');
fm.mm.tOneSelDecr    = uicontrol('Style','Pushbutton','String','<<','Position',[120 180 30 18],'Callback','SP2_MM_T1SelectDecr',...
                                 'TooltipString','Scroll backward through the T1 components');
fm.mm.tOneSelect     = uicontrol('Style','Edit','Position', [150 180 40 18],'String',num2str(mm.tOneSelect),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_T1SelectUpdate',...
                                 'TooltipString','Selected T1 component to be displayed');
fm.mm.tOneSelIncr    = uicontrol('Style','Pushbutton','String','>>','Position',[190 180 30 18],'Callback','SP2_MM_T1SelectIncr',...
                                 'TooltipString','Scroll upwards through the T1 components');
fm.mm.tOneShowSuper  = uicontrol('Style','Pushbutton','String','Superpos','Position',[260 200 70 18],'Callback','SP2_MM_T1ShowSpecSuper(1);',...
                                 'TooltipString','Visualize spectrum superposition');
fm.mm.tOneShowArray  = uicontrol('Style','Pushbutton','String','Array','Position',[330 200 50 18],'Callback','SP2_MM_T1ShowSpecArray(1);',...
                                 'TooltipString','Visualize spectrum array');
fm.mm.tOneShowSum    = uicontrol('Style','Pushbutton','String','Sum','Position',[380 200 50 18],'Callback','SP2_MM_T1ShowSpecSum(1);',...
                                 'TooltipString','Visualize summation spectrum');
fm.mm.tOneShowSubtr  = uicontrol('Style','Pushbutton','String','Subract','Position',[430 200 65 18],'Callback','SP2_MM_T1ShowSpecSubtract(1);',...
                                 'TooltipString','Visualize subraction spectrum');
fm.mm.tOneShow2D     = uicontrol('Style','Pushbutton','String','2D','Position',[495 200 40 18],'Callback','SP2_MM_T1ShowSpec2D(1);',...
                                 'TooltipString','Visualize 2D analysis (ppm & T1)');
fm.mm.tOneShowSurf   = uicontrol('Style','Pushbutton','String','Surf','Position',[535 200 45 18],'Callback','SP2_MM_T1ShowSpecSurf(1);',...
                                 'TooltipString','Visualize 2D analysis (ppm & T1)');
fm.mm.tOneConsStr    = uicontrol('Style','Edit','Position', [260 180 255 18],'String',mm.tOneConsStr,...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_T1ConsStrUpdate',...
                                 'TooltipString',sprintf('T1 selection to be considered for\nsignal display/summation [#]'));             
fm.mm.tOneSpline     = uicontrol('Style','RadioButton','String','Spline','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmTOneSpline,...
                                 'Position',[0.87 0.252 .13 .03],'Callback','SP2_MM_T1SplineFlagUpdate',...
                                 'TooltipString',sprintf('Apply spline interpolation to\n1) Summation result or\n2) Spectrum to be subtracted'));

%--- spectral/T1 selection ---
fm.mm.select2DLab   = text('Position',[-0.11, 0.134],'String','Select','FontSize',pars.fontSize);
fm.mm.select2D2D    = uicontrol('Style','Pushbutton','String','2D','Position',[120 145 40 18],'Callback','SP2_MM_2DShowAndDefine;',...
                                'TooltipString','Visualize 2D analysis (ppm & T1)\nand define spetral/T1 range');
fm.mm.select2DSurf  = uicontrol('Style','Pushbutton','String','Surf','Position',[160 145 45 18],'Callback','SP2_MM_2DShowSurf(1);',...
                                'TooltipString','Visualize 2D analysis (ppm & T1)\nand define spetral/T1 range');
fm.mm.select2DSum   = uicontrol('Style','Pushbutton','String','Sum','Position',[205 145 50 18],'Callback','SP2_MM_2DShowSum(1);',...
                                'TooltipString','Visualize summation spectrum');
fm.mm.select2DSubtr = uicontrol('Style','Pushbutton','String','Subract','Position',[255 145 65 18],'Callback','SP2_MM_2DShowSubtract(1);',...
                                'TooltipString','Visualize subraction spectrum');
                             
                             
                             
%--- analysis/visualization: T1 components (incl. summed T1 ranges) ---
fm.mm.expDisplLab    = text('Position',[-0.11, 0.082],'String','Fit Analysis','FontSize',pars.fontSize);
fm.mm.expFidSingle   = uicontrol('Style','Pushbutton','String','Show','Position',[120 115 60 18],'Callback','SP2_MM_ExpFitAnalysis(1);',...
                                 'TooltipString','Show multi-exponential fitting result for given frequency position [ppm]/[point]');
fm.mm.expPpmLab      = text('Position',[0.3, 0.082],'String','ppm','FontSize',pars.fontSize);
fm.mm.expPpmDecr     = uicontrol('Style','Pushbutton','String','<<','Position',[255 115 30 18],'Callback','SP2_MM_ExpPpmSelectDecr',...
                                 'TooltipString','Reduce frequency position [ppm] to be displayed');
fm.mm.expPpmSelect   = uicontrol('Style','Edit','Position', [285 115 50 18],'String',sprintf('%.3f',mm.expPpmSelect),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ExpPpmSelectUpdate',...
                                 'TooltipString','Select frequency position [ppm] to be displayed');
fm.mm.expPpmIncr     = uicontrol('Style','Pushbutton','String','>>','Position',[335 115 30 18],'Callback','SP2_MM_ExpPpmSelectIncr',...
                                 'TooltipString','Increase frequency position [ppm] to be displayed');
fm.mm.expPpmLink     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmExpPpmLink,...
                                 'Position',[0.62 0.160 .03 .03],'Callback','SP2_MM_ExpPpmLinkFlagUpdate',...
                                 'TooltipString','Link ppm value of fit analysis to overall ppm position (for line display)');
fm.mm.expPointLab    = text('Position',[0.725, 0.082],'String','point','FontSize',pars.fontSize);
fm.mm.expPointDecr   = uicontrol('Style','Pushbutton','String','<<','Position',[455 115 30 18],'Callback','SP2_MM_ExpPointSelectDecr',...
                                 'TooltipString','Reduce frequency position [point] to be displayed');
fm.mm.expPointSelect = uicontrol('Style','Edit','Position', [485 115 40 18],'String',num2str(mm.expPointSelect),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ExpPointSelectUpdate',...
                                 'TooltipString','Select frequency position [point] to be displayed');
fm.mm.expPointIncr   = uicontrol('Style','Pushbutton','String','>>','Position',[525 115 30 18],'Callback','SP2_MM_ExpPointSelectIncr',...
                                 'TooltipString','Increase frequency position [point] to be displayed');
                             
%--- result display ---
fm.mm.amplShowLab    = text('Position',[-0.11, 0.030],'String','Amplitude','FontSize',pars.fontSize);
fm.mm.amplShowAuto   = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmAmplShow,...
                                 'String','Auto','Position',[.19 .12 .2 .03],'Callback','SP2_MM_AmplShowAutoUpdate',...
                                 'TooltipString',sprintf('Automatic determination of amplitude range'));
fm.mm.amplShowDirect = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',~flag.mmAmplShow,...
                                 'String','Direct','Position',[.29 .12 .03 .03],'Callback','SP2_MM_AmplShowDirectUpdate',...
                                 'TooltipString',sprintf('Direct assignment of amplitude range'));
fm.mm.amplShowMin    = uicontrol('Style','Edit','Position', [200 88 50 18],'String',num2str(mm.amplShowMin),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                 'TooltipString','Lower amplitude limit');
fm.mm.amplShowMax    = uicontrol('Style','Edit','Position', [250 88 50 18],'String',num2str(mm.amplShowMax),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                 'TooltipString','Upper amplitude limit');
fm.mm.ppmShowLab     = text('Position',[0.57, 0.030],'String','Frequency','FontSize',pars.fontSize);
fm.mm.ppmShowFull    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Full', ...
                                 'Value',flag.mmPpmShow,'Position',[.695 .12 .12 .03],'Callback','SP2_MM_PpmShowFullUpdate');
fm.mm.ppmShowDirect  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized', ...
                                 'Value',~flag.mmPpmShow,'Position',[.775 .12 .03 .03],'Callback','SP2_MM_PpmShowDirectUpdate');
fm.mm.ppmShowMin     = uicontrol('Style','Edit','Position', [495 88 40 18],'String',sprintf('%.2f',mm.ppmShowMin),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                 'TooltipString','Lower amplitude limit');
fm.mm.ppmShowMax     = uicontrol('Style','Edit','Position', [535 88 40 18],'String',sprintf('%.2f',mm.ppmShowMax),...
                                 'BackGroundColor',pars.bgColor,'Callback','SP2_MM_ParsUpdate',...
                                 'TooltipString','Upper amplitude limit');
fm.mm.formatLab   = text('Position',[-0.11, -0.022],'String','Format','FontSize',pars.fontSize);
fm.mm.formatReal  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Real', ...
                              'Value',flag.mmFormat==1,'Position',[.19 .078 .2 .03],'Callback','SP2_MM_FormatRealUpdate');
fm.mm.formatImag  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Imag', ...
                              'Value',flag.mmFormat==2,'Position',[.28 .078 .2 .03],'Callback','SP2_MM_FormatImagUpdate');
fm.mm.formatMagn  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Magn', ...
                              'Value',flag.mmFormat==3,'Position',[.37 .078 .2 .03],'Callback','SP2_MM_FormatMagnUpdate');
fm.mm.formatPhase = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Phase', ...
                              'Value',flag.mmFormat==4,'Position',[.46 .078 .2 .03],'Callback','SP2_MM_FormatPhaseUpdate');
fm.mm.cmapLab     = text('Position',[-0.11, -0.074],'String','Color Mode','FontSize',pars.fontSize);
fm.mm.cmapUni     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Blue', ...
                              'Value',flag.mmCMap==0,'Position',[.19 .036 .1 .03],'Callback','SP2_MM_ColormapUniUpdate');
fm.mm.cmapJet     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Jet', ...
                              'Value',flag.mmCMap==1,'Position',[.28 .036 .1 .03],'Callback','SP2_MM_ColormapJetUpdate');
fm.mm.cmapHsv     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Hsv', ...
                              'Value',flag.mmCMap==2,'Position',[.37 .036 .1 .03],'Callback','SP2_MM_ColormapHsvUpdate');
fm.mm.cmapHot     = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Hot', ...
                              'Value',flag.mmCMap==3,'Position',[.46 .036 .1 .03],'Callback','SP2_MM_ColormapHotUpdate');
fm.mm.cmapLegend  = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','String','Legend', ...
                              'Value',flag.mmCMapLegend,'Position',[.19 .005 .1 .03],'Callback','SP2_MM_ColormapLegendUpdate');
fm.mm.ppmShowPosLab    = text('Position',[0.6, -0.074],'String','Position');
fm.mm.ppmShowPos       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'Units','Normalized','Value',flag.mmPpmShowPos,...
                                   'Position',[0.69 0.036 .03 .03],'Callback','SP2_MM_PpmShowPosFlagUpdate',...
                                   'TooltipString',sprintf('Display frequency position in 2D plot'));
fm.mm.ppmShowPosVal    = uicontrol('Style','Edit','Position',[440 28 50 18],'String',num2str(mm.ppmShowPos),'BackGroundColor',pars.bgColor,...
                                   'Callback','SP2_MM_PpmShowPosValUpdate','TooltipString',sprintf('Frequency [ppm] position to be displayed'));
fm.mm.ppmShowPosAssign = uicontrol('Style','Pushbutton','String','Assign','Position',[490 28 55 18],...
                                   'FontSize',pars.fontSize,'Callback','SP2_MM_PpmShowPosAssign',...
                                   'TooltipString',sprintf('Manual assignment of frequency position [ppm]'));        
                          
                          
%--- data export ---
% fm.mm.exportMM    = uicontrol('Style','Pushbutton','String','Export MM','Position',[380 30 90 18],'Callback','SP2_MM_ExportMM',...
%                               'TooltipString','Export macromolecule (MM) spectrum to ''Processing'' page');
% fm.mm.exportMetab = uicontrol('Style','Pushbutton','String','Export Metab','Position',[470 30 90 18],'Callback','SP2_MM_ExportMetab',...
%                               'TooltipString','Export metabolite spectrum to ''Processing'' page');

  
%--- window update ---                           
SP2_MM_MacroWinUpdate
