%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
    function SP2_Stab_StabilityMain
%% 
%%  Stability analysis window
%%
%%  11-2009, Christoph Juchem
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global fm fmfig pars flag stab


SP2_ClearWindow
flag.fmWin = 2;
figPos = get(fmfig,'Position');
set(fmfig,'Name',' INSPECTOR: Data Analysis','Position',...
    [figPos(1) pars.mainDims(2) pars.mainDims(3) pars.mainDims(4)])


%********************************************************************
%   D A T A    P R O C E S S I N G    O P T I O N S
%********************************************************************
% analysis buttons
fm.stab.signal = uicontrol('Style','Pushbutton','String','Signal Analysis','FontWeight','bold','Position',[15 650 110 18],...
                           'FontSize',10,'FontName','Helvetica','Callback','SP2_Stab_DoSignalAnalysis;',...
                           'TooltipString',sprintf('Statistical analysis of signal series'));
fm.stab.noise  = uicontrol('Style','Pushbutton','String','Noise Analysis','FontWeight','bold','Position',[15 625 110 18],...
                           'FontSize',10,'FontName','Helvetica','Callback','SP2_Stab_DoNoiseAnalysis;',...
                           'TooltipString',sprintf('Statistical analysis of noise series'),'Enable','off');

%--- parameter selection ---
fm.stab.calibLab    = text('Position',[-0.12, 0.91],'String','Calib','FontSize',pars.fontSize);
fm.stab.ppmCalib    = uicontrol('Style','Edit','Position', [80 590 45 18],'String',sprintf('%.3f',stab.ppmCalib),...
                                'BackGroundColor',pars.bgColor,'Callback','SP2_Stab_PpmCalibUpdate',...
                                'TooltipString',sprintf('Frequency calibration of on-resonance [ppm]'));
fm.stab.specMagn    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,...
                                'Units','Normalized','Value',flag.stabRealMagn==0,'Position',[.24 .835 .11 .03],...
                                'String','Magn','Callback','SP2_Stab_SpecMagnUpdate',...
                                'TooltipString',sprintf('Spectral data mode: Magnitude'));
fm.stab.specReal    = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,...
                                'Units','Normalized','Value',flag.stabRealMagn==1,'Position',[.34 .835 .11 .03],...
                                'String','Real','Callback','SP2_Stab_SpecRealUpdate',...
                                'TooltipString',sprintf('Spectral data mode: Real part'));
fm.stab.phc0Lab    = text('Position',[0.44, 0.91],'String','PHC0','FontSize',pars.fontSize);
fm.stab.phc0       = uicontrol('Style','Edit','Position', [330 590 45 18],'String',sprintf('%.0f',stab.phc0),...
                               'BackGroundColor',pars.bgColor,'Callback','SP2_Stab_PhaseZeroUpdate',...
                               'TooltipString',sprintf('Zero order phase [deg]'));

fm.stab.specLab     = text('Position',[-0.12, 0.84],'String','Spectra','FontSize',pars.fontSize);
fm.stab.specFirst   = uicontrol('Style','Edit','Position', [80 550 40 18],'String',sprintf('%.0f',stab.specFirst),...
                                'BackGroundColor',pars.bgColor,'Callback','SP2_Stab_SpecFirstUpdate',...
                                'TooltipString',sprintf('First spectrum of spectral range/series'));
fm.stab.specLast    = uicontrol('Style','Edit','Position', [120 550 40 18],'String',sprintf('%.0f',stab.specLast),...
                                'BackGroundColor',pars.bgColor,'Callback','SP2_Stab_SpecLastUpdate',...
                                'TooltipString',sprintf('Last spectrum of spectral range/series'));
fm.stab.binsLab     = text('Position',[0.250, 0.84],'String','# Bins','FontSize',pars.fontSize);
fm.stab.ppmBins     = uicontrol('Style','Edit','Position', [245 550 35 18],'String',sprintf('%.0f',stab.ppmBins),...
                                'BackGroundColor',pars.bgColor,'Callback','SP2_Stab_PpmBinsUpdate',...
                                'TooltipString',sprintf('Number of frequency bins'));
fm.stab.binSelLab   = text('Position',[-0.12, 0.77],'String','Selected Bin','FontSize',pars.fontSize);
fm.stab.ppmBinSel   = uicontrol('Style','Edit','Position', [120 510 40 18],'String',sprintf('%.0f',stab.ppmBinSel),...
                                'BackGroundColor',pars.bgColor,'Callback','SP2_Stab_PpmBinSelectUpdate',...
                                'TooltipString',sprintf('Single, selected spectral bin for detailed analysis'));
fm.stab.specSelLab  = text('Position',[0.25, 0.77],'String','Selected Spectrum','FontSize',pars.fontSize);
fm.stab.specSel     = uicontrol('Style','Edit','Position', [320 510 40 18],'String',sprintf('%.0f',stab.specSel),...
                                'BackGroundColor',pars.bgColor,'Callback','SP2_Stab_SpecSelectUpdate',...
                                'TooltipString',sprintf('Single, selected spectrum for detailed analysis'));

% fm.stab.transLab     = text('Position',[0.715, 0.185],'String','Transmit');
% fm.stab.transNumDecr = uicontrol('Style','Pushbutton','String','-','Position',[470 175 22 18],'FontWeight','bold','Callback','SP2_Stab_TransmitNumDecrease');
% fm.stab.transNum     = uicontrol('Style','Edit','Position', [492 175 35 18],'String',num2str(stab.trans), ...
%                                 'HorizontalAlignment','Center','Callback','SP2_Stab_TransmitNumUpdate');          
% fm.stab.transNumIncr = uicontrol('Style','Pushbutton','String','+','Position',[527 175 22 18],'FontWeight','bold','Callback','SP2_Stab_TransmitNumIncrease');
% fm.stab.rcvrLab      = text('Position',[0.715, 0.14],'String','Receiver');
% fm.stab.rcvrNumDecr  = uicontrol('Style','Pushbutton','String','-','Position',[470 150 22 18],'FontWeight','bold','Callback','SP2_Stab_RcvrNumDecrease');
% fm.stab.rcvrNum      = uicontrol('Style','Edit','Position', [492 150 35 18],'String',num2str(stab.rcvr), ...
%                                  'HorizontalAlignment','Center','Callback','SP2_Stab_RcvrNumUpdate');          
% fm.stab.rcvrNumIncr  = uicontrol('Style','Pushbutton','String','+','Position',[527 150 22 18],'FontWeight','bold','Callback','SP2_Stab_RcvrNumIncrease');
fm.stab.totAll       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,...
                                 'Units','Normalized','Value',flag.stabTotAll,'Position',[.05 .632 .50 .03],...
                                 'String','All Frequencies / Range of Spectra','Callback','SP2_Stab_TotalAllUpdate',...
                                 'TooltipString',sprintf('All frequencies, selected range of spectra'));
fm.stab.totSel       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,...
                                 'Units','Normalized','Value',flag.stabTotSel,'Position',[.05 .588 .50 .03],...
                                 'String','All Frequencies / Single Spectrum','Callback','SP2_Stab_TotalSelectUpdate',...
                                 'TooltipString',sprintf('All frequencies, selected range of spectra'));
fm.stab.binAll       = uicontrol('Style','RadioButton','BackGroundColor',pars.bgColor,'FontSize',pars.fontSize,...
                                 'Units','Normalized','Value',flag.stabBinAll,'Position',[.05 .544 .50 .03],...
                                 'String','Frequency Bin / Range of Spectra','Callback','SP2_Stab_BinAllUpdate',...
                                 'TooltipString',sprintf('All frequencies, selected range of spectra')); 

                             
% fm.stab.maxFft   = uicontrol('Style','Pushbutton','String','Stability Analysis','FontWeight','bold','Position',[15 250 130 18],...
%                              'FontSize',10,'FontName','Helvetica','Callback','SP2_Stab_DoBinMaxFFT;',...
%                              'TooltipString',sprintf('Spectral analysis of bin-specific maximum series'));
fm.stab.stabAna   = uicontrol('Style','Pushbutton','String','Stability Analysis','FontWeight','bold','Position',[15 250 130 18],...
                              'FontSize',10,'FontName','Helvetica','Callback','SP2_Stab_StabilityAnalysis;',...
                              'TooltipString',sprintf('Comprehensive stability analysis'));

                             

%--- window update ---                           
SP2_Stab_StabilityWinUpdate

end
